### ISSUE TITLE
Icinga-Windows Agent terminated unexpectedly

### ISSUE THREAD

**Issue by phil-or** [Icinga/icinga2#7878] opened 2020-03-03 07:16 UTC
## Describe the bug

We have an Icinga production and test environment which are separated from each other.
The following error occured after an incorrect configuration in our test environment. 

Our Icinga-Agent "Icinga-Agent-Win1" is configured as an Icinga-Agent through the Director in our production environment.
Erroneously I configured Agent "Icinga-Agent-Win1" also in our test system as Icinga-Agent.

Then the test-satellites always 
tried to connect to the Agent but got a correctly certificate signature failure.
After a while the "Icinga-Agent-Win1" has terminated unexpectedly. 
I tested this case also with a Linux-Icinga-Agent where Icinga survived.

## To Reproduce

1. install two separated icinga environments
2. configure the same Windows-Agent on both environments
3. wait a while after deployment
4. Icinga terminates unexpected

## Expected behavior

However, this error should also not occur due to a incorrect config.

## Your Environment

* Version used (`icinga2 --version`): v2.11.2
* Operating System and version: W2016

## Logs:
[report.1583141547.906000.log](https://github.com/Icinga/icinga2/files/4279788/report.1583141547.906000.log)
[win_debug.log](https://github.com/Icinga/icinga2/files/4279799/win_debug.log)
[win_icinga2.log](https://github.com/Icinga/icinga2/files/4279801/win_icinga2.log)

**Comment by mcktr** [comment] 2020-03-03 20:52
Hi,

thanks for your report. Are you able to test snapshot packages on this specific agent where Icinga 2 crashed?

* http://packages.icinga.com/windows/

My assumption is that Icinga 2 hit some limit (open connections, resources) and therefore crashes. There are a lot of the following log messages:

```
[2020-03-02 10:25:38 +0100] information/ApiListener: New client connection for identity 'icingatest-satellite3' from [::ffff:192.168.1.157]:40072 (certificate validation failed: code 7: certificate signature failure)
[2020-03-02 10:25:38 +0100] critical/ApiListener: Exception while handling new API client connection: Error: bad allocation
```

```
[2020-03-02 10:32:31 +0100] notice/JsonRpcConnection: Received 'event::Heartbeat' message from identity 'icingatest-satellite4'.
```
There were a bug which involved Heartbeat message send to unauthenticated peers which leads to connections that were kept open. See #7746 This is fixed in the snapshot packages, please test them and report if the issue is resolved. :-)

**Comment by phil-or** [comment] 2020-03-05 13:11
Thanks for your advice!
I have already tested snapshot packages and can confirm that the bug is fixed.

**Comment by N-o-X** [comment] 2020-03-05 13:36
That's great news, thanks for reporting!

**Closed by N-o-X** 2020-03-05 13:36 UTC
Labels: area/windows, needs-feedback
