### ISSUE TITLE
icnga2 (redhat 6 rpm build) does not pick up group from sysconfig file

### ISSUE THREAD

**Issue by Elias481** [Icinga/icinga2#6240] opened 2018-04-18 23:56 UTC
I installed the current (2.8.2) rpm on Redhat 6. We need to configre icinga 2 to use different group but on startup (config check) it shows "invalid group specified icinga" (icinga group does not exists).

Now I compiled myself and checked the issue.
The message is generated in icinga.cpp and I could see that here the goup is correctly not hardcoded but picked up from sysconfig file - but this is not working, most probably because the ICINGA2_SYSCONFIGFILE cmake option has not been specified at configure/build time and it defaults to empty string if not explicitly set as I figured out.
The cmake should really set it to ${CMAKE_INSTALL_FULL_SYSCONFDIR}/icinga2 - that of course also means to ${CMAKE_INSTALL_PREFIX]/etc/sysconfig when the SYSCONFDIR is not specified - if not specified explicitly.
At very least the documentation should mention this setting and that it is required if behaviour of cmake configure is not changed, hopefully rpm builders would then set that explicitly (currently I cannot find this setting in INSTALL.md at all).

**Comment by dnsmichi** [comment] 2018-04-19 06:26
That's a duplicate of #6215

**Closed by dnsmichi** 2018-04-19 06:26 UTC
