### ISSUE TITLE
Recuring Downtime wrong dates specific month

### ISSUE THREAD

**Issue by cfcnigel** [Icinga/icinga2#7061] opened 2019-03-29 11:26 UTC
## Describe the bug

i have a problem with recurring downtimes in my Icinga. i have a host that is always shut down on the last Monday of the month for maintenance.

```
apply ScheduledDowntime "reboot-system-vsmo" to Host {
        author ="icingaadmin"
        comment = "Monatliche Wartung VSM-CP2"
        ranges = {
                 "monday -1" = "05:45-07:15"
                 }
        assign where host.name == "vsm_sapcp2"
}

```
For a while this worked quite well. but since last month, this does not work properly.
In IcingaWeb2 the downtime is planed for 01.04.2019 but the last monday in april is the 29th.

from debug log:

```
Evaluating segment: monday -1 april: 05:45-07:15
Considering segment: Mon Apr 29 05:45:00 2019 -> Mon Apr 29 07:15:00 2019
(best match yet)
Evaluating segment: monday -1 august: 05:45-07:15
Considering segment: Mon Aug 26 05:45:00 2019 -> Mon Aug 26 07:15:00 2019
Evaluating segment: monday -1 december: 05:45-07:15
Considering segment: Mon Dec 30 05:45:00 2019 -> Mon Dec 30 07:15:00 2019
Evaluating segment: monday -1 february: 05:45-07:15
Evaluating segment: monday -1 january: 05:45-07:15
Evaluating segment: monday -1 july: 05:45-07:15
Considering segment: Mon Jul 29 05:45:00 2019 -> Mon Jul 29 07:15:00 2019
Evaluating segment: monday -1 june: 05:45-07:15
Considering segment: Mon Jul  1 05:45:00 2019 -> Mon Jul  1 07:15:00 2019
Evaluating segment: monday -1 march: 05:45-07:15
Considering segment: Mon Apr  1 05:45:00 2019 -> Mon Apr  1 07:15:00 2019
(best match yet)
Evaluating segment: monday -1 may: 05:45-07:15
Considering segment: Mon May 27 05:45:00 2019 -> Mon May 27 07:15:00 2019
Evaluating segment: monday -1 november: 05:45-07:15
Considering segment: Mon Nov 25 05:45:00 2019 -> Mon Nov 25 07:15:00 2019
Evaluating segment: monday -1 october: 05:45-07:15
Considering segment: Mon Oct 28 05:45:00 2019 -> Mon Oct 28 07:15:00 2019
Evaluating segment: monday -1 september: 05:45-07:15
Considering segment: Mon Sep 30 05:45:00 2019 -> Mon Sep 30 07:15:00 2019
```
If I look at it that way, the result for January, February, march and june is not correct. However, all other months fit again.

## Screenshots

https://community.icinga.com/uploads/default/original/1X/0ee1bcf4b80f39490b5caef7eca6a089fe678dcb.png

## Your Environment
My System:
Ubuntu 16.04.6 LTS
Icinga2 r2.10.4-1
Icingaweb2: 2.6.2

watch Icinga forum for more infos:
https://community.icinga.com/t/recuring-downtime-wrong/740

regards,
Basti

**Comment by dnsmichi** [comment] 2019-04-08 07:36
Sounds like an off-by-one error in the timeperiod calculation code. Anyone up for a patch is more than welcome.

**Comment by lakshmanaram** [comment] 2020-10-01 20:30
@htriem I see that you've assigned this issue to yourself. Are you working on this or would it be okay if I take this up as my first issue?

**Comment by Al2Klimov** [comment] 2021-09-28 16:26
_PING_ @htriem

**Comment by julianbrost** [comment] 2021-09-29 07:29
Oh, sounds like something I've written down as "looks like this might be broken, should maybe look if this is indeed a problem" to my todo list while working on #8921.

Looks like the search for the last n-th weekday includes the first day of the following month there:
https://github.com/Icinga/icinga2/blob/8a704fb0f02727b6d7df6f7c97eb7745856eb534/lib/icinga/legacytimeperiod.cpp#L63-L75

**Comment by Al2Klimov** [comment] 2021-11-02 17:44
While working on #8921? An already merged PR?

**Comment by julianbrost** [comment] 2021-11-03 08:13
Yes? I didn't say that the PR is supposed to fix the issue. Just read "while working on #8921" as "the last time I looked at `legacytimeperiod.cpp`".

**Comment by yhabteab** [comment] 2024-08-02 12:43
I've successfully reproduced this!

```bash
[2024-06-21 00:01:00 +0000] debug/ScheduledDowntime: Creating new Downtime for ScheduledDowntime "docker-master!something-happened"
[2024-06-21 00:01:00 +0000] debug/ScheduledDowntime: Finding running scheduled downtime segment for time 1718928060 (minEnd -)
[2024-06-21 00:01:00 +0000] debug/ScheduledDowntime: Evaluating (running?) segment: monday -1: 05:45-07:15
[2024-06-21 00:01:00 +0000] debug/ScheduledDowntime: Finding next scheduled downtime segment for time 1718928060
[2024-06-21 00:01:00 +0000] debug/ScheduledDowntime: Evaluating segment: monday -1: 05:45-07:15
[2024-06-21 00:01:00 +0000] debug/ScheduledDowntime: Considering segment: Mon Jul  1 05:45:00 2024 -> Mon Jul  1 07:15:00 2024
[2024-06-21 00:01:00 +0000] debug/ScheduledDowntime: (best match yet)
```

**Closed** 2024-08-08 12:40 UTC
Labels: bug, area/runtime
