### ISSUE TITLE
default templates behave as if imported last instead of first as is documented

### ISSUE THREAD

**Issue by dwt** [Icinga/icinga2#9220] opened 2022-02-17 12:19 UTC
## Describe the bug

default templates for services and apply service interaction is buggy.

[The documentation on default templates](https://icinga.com/docs/icinga-2/latest/doc/17-language-reference/#template-imports) states that: 'Default templates are imported before any other user-specified statement in an object definition is evaluated.'.

However, when default templates and service apply rules are combined, default templates are applied _after_ all the rules of the apply rule. The effect is that the default template overrides settings done in the apply rule.

## To Reproduce
Example:

```
template Service "default-service" default {
  retry_interval = 34s
}

apply Service "ssh-users" {
  assign where host.vars.os == "Linux" && host.vars.agent_type == "ssh"
  check_command = "users"
  import "ssh-service"
  import "sntl-service"
  retry_interval = 33s
}
```

This resolves `retry_interval` to 34.

## Expected behavior

I expect to be able to override attributes in apply rules. In the given example, the attribute `retry_interval` should resolve to 33

## Screenshots

<img width="354" alt="image" src="https://user-images.githubusercontent.com/57199/154479956-76fbf7aa-7dff-435c-b288-e58784ff5a28.png">

## Your Environment

```
dwt@nathan ~/Code/Projekte/sntl/opensource/icinga (git)-[master] % docker exec icinga_icinga2_1 icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.13.0-197-g8016b013a)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.76-linuxkit
  Architecture: x86_64

Build information:
  Compiler: GNU 10.2.1
  Build host: e2e8a1183e4d
  OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* Operating System and version:

```icinga@ops:/$ uname -a
Linux ops 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 GNU/Linux
```

* Enabled features (`icinga2 feature list`): ```
icinga@ops:/$ icinga2 feature list
Disabled features: debuglog elasticsearch gelf graphite ido-mysql ido-pgsql influxdb mainlog opentsdb perfdata syslog
Enabled features: api checker icingadb notification
```

* Icinga Web 2 version and modules (System - About): ```
Icinga Web 2 Version
2.9.5
Git commit
52d51f0ee532c33f2a1ab3136d5cfd5fd20d5f4c
PHP Version
7.4.25
Git commit date
2022-02-16
```

* Config validation (`icinga2 daemon -C`): ```
* icinga@ops:/$ icinga2 daemon -C
[2022-02-17 12:18:52 +0000] information/cli: Icinga application loader (version: v2.13.0-197-g8016b013a)
[2022-02-17 12:18:52 +0000] information/cli: Loading configuration file(s).
[2022-02-17 12:18:52 +0000] information/ConfigItem: Committing config item(s).
[2022-02-17 12:18:52 +0000] information/ApiListener: My API identity: ops.zms.hosting
[2022-02-17 12:18:53 +0000] warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
[2022-02-17 12:18:53 +0000] warning/ApplyRule: Apply rule '' (in /etc/icinga2/conf.d/services.conf: 34:1-34:53) for type 'Service' does not match anywhere!
[2022-02-17 12:18:53 +0000] warning/ApplyRule: Apply rule 'icinga' (in /etc/icinga2/conf.d/services.conf: 41:1-41:22) for type 'Service' does not match anywhere!
[2022-02-17 12:18:53 +0000] warning/ApplyRule: Apply rule 'load' (in /etc/icinga2/conf.d/services.conf: 46:1-46:20) for type 'Service' does not match anywhere!
[2022-02-17 12:18:53 +0000] warning/ApplyRule: Apply rule 'procs' (in /etc/icinga2/conf.d/services.conf: 55:1-55:21) for type 'Service' does not match anywhere!
[2022-02-17 12:18:53 +0000] warning/ApplyRule: Apply rule 'swap' (in /etc/icinga2/conf.d/services.conf: 61:1-61:20) for type 'Service' does not match anywhere!
[2022-02-17 12:18:53 +0000] warning/ApplyRule: Apply rule 'users' (in /etc/icinga2/conf.d/services.conf: 67:1-67:21) for type 'Service' does not match anywhere!
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 1 IcingaDB.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 1 UserGroup.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 2 Users.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 3 ServiceGroups.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 4 TimePeriods.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 25 Services.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 3 Zones.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 2 Hosts.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 4 NotificationCommands.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 54 Notifications.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 2 HostGroups.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 1 Endpoint.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 2 ApiUsers.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 244 CheckCommands.
[2022-02-17 12:18:53 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2022-02-17 12:18:53 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2022-02-17 12:18:53 +0000] information/cli: Finished validating the configuration file(s).
```

**Comment by dwt** [comment] 2022-02-17 12:20
I should have added that ordinary defined services (without apply) seem to evaluate the templates correctly.

**Comment by dwt** [comment] 2022-02-22 08:16
This has the rather unfortunate side effect that I cannot configure the defaults for a service in the apply rule, which currently leads to many unnecessary warnings because I cannot set a longer timeout for remote check that is rather slow. :/ Is this a bug you guys can reproduce?

**Comment by dwt** [comment] 2022-03-01 10:00
ping - @developers can you guys reproduce the issue? Am I missing something? Is this a well disguised feature?

**Comment by dwt** [comment] 2022-03-07 10:23
ping @maintainers? Any info on this? Do you require additional input for me to reproduce?

**Comment by julianbrost** [comment] 2022-03-08 15:47
Looks strange indeed and the current behavior makes no sense for me:
```
root@1eaa341b7fa9:/# cat -n /etc/icinga2/conf.d/test.conf
     1	template Service "test" default {
     2	  retry_interval = 23s
     3	}
     4	
     5	object Host "test" {
     6	  check_command = "dummy"
     7	}
     8	
     9	apply Service "test" {
    10	  assign where true
    11	  check_command = "dummy"
    12	  retry_interval = 42s
    13	}
root@1eaa341b7fa9:/# icinga2 daemon -C
[2022-03-08 15:45:27 +0000] information/cli: Icinga application loader (version: v2.13.0-235-gbf5b90570)
[2022-03-08 15:45:27 +0000] information/cli: Loading configuration file(s).
[2022-03-08 15:45:27 +0000] information/ConfigItem: Committing config item(s).
[2022-03-08 15:45:27 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2022-03-08 15:45:27 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2022-03-08 15:45:27 +0000] information/ConfigItem: Instantiated 1 Service.
[2022-03-08 15:45:27 +0000] information/ConfigItem: Instantiated 3 Zones.
[2022-03-08 15:45:27 +0000] information/ConfigItem: Instantiated 1 Host.
[2022-03-08 15:45:27 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-03-08 15:45:27 +0000] information/ConfigItem: Instantiated 1 Endpoint.
[2022-03-08 15:45:27 +0000] information/ConfigItem: Instantiated 244 CheckCommands.
[2022-03-08 15:45:27 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2022-03-08 15:45:27 +0000] information/cli: Finished validating the configuration file(s).
root@1eaa341b7fa9:/# icinga2 object list -t Service
Object 'test!test' of type 'Service':
  % declared in '/etc/icinga2/conf.d/test.conf', lines 9:1-9:20
  * __name = "test!test"
  * action_url = ""
  * check_command = "dummy"
    % = modified in '/etc/icinga2/conf.d/test.conf', lines 11:3-11:25
  * check_interval = 300
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "test"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_ignore_states = null
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "test"
    % = modified in '/etc/icinga2/conf.d/test.conf', lines 9:1-9:20
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
  * name = "test"
    % = modified in '/etc/icinga2/conf.d/test.conf', lines 9:1-9:20
  * notes = ""
  * notes_url = ""
  * package = "_etc"
    % = modified in '/etc/icinga2/conf.d/test.conf', lines 9:1-9:20
  * retry_interval = 23
    % = modified in '/etc/icinga2/conf.d/test.conf', lines 12:3-12:22
    % = modified in '/etc/icinga2/conf.d/test.conf', lines 2:3-2:22
  * source_location
    * first_column = 1
    * first_line = 9
    * last_column = 20
    * last_line = 9
    * path = "/etc/icinga2/conf.d/test.conf"
  * templates = [ "test", "test" ]
    % = modified in '/etc/icinga2/conf.d/test.conf', lines 9:1-9:20
    % = modified in '/etc/icinga2/conf.d/test.conf', lines 1:0-1:30
  * type = "Service"
  * vars = null
  * volatile = false
  * zone = ""
```

**Comment by dwt** [comment] 2022-03-11 06:55
@julianbrost Do you guys plan to fix this behaviour? Can you suggest a workaround until this gets fixed?

I had the idea pull out the customization into it's own template to enforce it overriding the inherited template that way. Not pretty, but might work? Do you maybe see a better way?

**Comment by yhabteab** [comment] 2022-03-11 08:25
Duplicate of #7914

**Comment by dwt** [comment] 2022-03-15 08:44
#7929 seems to be an attempt at fixing this, but seems stale / blocked. Are there known workarounds in the meantime?

**Closed** 2022-03-22 09:19 UTC
Labels: bug, area/configuration
