### ISSUE TITLE
Classic-UI / avail.cgi - fixed periods doesnt work

### ISSUE THREAD

**Issue by avik78** [Icinga/icinga2#6346] opened 2018-05-31 13:22 UTC
Selecting Yesterday, Last week, Last month gives % Time Undetermined - 100%
Selecting Last 24hours, Last7 days, This month gives correct numbers

-->

## Expected Behavior
Expect Availibility report to be correct for all defined periods

## Current Behavior
Doesn't work for

timeperiod=yesterday
timeperiod=lastweek
timeperiod=lastmonth

Works fine for 
timeperiod=last24hours
timeperiod=thisweek
timeperiod=thismonth

## Steps to Reproduce (for bugs)

1. In Classic-UI, select "Availability"
2. Select type and period
3. Verify the findings over
4.

## Your Environment

* Version used (`icinga2 --version`): 2.8.4
* Operating System and version: Ubuntu 16.04
* Enabled features (`icinga2 feature list`):
* Classic-UI version: 1.13.3

**Comment by Napsty** [comment] 2018-05-31 15:13
I can confirm the findings of @avik78 . 

In our PROD Icinga installation, still running Icinga2 2.6.1 and Classic-UI 1.13.3 the availability stats are working (and are an important tool for our internal SLA calculation).

In our new/future Prod Icinga installation, running Icinga2 2.8.2 and Classic-UI 1.13.3 the availability stats are not all working, some are.

**Working**
- Today (timeperiod=today)
- Last 24 hours (timeperiod=last24hours)
- This week (timeperiod=thisweek)
- Last 7 Days (timeperiod=last7days)
- This Month (timeperiod=thismonth)
- Last 31 Days (timeperiod=last31days)
- This Year (timeperiod=thisyear)


**Not working**
- Yesterday (timeperiod=yesterday)
- Last Week (timeperiod=lastweek)
- Last Month (timeperiod=lastmonth)
- Last Year (timeperiod=lastyear)

So calculations including data up to this moment/now work. But data from the past are not shown.

As I have some of the same services already checked in our future prod environment (2.8) and in our current prod environment (2.6), I can show stats from the same service.

**avail.cgi on 2.6**
URL: http://icinga26/cgi-bin/icinga2-classicui/avail.cgi?t1=1483225200&t2=1514761199&show_log_entries=&host=MyLoadBalancer&service=HTTP&assumeinitialstates=yes&assumestateretention=yes&assumestatesduringnotrunning=yes&includesoftstates=no&initialassumedhoststate=0&initialassumedservicestate=0&timeperiod=lastmonth&backtrack=8

Json output (the relevant part):

```
"avail": {
"service_availability": {
"services": [
{ "host_name": "MyLoadBalancer",  "host_display_name": "MyLoadBalancer",  "service_description": "HTTP",  "service_display_name": "HTTP",  "time_ok_scheduled": 1411,  "percent_time_ok_scheduled": 0.054,  "percent_known_time_ok_scheduled": 0.059,  "time_ok_unscheduled": 2381698,  "percent_time_ok_unscheduled": 91.887,  "percent_known_time_ok_unscheduled": 99.412,  "total_time_ok": 2383109,  "percent_total_time_ok": 91.941,  "percent_known_time_ok": 99.471,  "time_warning_scheduled": 0,  "percent_time_warning_scheduled": 0.000,  "percent_known_time_warning_scheduled": 0.000,  "time_warning_unscheduled": 0,  "percent_time_warning_unscheduled": 0.000,  "percent_known_time_warning_unscheduled": 0.000,  "total_time_warning": 0,  "percent_total_time_warning": 0.000,  "percent_known_time_warning": 0.000,  "time_unknown_scheduled": 0,  "percent_time_unknown_scheduled": 0.000,  "percent_known_time_unknown_scheduled": 0.000,  "time_unknown_unscheduled": 0,  "percent_time_unknown_unscheduled": 0.000,  "percent_known_time_unknown_unscheduled": 0.000,  "total_time_unknown": 0,  "percent_total_time_unknown": 0.000,  "percent_known_time_unknown": 0.000,  "time_critical_scheduled": 33,  "percent_time_critical_scheduled": 0.001,  "percent_known_time_critical_scheduled": 0.001,  "time_critical_unscheduled": 12647,  "percent_time_critical_unscheduled": 0.488,  "percent_known_time_critical_unscheduled": 0.528,  "total_time_critical": 12680,  "percent_total_time_critical": 0.489,  "percent_known_time_critical": 0.529,  "time_undetermined_not_running": 0,  "percent_time_undetermined_not_running": 0.000,  "time_undetermined_no_data": 196210,  "percent_time_undetermined_no_data": 7.570,  "total_time_undetermined": 196210,  "percent_total_time_undetermined": 7.570,  "total_time_all": 2591999,  "percent_total_time_all": 100.000,  "percent_known_time_all": 100.000,
"log_entries": [
{ "start_time_string": "04-03-2018 06:30:10",  "start_time_timestamp": 1522729810,  "end_time_string": "04-03-2018 07:00:00",  "end_time_timestamp": 1522731600,  "duration_string": "0d 0h 29m 50s",  "duration_timestamp": 1790,  "entry_type": "SERVICE OK",  "state_type": "HARD",  "state_information": "HTTP OK: HTTP/1.1 200 OK - 853 bytes in 0.005 second response time"},
{ "start_time_string": "04-03-2018 07:00:00",  "start_time_timestamp": 1522731600,  "end_time_string": "04-03-2018 09:00:09",  "end_time_timestamp": 1522738809,  "duration_string": "0d 2h 0m 9s",  "duration_timestamp": 7209,  "entry_type": "SERVICE OK",  "state_type": "HARD",  "state_information": "HTTP OK: HTTP/1.1 200 OK - 853 bytes in 0.005 second response time"},
[...]
```

**avail.cgi on 2.8**
URL: http://icinga28/cgi-bin/icinga2-classicui/avail.cgi?t1=1483225200&t2=1514761199&show_log_entries=&host=MyLoadBalancer&service=HTTP&assumeinitialstates=yes&assumestateretention=yes&assumestatesduringnotrunning=yes&includesoftstates=no&initialassumedhoststate=0&initialassumedservicestate=0&timeperiod=lastmonth&backtrack=8

Json output (the relevant part):

```
"avail": {
"service_availability": {
"services": [
{ "host_name": "MyLoadBalancer",  "host_display_name": "MyLoadBalancer",  "service_description": "HTTP",  "service_display_name": "HTTP",  "time_ok_scheduled": 0,  "percent_time_ok_scheduled": 0.000,  "percent_known_time_ok_scheduled": 0.000,  "time_ok_unscheduled": 0,  "percent_time_ok_unscheduled": 0.000,  "percent_known_time_ok_unscheduled": 0.000,  "total_time_ok": 0,  "percent_total_time_ok": 0.000,  "percent_known_time_ok": 0.000,  "time_warning_scheduled": 0,  "percent_time_warning_scheduled": 0.000,  "percent_known_time_warning_scheduled": 0.000,  "time_warning_unscheduled": 0,  "percent_time_warning_unscheduled": 0.000,  "percent_known_time_warning_unscheduled": 0.000,  "total_time_warning": 0,  "percent_total_time_warning": 0.000,  "percent_known_time_warning": 0.000,  "time_unknown_scheduled": 0,  "percent_time_unknown_scheduled": 0.000,  "percent_known_time_unknown_scheduled": 0.000,  "time_unknown_unscheduled": 0,  "percent_time_unknown_unscheduled": 0.000,  "percent_known_time_unknown_unscheduled": 0.000,  "total_time_unknown": 0,  "percent_total_time_unknown": 0.000,  "percent_known_time_unknown": 0.000,  "time_critical_scheduled": 0,  "percent_time_critical_scheduled": 0.000,  "percent_known_time_critical_scheduled": 0.000,  "time_critical_unscheduled": 0,  "percent_time_critical_unscheduled": 0.000,  "percent_known_time_critical_unscheduled": 0.000,  "total_time_critical": 0,  "percent_total_time_critical": 0.000,  "percent_known_time_critical": 0.000,  "time_undetermined_not_running": 0,  "percent_time_undetermined_not_running": 0.000,  "time_undetermined_no_data": 2591999,  "percent_time_undetermined_no_data": 100.000,  "total_time_undetermined": 2591999,  "percent_total_time_undetermined": 100.000,  "total_time_all": 2591999,  "percent_total_time_all": 100.000,  "percent_known_time_all": 100.000,
"log_entries": [

]

}
]
}
}
}
```

Note the completely missing log entries... I think that's why the calculations are wrong (nothing to calculate from).

**Comment by lazyfrosch** [comment] 2018-06-01 07:16
Classic UI is part of https://github.com/Icinga/icinga-core and our support for the integration will slowly end.

Although ClassicUI availability is based on the classic icinga.log (feature `compatlog`).

I'm not aware of any issues with `compatlog` itself.

**Comment by Napsty** [comment] 2018-06-01 10:07
Interesting:

```
root@icinga26:~#  md5sum /usr/lib/cgi-bin/icinga/avail.cgi
6567f29c05e978724b6ccd4487ccdfb6  /usr/lib/cgi-bin/icinga/avail.cgi

root@icinga28:~# md5sum /usr/lib/cgi-bin/icinga/avail.cgi
11b058069f043aa6a766514842519726  /usr/lib/cgi-bin/icinga/avail.cgi
```

So 1.13.3 != 1.13.3 ?

```
root@icinga26:~#  dpkg -l|grep icinga-cgi-bin | awk '{print $1" "$2" "$3}'
ii icinga-cgi-bin 1.13.3-1~ppa1~trusty1

root@icinga28:~#  dpkg -l|grep icinga-cgi-bin | awk '{print $1" "$2" "$3}'
ii icinga-cgi-bin 1.13.3-2ubuntu0.1
```

**Comment by Napsty** [comment] 2018-06-01 10:41
New comment to separate a bit...
OK scratch that with the different packages. I re-installed 1.13.3-2ubuntu0.1 again and Last Month and Last Week still work. Yesterday is still empty.

Seems to be a permission problem with the log files.
Make sure you adjust the folder and file permissions:

```
root@icinga28:/var/log/icinga2# ll
total 109488
drwxr-s--x 3 nagios   adm        4096 May 22 14:59 compat
drwxr-s--x 2 nagios   adm        4096 Mar 22 12:30 crash
-rw-r--r-- 1 nagios   nagios 19520212 Jun  1 12:36 icinga2.log
-rw-r--r-- 1 nagios   nagios 75700456 Jun  1 06:25 icinga2.log.1
-rw-r--r-- 1 nagios   nagios  2835443 May 31 06:25 icinga2.log.2.gz
-rw-r--r-- 1 nagios   nagios  2821382 May 30 06:25 icinga2.log.3.gz
-rw-r--r-- 1 nagios   nagios  2810021 May 29 06:25 icinga2.log.4.gz
-rw-r--r-- 1 nagios   nagios  2799383 May 28 06:25 icinga2.log.5.gz
-rw-r--r-- 1 nagios   nagios  2797273 May 27 06:25 icinga2.log.6.gz
-rw-r--r-- 1 nagios   nagios  2793939 May 26 06:25 icinga2.log.7.gz
-rw-r--r-- 1 www-data adm           0 Jun  1 11:47 icinga-cgi.log
-rw-r--r-- 1 root     adm        1144 May 12 09:05 startup.log

root@icinga28:/var/log/icinga2# chmod 755 compat/
root@icinga28:/var/log/icinga2/compat# chmod 755 archives/
root@icinga28:/var/log/icinga2/compat# chmod 644 icinga.log
root@icinga28:/var/log/icinga2/compat/archives# chmod 644 *
```

Not sure yet how the permissions will be after a rotate from Icinga2 though.

**Comment by avik78** [comment] 2018-06-01 11:44
I found the same thing - I'll probably add a cron job to add the permission, so that is fixable.

My concern now is that I only seem to have 4 weeks of logs in /var/log/icinga2/compat/archive - and I would like to increase that to X weeks. Now - if any idea on how to do that, I'd appreciate any tip.

I use the Classic UI only for these reports, so whenever I learn an "easy" way to do SLA reporting, I'll probably go down that road.

Thanks.


Ole

**Comment by Napsty** [comment] 2018-06-01 12:16
> I use the Classic UI only for these reports

I'm currently relying on the Classic UI for SLA reporting as well. 

But recently I came across this howto: https://monitoring-portal.org/t/grafana-for-service-host-sla-graphs/2408 from @Mikesch-mp . Graphing the SLA values in Grafana would be overkill for your and my usage. But maybe he can help (SQL queries from the IDO)?

**Comment by dnsmichi** [comment] 2018-06-01 12:19
I fail to see how this is related to Icinga 2 ... you're using the 1.x cgis here which do something "weird". Keep in mind that 1.x won't receive any fixes either, this is EOL.

The `compatlog` feature will be deprecated with 2.9, which in term means that the developers won't fix any bugs in this feture (except for security).

**Closed by dnsmichi** 2018-06-01 12:19 UTC
Labels: Compat, needs-feedback
