### ISSUE TITLE
Upgrading from 2.7.2-1 to 2.8.0-1 via Ubuntu packages fails with duplicate key name error

### ISSUE THREAD

**Issue by bkeifer** [Icinga/icinga2#5781] opened 2017-11-20 15:52 UTC
Repository: 

## Expected Behavior
Upgrade should succeed.

## Current Behavior
Upgrade fails with database error:
```An error occurred while upgrading the database:

mysql said: ERROR 1061 (42000) at line 68: Duplicate key name
'idx_downtimehistory_remove'
```

## Your Environment
Installed from `deb http://ppa.launchpad.net/formorer/icinga/ubuntu trusty main`

* Version used (`icinga2 --version`):
```# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.5 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 3.16.0-77-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.2
  Build host: b86032943218
```

* Operating System and version:
```Linux icinga 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```

* Enabled features (`icinga2 feature list`):
```# icinga2 feature list
Disabled features: compatlog elasticsearch gelf icingastatus influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command debuglog graphite ido-mysql mainlog notification```

**Comment by dnsmichi** [comment] 2017-11-20 16:08
Duplicate of #5778 

Please check with dbconfig-common and open Debian packaging issues over at icinga/icinga-packaging.

**Closed** 2017-11-20 16:09 UTC
Labels: DB IDO, duplicate, Packages

**Comment by bkeifer** [comment] 2017-11-20 16:21
So if this is a long-standing debian/ubuntu issue, are we just stuck on 2.7.2 until it's fixed or we do a fresh install from scratch?  Is there a way to get past this?

**Comment by dnsmichi** [comment] 2017-11-20 16:25
I see you are using a community PPA. Might be worthwhile to try the official packages from packages.icinga.com as an alternative.

**Comment by TryTryAgain** [comment] 2017-11-28 13:49
I'm having the same issue with the packages.icinga.com repo, not sure what the fix would be.

**Comment by log1-c** [comment] 2017-11-30 16:05
It works if you don't let dbconfig-common update your schema but do it yourself:
mysql -u root -p [icinga2 database] < /usr/share/icinga2-ido-mysql/schema/upgrade/<version>.sql

**Comment by dnsmichi** [comment] 2017-11-30 19:03
Right. This is a longstanding problem with dbconfig-common (a Debian upstream tool) which sometimes executes upgrade SQL files twice or more often. I for myself don't let dbconfig-common manage the database, but do that manually - the same as I am used to on RPM based systems.

**Comment by remy1991** [comment] 2019-08-23 10:41
Hey, I am following the manual upgrade steps and moving from 2.6 to 2.10. 
Now everything worked fine and I selected manual schema upgrade strategy but when i am running 'mysql -u root -p [icinga2 database] < /usr/share/icinga2-ido-mysql/schema/upgrade/2.8.0.sql' command, it keeps throwing "ERROR 1061 (42000) at line 68: Duplicate key name 'idx_downtimehistory_remove'". 

I applied 2.8.1.sql file and it worked fine. I am performing rolling upgrade to my satellites and one of the satellite is facing the issue (maybe due to some step missed from my side). Is there a way to resolve this?. Reverting back to 2.6 worked fine but after upgrading to 2.10 again is giving the same issue. I am also trying to figure out the consequences of running the satellite even after applying 2.8.0.sql failed? Should I recreate the satellite?
