### ISSUE TITLE
ScheduledDowntime objects do create a new Downtime immediately

### ISSUE THREAD

**Issue by marcofl** [Icinga/icinga2#6091] opened 2018-02-14 17:39 UTC
We use ScheduledDowntime apply rules to downtime services completely which are not yet fully in production, etc. We do this by setting a variable on such hosts and services and then using this variable to assign the downtimes.

```
apply ScheduledDowntime "service_downtime_test" to Service {
  author = "Automatic Downtime"
  comment = "Test 24x7 downtime"
  assign where service.vars.example
  ranges = {
      "monday - sunday" = "00:00-24:00"
  }
}
```
This downtime then starts only the next day / or even the next range entry, not immediately as one would expect:
Example: now it's Feb 14, ~18:32
```
Fixed downtime by Automatic Downtime created 2m 6s ago ǀ scheduled on Feb 19 expires on Feb 20 
```
or with:
```
  ranges = {
    "friday" = "00:00-24:00"
    "monday" = "00:00-24:00"
    "saturday" = "00:00-24:00"
    "sunday" = "00:00-24:00"
    "thursday" = "00:00-24:00"
    "tuesday" = "00:00-24:00"
    "wednesday" = "00:00-24:00"
  }
```
```
Fixed downtime by Automatic Downtime created 0m 32s ago ǀ scheduled on Feb 15 00:00 expires in 1d 5h 
```
On the next day, there will be 2 downtimes, one for the current day and one for the next day. 

## Expected Behavior
A downtime with ranges reflecting "always" should be active immediately after config load.   

## Current Behavior
The downtime will start at the next day. There is no downtime create for the current day. 

## Possible Solution
I don't know, but this needs to be fixed somehow or there should be a range "always" which does as one would expect from "aways", means starting right now. 

## Steps to Reproduce (for bugs)
1. Create a downtime apply rule that applies to at least one service:
```
apply ScheduledDowntime "service_downtime_test" to Service {
  author = "Automatic Downtime"
  comment = "Test 24x7 downtime"
  assign where service.vars.example
  ranges = {
      "monday - sunday" = "00:00-24:00"
  }
}
```
2. check icingaweb2 after icinga2 reload and you'll see that the downtime is not active yet.

## Context
The problem is that, when new services are added to icinga2 (happens automatically via puppet for example) which should be downtimed, the downtime will start the next day instead of now and the service will pop up as unhandled in icingaweb2, notifications will be sent, etc. 

## Your Environment

* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: Ubuntu 16.04
* Enabled features (`icinga2 feature list`): Enabled features: api checker command ido-mysql influxdb mainlog notification
* Icinga Web 2 version and modules (System - About): 2.5.1-1.xenial
* Config validation (`icinga2 daemon -C`): 
```
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Please read the upgrading documentation for v2.8: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
information/ApiListener: My API identity: icinga-server.vagrant.dev
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 212 CheckCommands.
information/ConfigItem: Instantiated 30 Downtimes.
information/ConfigItem: Instantiated 4 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2 Hosts.
information/ConfigItem: Instantiated 4 Dependencies.
information/ConfigItem: Instantiated 2 TimePeriods.
information/ConfigItem: Instantiated 79 Services.
information/ConfigItem: Instantiated 2 ServiceGroups.
information/ConfigItem: Instantiated 9 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by marcofl** [comment] 2018-02-14 17:48
a downtime object looks like this, when no downtime is active yet:
```
Object 'icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0' of type 'Downtime':
  % declared in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 1:0-1:59
  * __name = "icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0"
  * author = "Automatic Downtime"
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 2:2-2:30
  * comment = "Test 24x7 downtime"
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 3:2-3:32
  * config_owner = "icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!service_downtime_test5"
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 4:2-4:106
  * duration = 0
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 5:2-5:20
  * end_time = 1519081200
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 6:2-6:29
  * entry_time = 1518630404.816010
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 7:2-7:31
  * fixed = true
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 8:2-8:13
  * host_name = "icinga-server.vagrant.dev"
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 9:2-9:40
  * name = "icinga-server-1518630404-0"
  * package = "_api"
  * scheduled_by = "icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!service_downtime_test5"
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 10:2-10:106
  * service_name = "random_master_icinga-server.vagrant.dev"
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 11:2-11:57
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 59
    * last_line = 1
    * path = "/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf"
  * start_time = 1518994800
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 12:2-12:31
  * templates = [ "icinga-server-1518630404-0" ]
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 1:0-1:59
  * triggered_by = ""
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 13:2-13:18
  * type = "Downtime"
  * zone = "master"
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-server-1518126579-1/conf.d/downtimes/icinga-server.vagrant.dev!random_master_icinga-server.vagrant.dev!icinga-server-1518630404-0.conf', lines 15:2-15:16
```

**Comment by dgoetz** [comment] 2018-02-15 07:23
I think this is a duplicate of https://github.com/Icinga/icinga2/issues/4790

**Comment by dnsmichi** [comment] 2018-02-15 07:30
Could be related, not sure though. The ScheduledDowntime code is known to be buggy.

**Comment by melaniebauer** [comment] 2018-06-12 07:16
I am experiencing the same problem. Every time I restart icinga, all my nicely schedule-downtimed hosts show up as problems. I would be very happy if you fixed that. Apart from that, icinga2 is really doing well, thanks for all the work. :-)

**Comment by dnsmichi** [comment] 2018-07-03 17:55
After re-reading this again, this is a duplicate like @dgoetz mentioned. I know that @marcofl wants to be fixed, we're waiting for his feedback on Eric's mail. Closing here, proceed in the linked issue please.

**Closed by dnsmichi** 2018-07-03 17:55 UTC
Labels: Configuration, Notifications
