### ISSUE TITLE
v2.8.4 segmentation fault for every ~100 execution of icinga2 daemon -C

### ISSUE THREAD

**Issue by stefanandres** [Icinga/icinga2#6291] opened 2018-05-08 08:43 UTC
We have a icinga service check that runs icinga2 daemon -C every 5 minutes.

Before upgrading to 2.8.4 (we were on 2.8.2 before, skipped the .3 release) we never experienced this issue.
Now, the command will fail every ~100 runs though:

```
i=0; while icinga2 daemon -C; do echo $((++i)); done
[...]
93
[2018-05-08 10:33:25 +0200] warning/icinga-app: Sysconfig file '/etc/sysconfig/icinga2' cannot be read. Using default values.
[2018-05-08 10:33:25 +0200] warning/icinga-app: Sysconfig file '/etc/sysconfig/icinga2' cannot be read. Using default values.
information/cli: Icinga application loader (version: r2.8.4-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Please read the upgrading documentation for v2.8: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
information/ApiListener: My API identity: foo.icinga2.stage.master01
information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 25000, rate: 7891.78/s (473507/min 473507/5min 473507/15min);
information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 0, rate:  0/s (0/min 0/5min 0/15min);
warning/ApplyRule: Apply rule 'cassandra' (in /etc/icinga2/zones.d/globals.d/services.conf: 229:1-229:33) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'gitlab' (in /etc/icinga2/zones.d/globals.d/services.conf: 517:1-517:30) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'puppet_client_cert_expiration' (in /etc/icinga2/zones.d/globals.d/services.conf: 1151:1-1151:53) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'rabbitmqs' (in /etc/icinga2/zones.d/globals.d/services.conf: 1226:1-1226:33) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'smtps' (in /etc/icinga2/zones.d/globals.d/services.conf: 1315:1-1315:29) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 6 Zones.
information/ConfigItem: Instantiated 8 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 6 ApiUsers.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 54578 Notifications.
information/ConfigItem: Instantiated 1 NotificationCommand.
information/ConfigItem: Instantiated 11 CheckCommands.
information/ConfigItem: Instantiated 970 Downtimes.
information/ConfigItem: Instantiated 406 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2693 Hosts.
information/ConfigItem: Instantiated 238 UserGroups.
information/ConfigItem: Instantiated 50637 Dependencies.
information/ConfigItem: Instantiated 301 Users.
information/ConfigItem: Instantiated 4 TimePeriods.
information/ConfigItem: Instantiated 59621 Services.
information/ConfigItem: Instantiated 1 ServiceGroup.
information/ConfigItem: Instantiated 560 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
94
[2018-05-08 10:33:41 +0200] warning/icinga-app: Sysconfig file '/etc/sysconfig/icinga2' cannot be read. Using default values.
[2018-05-08 10:33:41 +0200] warning/icinga-app: Sysconfig file '/etc/sysconfig/icinga2' cannot be read. Using default values.
information/cli: Icinga application loader (version: r2.8.4-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Please read the upgrading documentation for v2.8: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
information/ApiListener: My API identity: foo.icinga2.stage.master01
Segmentation fault
```

![screen shot 2018-05-08 at 10 41 23](https://user-images.githubusercontent.com/2674469/39747022-6535b9e0-52ac-11e8-8a29-fd3905f35742.png)
(we are caching the result, that's why even for a few re-checks it will report critical)

## Expected Behavior
* icinga2 daemon -C should never fail with segmentation fault.
* More logging

## Current Behavior
Every ~100 runs icinga2 daemon -C will fail with segmentation fault (on a big installation)

## Steps to Reproduce (for bugs)
1. Run ```i=0; while icinga2 daemon -C; do echo $((++i)); done``` on a big (see above) installation
2. Wait until it fails 

## Your Environment
* Ubuntu 16.04
* Master-Master, multiple satellites (only on the active ido-master the error occurs)

**Comment by dnsmichi** [comment] 2018-05-08 09:00
Can you please run it with gdb and attach the stacktrace? Instructions can be found in the development documentation chapter.

**Comment by stefanandres** [comment] 2018-05-08 09:42
Yep, running now with, I'll wait for the next crash:
```
{ i=0; while gdb --batch --ex='r' --ex "thread apply all bt full" --args /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2  daemon -x debug --no-stack-rlimit -C; do echo $((++i)); done; date; } > /tmp/icinga.crash 2>&1
```

**Comment by stefanandres** [comment] 2018-05-08 10:59
Here is the gdg output from the failed execution:
https://gist.github.com/stefanandres/df102c7c955e5aaf969d8a2a54bda232

**Comment by gunnarbeutner** [comment] 2018-05-08 11:13
This is most likely a duplicate of #6279.

**Closed by gunnarbeutner** 2018-05-08 11:13 UTC
Labels: CLI, Crash, needs-feedback
