### ISSUE TITLE
Flapping & Flapping_Current is empty when using it as macro

### ISSUE THREAD

**Issue by Duffkess** [Icinga/icinga2#6024] opened 2018-01-22 10:06 UTC
I want to create a powershell based eventhandler on Windows systems.

Currently I parse the following information to the script:
-servicename $service.vars.service_win_service$ -state $service.state_id$ -attempt $service.check_attempt$ -statetype $service.state_type$ -downtimes $service.downtime_depth$

which works just fine. But when I try to add $service.flapping$ and $service.flapping_current$ it just returns as "false" for flapping and "0" for current. When I use the Directors Object Inspection I can see "true" for flaping and some value (like 55..0)  for current.

So it seems that these Attributes dont get resolved correct at this point.

I'm using CentOS with Icinga 2.8.0 Server and Client Version.

**Comment by Crunsher** [comment] 2018-01-23 08:25
Flapping is currently not implemented on Windows, in an oversight this was not documented correctly. So the macros are being resolved but just return 0 when run on Windows.

The master has the correct values as computation is done per node.
I'm closing this as a duplicate of the new #6025

**Closed by Crunsher** 2018-01-23 08:25 UTC
