### ISSUE TITLE
Windows service reload after config change fails while running as NT Authority

### ISSUE THREAD

**Issue by N-o-X** [Icinga/icinga2#6318] opened 2018-05-18 08:47 UTC
The reload on config change fails on windows while running as a service (User: NT Authority).
This issue has been introduced with #6116.

The validating instance is logging the following:

`[2018-05-18 09:28:47 +0200] critical/cli: Failed to open service manager. Error code: 5`

Which results to this (#6316) misleading message being logged in the main instance:

`[2018-05-18 09:28:47 +0200] critical/Application: Found error in config: reloading aborted`

It seams like `OpenSCManager()` requires the user to be an administrator.

The service was installed with user `Administrator` and is running as user `NT Authority`

**Comment by dnsmichi** [comment] 2018-05-18 08:54
This should be fixed prior to releasing 2.9 @lippserd

**Comment by N-o-X** [comment] 2018-05-18 09:02
Would be great if someone could confirm this issue. Could also be an issue with my windows setup.

**Comment by dnsmichi** [comment] 2018-05-18 09:32
Consider this a task with @Crunsher next week. Gunnar and myself are bound to different projects.

**Comment by Crunsher** [comment] 2018-05-29 11:48
Relevant document: https://msdn.microsoft.com/en-us/library/windows/desktop/aa379283(v=vs.85).aspx

I can't reproduce this somehow, but setting the ACLs during the node agent should :tm: fix this issue

**Comment by dnsmichi** [comment] 2018-06-04 14:40
Seems to be a different problem, will investigate after @N-o-X returns.

**Comment by Crunsher** [comment] 2018-06-08 08:00
#6353 Fixes this

**Comment by Crunsher** [comment] 2018-06-14 08:46
Closed as invalid since the reload behavior changed

**Closed by Crunsher** 2018-06-14 08:46 UTC
Labels: Windows, bug, high-priority
