### ISSUE TITLE
[dev.icinga.com #12793] Unnecessary notifications when service is NOT-OK but becomes reachable (Host UP)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4689] opened 2016-09-25 22:21 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12793

**Created by julianbrost on 2016-09-25 22:21:20 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-25 22:21:20 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

When a host and its services all start in a hard down/critical/warning state (for example because a reboot takes long enough), and the host comes back up, notifications for services are sent out, as they are in a hard critical state, even though they would recover shortly after. This often happens when a host reboots outside of a scheduled downtime.

This can be reproduced with the following dummy host and service. The host will just change its state every minute between up and down, the service will do the same just delayed by 10 seconds.

    object Host "dummy-host" {
        check_command = "dummy"
        check_interval = 10s
        retry_interval = 10s
        max_check_attempts = 3
        enable_flapping = false
        vars.dummy_state = {{
            return (((DateTime() - DateTime(0)) / 60) % 2) * 2
        }}
    }

    object Service "dummy-service" {
        host_name = "dummy-host"

        check_command = "dummy"
        check_interval = 10s
        retry_interval = 10s
        max_check_attempts = 3
        enable_flapping = false
        vars.dummy_state = {{
            return (((DateTime() - DateTime(10)) / 60) % 2) * 2
        }}
    }

This will generate the following notifications where the last two are pretty much useless in my opinion:

    23:57:17  PROBLEM - dummy-host is DOWN
    23:58:03  RECOVERY - dummy-host is UP
    23:58:07  PROBLEM - dummy-host - dummy-service is CRITICAL
    23:58:17  RECOVERY - dummy-host - dummy-service is OK

There might be two fixes for this, but I don't know if they have unintended side-effects:

1.  When a services changes from unreachable to reachable, make it start in a soft state if it wasn't already down before it became unreachable.
2.  Don't count checks agains the max checks limit while the service is unreachable so that it won't change to a hard state while it's unreachable.

I used the terms host and service but I think this also applies to service-service dependencies (I didn't test that though).

**Attachments**

* [icinga-debug-log.txt](https://dev.icinga.com/attachments/download/3660/icinga-debug-log.txt) julianbrost - _2016-09-25 22:19:34 +00:00_

**Comment by terra-nova** [comment] 2017-04-02 20:49
This one bugs me as well.

Just a few days ago a VPN link to one of our customers went AWOL, and everything stayed quiet (thanks to host dependencies)... until the VPN link came back up. The second it did, our ticket system got swamped with 300+ new tickets, all of them reporting out-of-date UNKNOWN service states from __before__ the host recovery of the VPN gateway... Some seconds later, all the services recovered.

I agree with julian that there needs to be a better way to handle such situations. Prior to sending out notifications for hard service state changes, Icinga should check if there was a host recovery after the last service check, and if that is the case, it should require one more service check to change to hard state.

Regards

**Comment by Al2Klimov** [comment] 2019-03-11 14:34
@terra-nova What about v2.10.2?

**Comment by terra-nova** [comment] 2019-03-11 17:23
@Al2Klimov oh, 2.6.3... I can barely remember.

I believe we mostly worked around this issue by making host checks much more frequent (1m/30s frequencies, 3 retries) than service checks (5m/1m, 3 retries). As of now, at worst a few false alarm notifications are sent out, but not hundres like when we were young & naive...

Of course even better would be some intelligence in Icinga2 regarding this issue, but I guess it's kind of complicated and may have unwanted side effects, so maybe it's not worth bothering..

Anyway, I have no objections to closing this issue.

**Comment by Al2Klimov** [comment] 2019-03-12 09:03
v2.6.3 is old... old enough for being included into the current Debian stable. What about v2.10.3?

**Comment by lvasiliev** [comment] 2019-12-06 14:07
Hello!

We are migrating our monitoring system to Icinga2 from Icinga1 and we have the same problem with notification:
1. Host geons12 is DOWN. We receive notify about this. OK.
2. Host geons12 is UP. We receive notify about this. OK.
3. We receive notify about geons12/ping4 is CRITICAL. NOT OK.
4. We receive notify about  geons12/ping4 is OK. NOT OK.
5. We receive notify about geons12/NRPE is CRITICAL. NOT OK.
6. We receive notify about geons12/NRPE is OK. NOT OK.

```
hostalive check interval:
  check_interval = 4m
  retry_interval = 1m
  max_check_attempts = 10

ping4 check interval:
  check_interval = 5m
  retry_interval = 2m
  max_check_attempts = 5

services check interval:
  check_interval = 5m
  retry_interval = 2m
  max_check_attempts = 5

dependencies:

apply Dependency "ping4-soft_states" to Host {
  child_service_name = "ping4"

  ignore_soft_states = false
  assign where get_service(host.name, "ping4")
}

apply Dependency "disable-ALL-network-notify" to Service {
  parent_service_name = "ping4"

  ignore_soft_states = false
  assign where get_service(host.name, "ping4")
  ignore where service.name == "ping4"
}
```

Logs:

```
[2019-12-06 16:23:45 +0300] information/Checkable: Checkable 'geons12' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2019-12-06 16:23:45 +0300] information/Notification: Sending 'Problem' notification 'geons12!mail-host-extadm' for user 'vasilyev_l-mail'
[2019-12-06 16:23:45 +0300] information/Notification: Completed sending 'Problem' notification 'geons12!mail-host-extadm' for checkable 'geons12' and user 'vasilyev_l-mail' using command 'mail-host-notification-extadm'.

[2019-12-06 16:31:38 +0300] information/Checkable: Checkable 'geons12' has 1 notification(s). Checking filters for type 'Recovery', sends will be logged.
[2019-12-06 16:31:38 +0300] information/Notification: Sending 'Recovery' notification 'geons12!mail-host-extadm' for user 'vasilyev_l-mail'
[2019-12-06 16:31:38 +0300] information/Notification: Completed sending 'Recovery' notification 'geons12!mail-host-extadm' for checkable 'geons12' and user 'vasilyev_l-mail' using command 'mail-host-notification-extadm'.

[2019-12-06 16:31:53 +0300] information/Checkable: Checkable 'geons12!ping4' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2019-12-06 16:31:53 +0300] information/Notification: Sending 'Problem' notification 'geons12!ping4!mail-service-extadm' for user 'vasilyev_l-mail'
[2019-12-06 16:31:53 +0300] information/Notification: Completed sending 'Problem' notification 'geons12!ping4!mail-service-extadm' for checkable 'geons12!ping4' and user 'vasilyev_l-mail' using command 'mail-service-notification-extadm'.

[2019-12-06 16:31:54 +0300] information/Checkable: Checkable 'geons12!ping4' has 1 notification(s). Checking filters for type 'Recovery', sends will be logged.
[2019-12-06 16:31:54 +0300] information/Notification: Sending 'Recovery' notification 'geons12!ping4!mail-service-extadm' for user 'vasilyev_l-mail'
[2019-12-06 16:31:54 +0300] information/Notification: Completed sending 'Recovery' notification 'geons12!ping4!mail-service-extadm' for checkable 'geons12!ping4' and user 'vasilyev_l-mail' using command 'mail-service-notification-extadm'.

[2019-12-06 16:31:56 +0300] information/Checkable: Checkable 'geons12!NRPE' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2019-12-06 16:32:23 +0300] information/Checkable: Checkable 'geons12!ext_GEODNS' has 1 notification(s). Checking filters for type 'Recovery', sends will be logged.
[2019-12-06 16:32:34 +0300] information/Checkable: Checkable 'geons12!SSH' has 1 notification(s). Checking filters for type 'Recovery', sends will be logged.
[2019-12-06 16:34:23 +0300] information/Checkable: Checkable 'geons12!NRPE' has 1 notification(s). Checking filters for type 'Recovery', sends will be logged.
```
Old format logs:
```
[Fri Dec  6 16:22:42 2019] HOST ALERT: geons12;DOWN;SOFT;9;CRITICAL - Host Unreachable (geons12.example.com)
[Fri Dec  6 16:23:45 2019] HOST ALERT: geons12;DOWN;HARD;1;CRITICAL - Host Unreachable (geons12.example.com)
[Fri Dec  6 16:23:45 2019] HOST NOTIFICATION: vasilyev_l-mail;geons12;DOWN (DOWN);mail-host-notification-extadm;CRITICAL - Host Unreachable (geons12.example.com);
[Fri Dec  6 16:23:52 2019] SERVICE ALERT: geons12;NRPE;CRITICAL;HARD;1;connect to address XX.XX.XX.XX port 5666: No route to host
[Fri Dec  6 16:31:38 2019] HOST ALERT: geons12;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 0.69 ms
[Fri Dec  6 16:31:38 2019] HOST NOTIFICATION: vasilyev_l-mail;geons12;RECOVERY (UP);mail-host-notification-extadm;PING OK - Packet loss = 0%, RTA = 0.69 ms;
[Fri Dec  6 16:31:53 2019] SERVICE NOTIFICATION: vasilyev_l-mail;geons12;ping4;CRITICAL;mail-service-notification-extadm;CRITICAL - Host Unreachable (geons12.example.com);
[Fri Dec  6 16:31:54 2019] SERVICE ALERT: geons12;ping4;OK;HARD;1;PING OK - Packet loss = 0%, RTA = 0.49 ms
[Fri Dec  6 16:31:54 2019] SERVICE NOTIFICATION: vasilyev_l-mail;geons12;ping4;RECOVERY;mail-service-notification-extadm;PING OK - Packet loss = 0%, RTA = 0.49 ms;
[Fri Dec  6 16:31:56 2019] SERVICE NOTIFICATION: vasilyev_l-mail;geons12;NRPE;CRITICAL;mail-service-notification-extadm;CHECK_NRPE STATE CRITICAL: Socket timeout after 50 seconds.;
[Fri Dec  6 16:32:23 2019] SERVICE ALERT: geons12;ext_GEODNS;OK;HARD;1;DNS OK - 0.064 seconds response time ( skipped )
[Fri Dec  6 16:32:34 2019] SERVICE ALERT: geons12;SSH;OK;HARD;1;SSH OK - OpenSSH_7.5 * (protocol 2.0) 
[Fri Dec  6 16:34:23 2019] SERVICE ALERT: geons12;NRPE;OK;HARD;1;NRPE v3.2.1
[Fri Dec  6 16:34:23 2019] SERVICE NOTIFICATION: vasilyev_l-mail;geons12;NRPE;RECOVERY;mail-service-notification-extadm;NRPE v3.2.1;

```

**Comment by FieldofClay** [comment] 2019-12-19 05:41
I'm also having this issue. I feel that anything suggested so far just hides it (changing frequency of checks etc.) rather than properly resolving it.

I think this could be resolved if the there was some logic that if the host/service has recently had it's notifications disabled, don't notify until X time period has past. It could use the first notification delay field (begin), rather than creating a new field.

**Comment by lvasiliev** [comment] 2019-12-19 11:54
> I'm also having this issue. I feel that anything suggested so far just hides it (changing frequency of checks etc.) rather than properly resolving it.
> 
> I think this could be resolved if the there was some logic that if the host/service has recently had it's notifications disabled, don't notify until X time period has past. It could use the first notification delay field (begin), rather than creating a new field.

I think that the main reason is that a notification is sent before check this host/service. Setting time intervals do not solve this problem. In Icinga1 when a service exited from dependency then notification to be sent only after host/service was checked with fail result after retry interval.

**Comment by htriem** [comment] 2020-01-23 11:49
In Icinga 1.x, a so-called "on-demand hostcheck" existed, which blocked the service execution up until the host check result was recieved. This worked for a single standalone instance and syncronous check execution. 

With Icinga 2, the host object is not necessarily checked by the same endpoint where the service object would be checked. This is due to the fact that object execution is balanced between endpoints in an HA-enabled zone. Furthermore, all checks are executed asyncronously and no waiting mechanism exists. 

In order to cope with the described problem suggested workarounds from the community channels and customers are to set the host check interval lower than the service check interval. For example: host check interval = 30s; service check interval = 1m.

We believe that there is no sane way to change the current implementation and design from our experience in the past years. Therefore please use the suggested solution.
Best wishes,
Henrik

**Closed by htriem** 2020-01-23 11:49 UTC
Labels: area/notifications, bug

**Comment by angadm** [comment] 2020-01-24 09:12
We also have the same problem and I tried to investigate it. From my observation these unnecessary notifications are reminder notifications, i.e. they are sent by notification component running on timer.

I think the problem is with this line in notificationcomponent.cpp:
		bool reachable = checkable->IsReachable(DependencyNotification);

It computes the current reachability state instead of getting the last_reachable attribute, which was computed when the check was done. So, you end up with a check status from the past and the current reachability state, which don't belong to each other. The past check status should be judged by the past reachability state.

I might be wrong, but it would be good if you looked into it. In case this is true the fix should be very simple.

**Comment by lvasiliev** [comment] 2020-01-24 13:08
We also have a different configuration with Service-to-Service dependency.

For example all nrpe services dependent from NRPE daemon:

apply Dependency "disable-ALL-nrpe-notify" to Service {
  parent_service_name = "NRPE"
  disable_checks = false
  ignore_soft_states = false
  assign where get_service(host.name, "NRPE") && match("nrpe-*", service.check_command)
}

nrpe check revokecerts with long period:

apply Service "revokecerts" {
  import "service-generic"

  check_command         = "nrpe-base"
  vars.nrpe_command     = "check_revokecerts"

  check_interval        = 30m
  retry_interval        = 15m
  max_check_attempts    = 4 

  assign where "relay" in host.vars.roles 
}

Time interval for parent_service_name NRPE:
check_interval = 5m
retry_interval = 2m
max_check_attempts = 5

When NRPE in critical state from 1h and above also revokecerts state is critical/unknown too (disable_checks=false). When the NRPE goes to OK state we have notification about problem from revokecerts service.
