### ISSUE TITLE
[dev.icinga.com #12579] Warning/Critical thresholds on the IDO check

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4591] opened 2016-08-28 15:14 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12579

**Created by lewiseason on 2016-08-28 15:14:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-28 15:14:27 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

I'd like to be able to be alerted when aspects of my IDO instance go out of regular values - specifically, I want to know if there are many pending queries, or if the backend can't keep up.

At the moment, I can either write a check that interrogates the API, or I can examine the log file and generate alerts based on the IDO statistics line that gets periodically written.

It'd be neat if we could specify warning/critical at least for \`pending\_queries\` if nothing else, since this is already being checked once by icinga2, instead of having to check it again, for example, here is a modified version of my current check command:

    apply Service "IDO" {
            check_command = "ido"

            vars.ido_type = "IdoMysqlConnection"
            vars.ido_name = "ido-mysql"

            vars.pending_queries_warn = 100
            vars.pending_queries_crit = 1000

            assign where "monitoring" in host.groups
    }

It might also be nice if the check could output the estimated clear time in the same way as the info message does.

**Comment by dnsmichi** [comment] 2017-08-17 18:35
That's a duplicate of #3924 actually which needs re-evaluation.

**Closed by dnsmichi** 2017-08-17 18:35 UTC
Labels: DB IDO, enhancement
