### ISSUE TITLE
API listener does not support IPv6 out-of-the-box

### ISSUE THREAD

**Issue by dracenmarx** [Icinga/icinga2#5772] opened 2017-11-17 07:43 UTC
After installing icinga2 out-of-the-box on a Debian 9 system, the ApiListener won't listen to IPv6 on port 5665.
I have to explicitly add   bind_host = "::"  to the configuration of the ApiListener.

## Expected behavior
Program should support IPv6 out of the box.

## Curren behavior
Modifications to the configuration has to be done to make IPv6 work.

## Possible solution
Add bind_host = "::" to the default configuration.

## Your Environment
Linux ... 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

**Comment by dnsmichi** [comment] 2017-11-17 07:47
Duplicate of #3249

**Closed by dnsmichi** 2017-11-17 07:47 UTC
