### ISSUE TITLE
Process-check-result bulk API request

### ISSUE THREAD

**Issue by mcodato** [Icinga/icinga2#8716] opened 2021-04-14 13:20 UTC
## Is your feature request related to a problem? Please describe.

We rely heavily on passive checks sent via the `/v1/actions/process-check-result` API endpoint.
In big environments, this amounts to hundreds of requests in one second which means hundreds of open connections.

## Describe the solution you'd like

We would like to reduce resource usage by executing only one request with a bulk of process check results.

## Describe alternatives you've considered

We briefly discussed with @lippserd  about a possible stream of passive check results.

**Comment by julianbrost** [comment] 2021-04-14 15:11
This should actually be fairly easy to do since the individual actions are already implemented to operate on individual objects and the filters can already return multiple objects. So this would only need a new mechanism to pass a separate set of parameters for each object in `ActionsHandler::HandleRequest()`.

**Comment by julianbrost** [comment] 2021-06-01 07:33
This feature request already came up in the past (#3553) and there is a draft PR (#7875), but that seems to be stalled and nowhere near complete.

**Comment by Al2Klimov** [comment] 2023-11-17 11:18
Duplicate of #3353

**Closed** 2023-11-17 11:18 UTC
Labels: enhancement, area/api
