### ISSUE TITLE
Can't compile with CMake>=3.15 and Boost>=1.70.0

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#7566] opened 2019-10-08 14:42 UTC
Icinga 2 (tested both `v2.11.0` and master @ `06296175e8044635a76c794dfdd2b5f369de2cb2`) fails to compile on Arch Linux using CMake 3.15.4-1 and Boost 1.71.0-2.

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1. `git clone https://github.com/Icinga/icinga2.git`
2. `mkdir icinga2/build && cd icinga2/build`
3. `cmake ..`

CMake fails with the error
```
CMake Error at third-party/cmake/BoostTestTargets.cmake:56 (message):
  NOTE: boost::test-based targets and tests cannot be added: boost >= 1.34.0
  required but not found.  (found: '1.71.0' want >=103400) You may disable
  BUILD_TESTING to continue without the tests.
Call Stack (most recent call first):
  test/CMakeLists.txt:3 (include)
```

## Cause

This happens due to changed behavior of the `Boost_VERSION` variable with the versions mentioned in the title, changing its value from `107100` to `"1.71.0"`:
* https://cmake.org/cmake/help/v3.15/module/FindBoost.html
* https://cmake.org/cmake/help/git-stage/policy/CMP0093.html.

## Fix/Workaround

A possible fix for this would be replacing `${Boost_VERSION}` with `${Boost_VERSION_MACRO}` in `third-party/cmake/BoostTestTargets.cmake`, however I don't know if that's the best solution considering that the code is in `third-party/` and I don't know how this would affect compatibility with older versions. Alternatively, the `CMP0093` policy could be set in CMake. Possibly the version check there could be omitted altogether as  `CMakeLists.txt` already requires Boost>=1.66.0 anyways.

## Your Environment

* Version used (`icinga2 --version`): 2.11.0 and master
* Operating System and version: Arch Linux latest

**Comment by dnsmichi** [comment] 2019-10-08 15:52
The RPM packages (and others as well) use a workaround with specifying the CMake variables. This overrules the cmake detection since we as packagers already know what we're doing in this regard.

https://git.icinga.com/packaging/rpm-icinga2/blob/master/icinga2.spec#L432

**Comment by julianbrost** [comment] 2019-10-08 21:53
I was indeed asking for the [AUR icinga2 PKGBUILD](https://aur.archlinux.org/packages/icinga2/) and fixed the build there using this workaround now.

But I think it should also be possible to compile without giving these flags, especially as the error message is quite confusing (`boost >= 1.34.0
  required` and `found: '1.71.0'`) if you don't know that this happens because the format of a version variable in CMake changed.

**Comment by dnsmichi** [comment] 2019-10-10 08:00
Those version variables caused us many headaches for years now, specifically with different CMake versions and also Boost itself. I'm fine with changing this. Still, I fear that things break. So for me this is a low priority task unless someone wants to work on a PR :)

**Comment by dnsmichi** [comment] 2019-10-13 13:14
I've seen this now myself after upgrading macOs to Catalina with latest CMake and Boost. 
https://gitlab.kitware.com/cmake/cmake/issues/18865

My workaround for the issue is to disable the CMake internals with detecting the correct Boost version, but use our own mechanism - `-DBoost_NO_BOOST_CMAKE=ON`.

**Comment by dnsmichi** [comment] 2019-10-14 07:45
In case someone takes the lead on fixing this - we still must support Boost 1.66 and likewise, the lowest CMake version available on older distributions (el6).

**Comment by dnsmichi** [comment] 2020-01-27 15:45
Fixed with the patch from @sebastic 👍

**Closed by dnsmichi** 2020-01-27 15:45 UTC
Labels: area/setup
