### ISSUE TITLE
[dev.icinga.com #12326] Automatic restarts orphans packages in staging

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4441] opened 2016-08-08 09:42 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12326

**Created by jflach on 2016-08-08 09:42:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-08 09:42:01 +00:00 (in Redmine)_

    Icinga Version: 2.5.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Here (https://monitoring-portal.org/index.php?thread/36987-host-addition-via-packages-and-service-creation-calls-via-api-slowing-down-icing) someone ran into the following scenario:

When sending multiple config packages and the first triggers a restart, the rest seems to get get stuck in a limbo during validation/processing.

**Comment by dnsmichi** [comment] 2017-02-07 17:45
Probably related to #4797.

**Comment by dnsmichi** [comment] 2017-09-26 11:37
Should be solved with #5620, merely a duplicate of #3668.

**Closed by dnsmichi** 2017-09-26 11:37 UTC
Labels: API, bug
