### ISSUE TITLE
Error in Icinga2 Documentation

### ISSUE THREAD

**Issue by Cornitus** [Icinga/icinga2#9839] opened 2023-07-27 11:09 UTC
Debian: 11.7

The "systemctl enable --now icingadb-redis" command in the documentation: https://icinga.com/docs/icinga-2/latest/doc/02-installation/01-Debian/ is incorrect. The correct command is: "systemctl enable --now icingadb-redis-server".

**Comment by Al2Klimov** [comment] 2023-08-29 14:51
Duplicate of #9766

**Closed** 2023-08-29 14:52 UTC
