### ISSUE TITLE
Reschedule checks before downtime ends

### ISSUE THREAD

**Issue by teclogi** [Icinga/icinga2#6676] opened 2018-10-12 10:21 UTC
It would be helpful in some situations to run all checks again before the end of a downtime.

FOR EXAMPLE:
A host has a downtime of 1h (03:00 - 04:00) for updates.
A service is only checked every 4h and changes to warning status during the downtime.
After the server is finished with the updates, the service is available again.
Icinga checks this service again in 4h and generates a notification after the end of the downtime.

```
apply ScheduledDowntime "downtime test" to Service {

    author = "Infrastruktur"
    comment = "Test Downtime (TACK)"

    fixed = true

    ranges = {
        friday = "11:45-11:50"
    }

    assign where ( match("server1", host.name) && match("spooler", service.name))
}
```

```
object Endpoint "server1" {
}

object Zone "server1" {
    endpoints = [ "server1" ]
    parent = "GER"
}

object Host "server1" {
    import "generic-host"

    address = "192.168.0.41"
}
```

```
apply Service "spooler" {
    import "generic-service"

    check_command = "service-windows"
	
    check_interval = 4h
    retry_interval = 1m

    assign where match ("server1", host.name)
}

```

## Expected Behavior

The service should be checked again before the end of the downtime.

## Current Behavior

Currently the service is only checked again in the specified interval (after the end of the downtime) and thus generates a notification after the downtime ends.

## Possible Solution

Reschedule checks before downtime ends.

## Steps to Reproduce (for bugs)

1. Set the check_interval to longer than the Downtime duration
2.  Schedule Downtime and wait for it to start
3. Change status of service to a not OK hard state (stop service on the host and reschedule the check)
4. start the service on the host again
5. Wait for the downtime to end.

## Context

Reduction of false positive notifications.

## Your Environment

* Version used (`icinga2 --version`): version: r2.9.1-1
* Operating System and version: Debian 9
* Config validation (`icinga2 daemon -C`): is ok

**Comment by dnsmichi** [comment] 2018-10-12 11:28
Imho checks shouldn't be rescheduled outside of the retry or check interval, as this leaves to strange historical entries, as seen with the parent dependencies fixed in 2.10.

One thing I could think of is to delay/adopt the next notification timestamp during a downtime, towards end + short offset, and let the reminder notification kick in, when this object is still !OK. Is that what you're looking for?

**Comment by teclogi** [comment] 2018-10-17 06:38
Would this also work with a notification interval = 0?
Would this also work in my scenario, if the new check takes place 3 hours after the end of the downtime?

Maybe only those checks that have changed to !OK status during downtime should be re-scheduled before the end of the downtime?
Sorry, but I'm not familiar with the problem you mentioned.

Is another downtime option for that workable? (defaults to false)

**Comment by dnsmichi** [comment] 2018-10-17 07:06
Delaying the notification in a downtime window should include interval=0 too, yes.

In terms of the check interval with +3h, this won't work since the state won't be changed if needed. I do see your point here, still this shouldn't drop down below the `retry_interval`. The problem I am describing is best to be understood with #6629 which would flood check execution and out-of-band check execution not following the typical configuration interval settings.

A config option is a no-no, as this makes things complicated and introduces 2 ways of doing things instead of one.

**Comment by teclogi** [comment] 2018-10-17 07:18
Ok, thank you for the information.
Is there a way (configuration) to change the interval of a check when in downtime?

**Comment by teclogi** [comment] 2018-10-17 08:46
ok, Thank you for the response!

**Comment by mjbrooks** [comment] 2018-10-23 18:16
A possible solution to the issue is to merely flag the !OK state as tainted by a downtime (or pick your own word for it) if the !OK occurred during a downtime. Then, if the previous !OK state is tainted, don't trigger a notification for that particular recovery event. That would prevent false recoveries from being made when the previous state occurred during a downtime when the checks in question were probably expected to not be OK at some point.

We can call it the Vegas boolean, because just like how "what happens in Vegas stays in Vegas", what happens in downtime should stay in downtime. :D

It seems like a simple and elegant solution to me, but I'm curious what you think of the idea @dnsmichi

**Comment by lippserd** [comment] 2019-02-06 14:29
Since version 2.10. we only send recovery notifications if a problem notification was sent before. This should fix your problem.

**Closed by lippserd** 2019-02-06 14:29 UTC
Labels: Notifications, enhancement
