### ISSUE TITLE
icinga does not start after Update to 2.10

### ISSUE THREAD

**Issue by fscaptain** [Icinga/icinga2#6677] opened 2018-10-12 13:41 UTC
Mainlog Output:

```[2018-10-12 15:18:53 +0200] information/FileLogger: 'main-log' started.
[2018-10-12 15:18:53 +0200] information/ApiListener: 'api' started.
[2018-10-12 15:18:53 +0200] information/ApiListener: Started new listener on '[::]:5665'
[2018-10-12 15:18:53 +0200] information/CheckerComponent: 'checker' started.
[2018-10-12 15:18:53 +0200] information/ApiListener: Reconnecting to endpoint 'masterserver' via host 'xxx.xxx.xxx.xxx' and port '5665'
[2018-10-12 15:18:53 +0200] information/ConfigItem: Activated all objects.
[2018-10-12 15:18:53 +0200] critical/Application: Could not open PID file '/icinga2.pid'.
[2018-10-12 15:18:53 +0200] critical/Application: Cannot update PID file '/icinga2.pid'. Aborting.```

## Your Environment
Fresh Installation

```c:\Program Files\ICINGA2\sbin>icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.10.0)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Windows
  Platform version: 8.1 or greater (Server)
  Kernel: Windows
  Kernel version: 6.2
  Architecture: x86_64

Build information:
  Compiler: MSVC 19.0.24215.1
  Build host: ICINGA-BUILD-WI

Application information:

General paths:
  Config directory: C:\ProgramData\icinga2\etc\icinga2
  Data directory: C:\ProgramData\icinga2\var\lib\icinga2
  Log directory: C:\ProgramData\icinga2\var\log\icinga2
  Cache directory: C:\ProgramData\icinga2\var\cache\icinga2
  Spool directory: C:\ProgramData\icinga2\var\spool\icinga2
  Run directory:

Old paths (deprecated):
  Installation root: C:\Program Files\ICINGA2\
  Sysconf directory: C:\ProgramData\icinga2\etc
  Run directory (base): C:\ProgramData\icinga2\var\run
  Local state directory: C:\ProgramData\icinga2\var

Internal paths:
  Package data directory: C:\Program Files\ICINGA2\\share\icinga2
  State path: C:\ProgramData\icinga2\var\lib\icinga2/icinga2.state
  Modified attributes path: C:\ProgramData\icinga2\var\lib\icinga2/modified-attributes.conf
  Objects path: C:\ProgramData\icinga2\var\cache\icinga2/icinga2.debug
  Vars path: C:\ProgramData\icinga2\var\cache\icinga2/icinga2.vars
  PID path: /icinga2.pid

```
Problem verified on 3 Windows System. It's the same on fresh setups and updates.

**Comment by dnsmichi** [comment] 2018-10-12 14:17
9fbc40615a747b2d5236ed499b0eca9c6d24e2ef

```
        if (!binaryPrefix.IsEmpty() && !dataPrefix.IsEmpty()) {
-               Application::DeclarePrefixDir(binaryPrefix);
-               Application::DeclareSysconfDir(dataPrefix + "\\etc");
-               Application::DeclareRunDir(dataPrefix + "\\var\\run");
-               Application::DeclareLocalStateDir(dataPrefix + "\\var");
-               Application::DeclarePkgDataDir(binaryPrefix + "\\share\\icinga2");
-               Application::DeclareIncludeConfDir(binaryPrefix + "\\share\\icinga2\\include");
+               Application::DeclareConst("PrefixDir", binaryPrefix);
+               Application::DeclareConst("ProgramData", dataPrefix);
+
+               Application::DeclareConst("ConfigDir", dataPrefix + "\\etc\\icinga2");
+
+               Application::DeclareConst("DataDir", dataPrefix + "\\var\\lib\\icinga2");
+               Application::DeclareConst("LogDir", dataPrefix + "\\var\\log\\icinga2");
+               Application::DeclareConst("CacheDir", dataPrefix + "\\var\\cache\\icinga2");
+               Application::DeclareConst("SpoolDir", dataPrefix + "\\var\\spool\\icinga2");
+
+               // also see call to HandleLegacyDefines() later
+
+               // internal constants
+               Application::DeclareConst("PkgDataDir", binaryPrefix + "\\share\\icinga2");
+               Application::DeclareConst("IncludeConfDir", binaryPrefix + "\\share\\icinga2\\include");
```

drops RunDir, but doesn't re-add InitRunDir since we internally use that PID file and need to write it.

**Comment by dnsmichi** [comment] 2018-10-12 14:54
Unfortunately I am not able to reproduce this with v2.10.0 in my Windows 10 VM. A fix for the above maybe-regression is available in the snapshot packages which you can test. Please do so, as I am leaving for the weekend.

http://packages.icinga.com/windows/

```
  | Name | Last modified | Size
-- | -- | -- | --
  | Parent Directory |   | -
  | Icinga2-snapshot-x86.msi | 2018-10-12 16:48 | 27M
  | Icinga2-snapshot-x86_64.msi | 2018-10-12 16:46 | 33M

```

**Comment by JohnZ-H** [comment] 2018-10-12 15:22
Snapshot build fixes #6678 which appears to be a duplicate of this.

**Comment by fscaptain** [comment] 2018-10-15 06:03
Tried with snapshot build from 15.10. , but ist looks like the same. Same logoutput```[2018-10-15 07:55:08 +0200] information/ConfigItem: Activated all objects.
[2018-10-15 07:55:08 +0200] critical/Application: Could not open PID file '/icinga2.pid'.
[2018-10-15 07:55:08 +0200] critical/Application: Cannot update PID file '/icinga2.pid'. Aborting.```

**Comment by dnsmichi** [comment] 2018-10-15 07:42
https://build.icinga.com/view/Icinga%202/job/icinga2-windows-package/815/console

**Comment by dnsmichi** [comment] 2018-10-15 07:51
@fscaptain snapshot packages are available.

**Comment by fscaptain** [comment] 2018-10-15 08:33
Looks good. Services should be started an also restarted.

**Comment by fscaptain** [comment] 2018-10-15 08:48
Checked fresh installation an update, both works.

**Comment by dnsmichi** [comment] 2018-10-15 13:58
Thanks.

**Closed by dnsmichi** 2018-10-15 13:58 UTC
Labels: Packages, Windows, bug, needs-feedback
