### ISSUE TITLE
Unreliable sending of Graphite performance metrics for host and service checks

### ISSUE THREAD

**Issue by akqopensystems** [Icinga/icinga2#6261] opened 2018-04-25 13:37 UTC
## Expected Behavior
Every service and host check should reliably send performance metrics to Graphite, if Graphite feature is enabled.

## Current Behavior
Performance metrics are sent very unreliably which leads to missing values in the Graphite DB. At the moment we are checking ~5K hosts with ~35K checks in total. In most checks we have missing performance points.
In order to rule out other factors, we sniffed the network traffic during a host/service check and verified, that Icinga2 is not sending all performance metrics to Graphite.

## Steps to Reproduce (for bugs)
1. Define Host and Service checks
2. Enable Graphite feature for Icinga2
3. Snif Carbon communication between Icinga2 host and Graphite on Icinga2 host.
4.

## Context
Service check "Ping Host":
![grafik](https://user-images.githubusercontent.com/23358770/39248403-473fcecc-489c-11e8-92a5-0e3b9207ceee.png)
Host check "Ping" (same host):
![grafik](https://user-images.githubusercontent.com/23358770/39248432-6465d640-489c-11e8-95ae-29688f80d415.png)
The checks are running and produce no error.
Following is a tcpdump output during a successful host ping check, which produces no metrics:
````
[root@xxxmo03 ~]# tcpdump -n -i nm-team0 -A port 2013 |grep xxxplvap05
icinga2.xxxlvap05.services.ping.ping.metadata.state 0 1524657462
icinga2.xxxplvap05.services.ping.ping.metadata.current_attempt 1 1524657462
icinga2.xxxplvap05.services.ping.ping.metadata.max_check_attempts 3 1524657462
icinga2.xxxplvap05.services.ping.ping.metadata.state_type 1 1524657462
icinga2.xxxplvap05.services.ping.ping.metadata.reachable 1 1524657462
icinga2.xxxplvap05.services.ping.ping.metadata.downtime_depth 0 1524657462
icinga2.xxxplvap05.services.ping.ping.metadata.acknowledgement 0 1524657462
icinga2.xxxplvap05.services.ping.ping.metadata.latency 0.000250 1524657462
icinga2.xxxplvap05.services.ping.ping.metadata.execution_time 4.006928 1524657462
icinga2.xxxplvap05.services.ping.ping.perfdata.rta.value 0.000487 1524657462
icinga2.xxxplvap05.services.ping.ping.perfdata.rta.crit 0.200000 1524657462
icinga2.xxxplvap05.services.ping.ping.perfdata.rta.warn 0.100000 1524657462
icinga2.xxxplvap05.services.ping.ping.perfdata.pl.value 0 1524657462
icinga2.xxxplvap05.services.ping.ping.perfdata.pl.crit 15 1524657462
icinga2.xxxplvap05.services.ping.ping.perfdata.pl.warn 5 1524657462
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.metadata.state 0 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.metadata.current_attempt 1 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.metadata.max_check_attempts 3 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.metadata.state_type 1 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.metadata.reachable 1 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.metadata.downtime_depth 0 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.metadata.acknowledgement 0 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.metadata.latency 0.000384 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.metadata.execution_time 0.021678 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.perfdata._var.value 2008023040 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.perfdata._var.crit 3855613952 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.perfdata._var.warn 3426746368 1524657470
icinga2.xxxplvap05.services.available_volume_space_var.nrpe.perfdata._var.max 4284481536 1524657470
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.metadata.state 0 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.metadata.current_attempt 1 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.metadata.max_check_attempts 3 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.metadata.state_type 1 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.metadata.reachable 1 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.metadata.downtime_depth 0 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.metadata.acknowledgement 0 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.metadata.latency 0.000300 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.metadata.execution_time 0.019612 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.perfdata._boot.value 313524224 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.perfdata._boot.crit 479199232 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.perfdata._boot.warn 425721856 1524657493
icinga2.xxxplvap05.services.available_volume_space_boot.nrpe.perfdata._boot.max 532676608 1524657493
icinga2.xxxplvap05.services.nrpe_version.nrpe.metadata.state 0 1524657504
icinga2.xxxplvap05.services.nrpe_version.nrpe.metadata.current_attempt 1 1524657504
icinga2.xxxplvap05.services.nrpe_version.nrpe.metadata.max_check_attempts 3 1524657504
icinga2.xxxplvap05.services.nrpe_version.nrpe.metadata.state_type 1 1524657504
````

## Your Environment

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.3-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.17.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog elasticsearch gelf influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.8.3-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: xxxmo03.xxx.de
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 12 Zones.
information/ConfigItem: Instantiated 11 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 3 ApiUsers.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 67 UserGroups.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 2022 Notifications.
information/ConfigItem: Instantiated 231 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 5573 Hosts.
information/ConfigItem: Instantiated 600 HostGroups.
information/ConfigItem: Instantiated 172 Downtimes.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 109 Users.
information/ConfigItem: Instantiated 137 Comments.
information/ConfigItem: Instantiated 2 ServiceGroups.
information/ConfigItem: Instantiated 27570 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by Thomas-Gelf** [comment] 2018-04-25 22:27
The tcpdump shows the metrics sent to Graphite, combined with the related timestamp. Assuming that @akqopensystems lives in the location shown in his profile, this would mean that we had a ping (service) check at 13:57:42, then two disk checks and an NRPE version check at 13:58:24 - and no Host (ping) check. To me this looks like a good method to track down related issues. Carbon cannot process what's not on the wire.

However, I see a potential problem with the used `tcpdump` parameters. @akqopensystems, you should better add `-s 0`, just to be on the safe side. I don't know how efficiently the Graphite writer bundles metrics into packets, but in theory with the shown command you could miss data.

Also, your host graph shows no gap between 13:50 and 14:00. A debug log showing that the check really took place combined with the related tcpdump could make a good proof. Try to figure out whether the related check commands have really been executed according their schedule by Icinga, eventually the problem isn't in the Graphite Writer. Also, please try to grep the Icinga log for statistics related to queued/sent metrics for Graphite. In case a Grapher isn't able to keep up, Icinga might drop data after some time. If so, you should see a growing (worker) queue in your logs.

Cheers,
Thomas

**Comment by akqopensystems** [comment] 2018-04-27 13:58
We've switched from carbon-c-relay to carbon-relay-ng and for now this seems to fix the problem. We will watch the situation over the weekend and hope that we have a solution there. Unfortunately this problem doesn't show up in our test environment so it seems to be at least partly triggered by production loads.

**Comment by dnsmichi** [comment] 2018-04-30 09:26
```
[2018-04-26 15:08:36 +0200] critical/GraphiteWriter: Cannot write to TCP socket on host '127.0.0.1' port '2013'.
Context:
        (0) Processing check result for 'xxxxxxxx'
[2018-04-26 15:08:36 +0200] critical/GraphiteWriter: Exception during Graphite operation: Verify that your backend is operational!
```

isn't part of the debug log, that's logged with the `mainlog` feature too. If the remote side closes the connection on idle (which is somewhat insane for a metric receiver, carbon-cache isn't doing that AFAIK), you might want to tune the graphite feature a bit in terms of the flush intervals and items. 

Other than that, I don't see a bug in Icinga here. Consider using the community support channels next time. Closing for that very reason.

**Closed by dnsmichi** 2018-04-30 09:26 UTC
Labels: Graphite, needs-feedback
