### ISSUE TITLE
Timeperiod timeranges not saved correctly into database

### ISSUE THREAD

**Issue by Epytir** [Icinga/icinga2#5618] opened 2017-09-25 12:09 UTC
We have some Icinga2 Servers installed on some customer sites.
We got the problem, when we create new timeranges icinga2 inserts this timeranges into the database and then remove it in the same request. (myslq Dumps below)
Customer 1 Icinga2 Infos:

```
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.5 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 4.4.0-72-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.4
  Build host: lgw01-43
```
Customer 2 ICinga2 Infos:

```
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.5 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 4.4.0-96-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.2
  Build host: 02a0e862c14c
```

Icinga2 feature list 
customer 1 
```
Disabled features: compatlog debuglog gelf graphite icingastatus influxdb livestatus opentsdb statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification perfdata
```
Customer 2 
```
Disabled features: debuglog gelf graphite icingastatus influxdb livestatus opentsdb syslog
Enabled features: api checker command compatlog ido-mysql mainlog notification perfdata statusdata
```

icinga2 daemon -C
customer 1 
```
icinga2 daemon -C
information/cli: Icinga application loader (version: r2.6.3-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga-domäne.com
warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
warning/ApplyRule: Apply rule 'ssh' (in /etc/icinga2/conf.d/services.conf: 55:1-55:19) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 5 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 5 Endpoints.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 598 Notifications.
information/ConfigItem: Instantiated 219 CheckCommands.
information/ConfigItem: Instantiated 244 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 15 HostGroups.
information/ConfigItem: Instantiated 4 Comments.
information/ConfigItem: Instantiated 2 Dependencies.
information/ConfigItem: Instantiated 7 UserGroups.
information/ConfigItem: Instantiated 18 Users.
information/ConfigItem: Instantiated 658 Services.
information/ConfigItem: Instantiated 6 TimePeriods.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
Customer 2 
```
icinga2 daemon -C
information/cli: Icinga application loader (version: r2.7.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga.anderedomäne.com
warning/ApplyRule: Apply rule 'mail-service-24x7-CoreTemp' (in /etc/icinga2/conf.d/notifications.conf: 302:1-302:58) for type 'Notification' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 3 Endpoints.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 735 Notifications.
information/ConfigItem: Instantiated 254 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 271 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 16 HostGroups.
information/ConfigItem: Instantiated 1 EventCommand.
information/ConfigItem: Instantiated 33 Comments.
information/ConfigItem: Instantiated 100 Dependencies.
information/ConfigItem: Instantiated 2 UserGroups.
information/ConfigItem: Instantiated 13 TimePeriods.
information/ConfigItem: Instantiated 16 Users.
information/ConfigItem: Instantiated 1526 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CompatLogger.
information/ConfigItem: Instantiated 1 StatusDataWriter.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

I tried several different timeranges and only the new ones I add got this problem. The old konfigs are all active and running. The Icinga itself is working.
Here are 2 Konfigs that are not running. (one of them is a copy with a different name of a copy that has no problems...)

```
object TimePeriod "DontCheck_2_45-3_30" {
  import "legacy-timeperiod"

  display_name = "DontCheck_2_45-3_30"
  ranges = {
    "monday"    = "00:00-02:45,03:30-24:00"
    "tuesday"   = "00:00-02:45,03:30-24:00"
    "wednesday" = "00:00-02:45,03:30-24:00"
    "thursday"  = "00:00-02:45,03:30-24:00"
    "friday"    = "00:00-02:45,03:30-24:00"
    "saturday"  = "00:00-02:45,03:30-24:00"
    "sunday"    = "00:00-02:45,03:30-24:00"
  }
}
object TimePeriod "Icinga 2TEST 24x7 TimePeriod" {
  import "legacy-timeperiod"

  display_name = "Icinga 2TEST 24x7 TimePeriod"
  ranges = {
    "monday"    = "00:00-24:00"
    "tuesday"   = "00:00-24:00"
    "wednesday" = "00:00-24:00"
    "thursday"  = "00:00-24:00"
    "friday"    = "00:00-24:00"
    "saturday"  = "00:00-24:00"
    "sunday"    = "00:00-24:00"
  }
}
```

## Current Behavior

When I reload the Icinga2 Server I see the following in the mysql Dumps:
```
INSERT INTO icinga_timeperiod_timeranges (day, end_sec, instance_id, start_sec, timeperiod_id) VALUES ('0', '79200', 1, '79200', 17);
INSERT INTO icinga_timeperiod_timerange  (day, end_sec, instance_id, start_sec, timeperiod_id) VALUES ('4', '79200', 1, '79200', 17);
INSERT INTO icinga_timeperiod_timeranges (day, end_sec, instance_id, start_sec, timeperiod_id) VALUES ('2', '79200', 1, '79200', 17);
INSERT INTO icinga_timeperiod_timeranges (day, end_sec, instance_id, start_sec, timeperiod_id) VALUES ('3', '79200', 1, '79200', 17);
DELETE FROM icinga_timeperiod_timeranges WHERE timeperiod_id = 17;
INSERT INTO icinga_timeperiod_timeranges (day, end_sec, instance_id, start_sec, timeperiod_id) VALUES ('5', '79200', 1, '79200', 17);
INSERT INTO icinga_timeperiod_timeranges (day, end_sec, instance_id, start_sec, timeperiod_id) VALUES ('1', '79200', 1, '79200', 17);
INSERT INTO icinga_timeperiod_timeranges (day, end_sec, instance_id, start_sec, timeperiod_id) VALUES ('6', '79200', 1, '79200', 17);UPDATE icinga_objects SET is_active = 0 WHERE object_id = 4209;
UPDATE icinga_objects SET is_active = 1 WHERE object_id = 4210
```

Because of that the config in the database looks like this
```
select * from icinga_timeperiod_timeranges where timeperiod_id = 17;
+-------------------------+-------------+---------------+------+-----------+---------+
| timeperiod_timerange_id | instance_id | timeperiod_id | day  | start_sec | end_sec |
+-------------------------+-------------+---------------+------+-----------+---------+
|                    5818 |           1 |            17 |    1 |     79200 |   79200 |
|                    5817 |           1 |            17 |    5 |     79200 |   79200 |
|                    5819 |           1 |            17 |    6 |     79200 |   79200 |
+-------------------------+-------------+---------------+------+-----------+---------+
```

so there are 4 days missing.
We got this on both icinga2 servers. sometimes there are some more or less entrys in the database.

## Steps to Reproduce (for bugs)

1.  Add new timeperiod konfig 
2.  Reload or restart icinga2

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment] 2017-09-25 13:20
Thanks, this is a duplicate of #4659.

**Closed by dnsmichi** 2017-09-25 13:20 UTC
