### ISSUE TITLE
[dev.icinga.com #13505] Improve documentation on InfluxdbWriters behaviour in distributed monitoring scenario

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4856] opened 2016-12-09 16:28 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13505

**Created by alorenzi on 2016-12-09 16:28:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-09 16:28:14 +00:00 (in Redmine)_

    Icinga Version: version: r2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

I'm running icinga2 in (top-down configuration sync scenario):https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/distributed-monitoring#distributed-monitoring-top-down-config-sync)

-   if I configure InfluxDB on master, no data from zones has written in influxdb.
-   if i configure InfluxDB also on agents data written in InfluxDB.

Tested also (Top Down Command Endpoint scenario):https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/distributed-monitoring#distributed-monitoring-top-down-command-endpoint , no data sent to influxdb even if writer configured in master and agent.

see also issue [\#13503](https://dev.icinga.com/issues/13503)

**Comment by dnsmichi** [comment] 2017-02-07 18:11
I'm not sure what topic this issue is about?

**Comment by lesinigo** [comment] 2017-02-07 22:00
Since then we have solved some problems in our setup so please don't mind our actual example.

I'd now rephrase the issue like this: I suggest to clarify in the documentation that the InfluxDBWriter (and afaik the other writers like Graphite) will write out all data the passes through an Icinga systems (even if coming from child zones) and not just data about checks that get actually executed in the same zone where the writer is configured.

**Comment by Crunsher** [comment] 2017-02-08 08:22
Would you like to submit a patch then?

**Comment by dnsmichi** [comment] 2017-02-08 09:09
Hm, that is the case for **any** feature enabled in a parent zone. If you are planning to patch that please keep that in mind. Probably fits better in the distributed monitoring section explaining what happens with CheckResult events and their further processing.

**Comment by dnsmichi** [comment] 2017-10-10 07:27
I'm closing this as a partial duplicate of #4855.

**Closed by dnsmichi** 2017-10-10 07:27 UTC
Labels: Documentation, enhancement
