### ISSUE TITLE
API: Escape special and control characters in JSON strings

### ISSUE THREAD

**Issue by thozook** [Icinga/icinga2#8312] opened 2020-10-06 18:02 UTC
## Is your feature request related to a problem? Please describe.

As discussed in https://community.icinga.com/t/invalid-json-due-to-non-escaped-strings/5714/3, the JSON that is generated when querying the API can contain unescaped special and control characters that will cause the JSON object to violate the JSON standard(https://tools.ietf.org/html/rfc8259) and become invalid for anything expecting standard JSON.

## Describe the solution you'd like

The special and control characters in the JSON strings to be escaped before the JSON is sent out in response to an API call.

## Describe alternatives you've considered

I've tried to adjust the input code of what I'm working with to become more invalid JSON tolerant, but some items are hard to escape with an already complete JSON object. It would be better if the received JSON object was already meeting the JSON standard.

**Comment by Al2Klimov** [comment] 2020-10-08 09:49
Hello @thozook and thank you for reporting!

What's your Icinga 2 version?

Best,
AK

**Comment by thozook** [comment] 2020-10-08 15:02
@Al2Klimov 
Icinga 2 version is 2.12.0-1

```
# icinga2 -V
icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.0-1)
```

**Comment by Al2Klimov** [comment] 2020-10-12 10:40
## Task

Reproduce https://community.icinga.com/t/invalid-json-due-to-non-escaped-strings/5714/3 on Windows.

**Comment by Al2Klimov** [comment] 2020-10-29 16:03
First of all I've just asked _to reproduce it_. Please do so _the next time_.

Have you reproduced it? How?

**Comment by Yonas-net** [comment] 2020-10-29 16:43
I actually thought that I should solve the problem and reproduce it but anyway, I have reproduced it as follows.
Install and build ``check_by_powershell`` [here](https://github.com/Icinga/check_by_powershell).

And just copy the CheckCommand template called ``powershell`` from ``check_by_powershell`` repo. You can find it in the ``icinga2`` directory in the ``command.conf`` file.

And additionally you have to define a CheckCommand which should be executed by check_by_powershell on the Windows server.
```
object CheckCommand "windows-icmp-check" {
    import "plugin-check-command"

    command = [
        "Invoke-IcingaCheckICMP"
    ]

    arguments = {
        "-Hostname" = {
            value = "$icmp_hostname$"
        }
        "-Warning" = {
            value = "$icmp_warning$"
        }
        "-Critical" = {
            value = "$icmp_critical$"
        }
        "-CriticalPl" = {
            value = "$icmp_critical_ipl$"
        }
        "-PacketCount" = {
            value = "$icmp_packet_count$"
        }
        "-PacketSize" = {
            value = "$icmp_packet_size$"
        }
        "-Verbosity" = {
            value = "$icmp_verbosity$"
        }
        "-NoPerfData" = {
            set_if = "$icmp_perfdata$"
        }
    }

    vars.icmp_warning = "100"
    vars.icmp_critical = "200"
    vars.icmp_packet_count = "5"
    vars.icmp_packet_size = "64"
}
```

And of course don't forget to define host and service.
```
object Host "windowshost" {
  import "generic-host"

  address = "10.27.1.26"
  vars.powershell_port = 5985
  vars.powershell_user = "Administrator"
  vars.powershell_password = "icinga0815!"
  vars.powershell_no_tls = true
  #vars.powershell_insecure = true

  vars.server_type = "windows"
}

template Service "powershell-template-service" {
   import "generic-service"

   vars.original_check_command = check_command
   check_command = "powershell"

   vars.by_powershell_command = {{ get_check_command(service.vars.original_check_command).command }}
   vars.by_powershell_arguments = {{ get_check_command(service.vars.original_check_command).arguments }}
}

apply Service "windows-icmp" {
    check_command = "windows-icmp-check"

    import "powershell-template-service"

    vars.icmp_hostname = "google.com"
    vars.icmp_verbosity = "2"

    assign where host.vars.server_type == "windows"
}
```

After that you only have to enable icinga2 api feature and start icinga2 and get the CheckResult with Stream Event Response. ``curl -k -s -v -X POST -u root:icinga -H 'Accept: application/json' https://localhost:5665/v1/events\?queue\=test\&types\=CheckResult``

Wait until Icinga2 executes ``check_by_powershell`` for our windows host then validate [here](https://jsonformatter.curiousconcept.com) the json output and our checkResult is invalid.

**Comment by Al2Klimov** [comment] 2020-10-29 16:45
Please share a such curl output.

**Comment by Al2Klimov** [comment] 2020-10-29 16:49
If I paste this on the given website and click _process_, it says "valid".

**Comment by Yonas-net** [comment] 2020-10-29 17:30
Once the curl output was invalid but after several attempts I cannot reproduce it again. And the curl output that was invalid I no longer have it.

```
{
   "check_result":{
      "active":true,
      "check_source":"yonass-mbp.int",
      "command":[
         "/Users/yhabteab/Workspace/icinga2/prefix/lib/nagios/plugins/check_by_powershell",
         "--icingacmd",
         "Invoke-IcingaCheckICMP -Hostname google.com -Verbosity 2",
         "--no-tls",
         "true",
         "--password",
         "secret!",
         "--user",
         "icinga",
         "-H",
         "windowshost",
         "-p",
         "5985"
      ],
      "execution_end":1603992238.040059,
      "execution_start":1603992233.249119,
      "exit_status":0.0,
      "output":"[OK] Check package \"ICMP Check for google.com\" (Match All)\n\\_ [OK] ICMP request to 172.217.23.110 with 64 bytes: 4ms\n\\_ [OK] ICMP request to 172.217.23.110 with 64 bytes: 4ms\n\\_ [OK] ICMP request to 172.217.23.110 with 64 bytes: 4ms\n\\_ [OK] ICMP request to 172.217.23.110 with 64 bytes: 4ms\n\\_ [OK] ICMP request to 172.217.23.110 with 64 bytes: 4ms\n\\_ [OK] Packet Loss: 0%\n",
      "performance_data":[
         "packet_loss=0%;20;50;0;100",
         "minimum_response_time=4ms;;",
         "maximum_response_time=4ms;;",
         "packet_count=5c;;",
         "average_response_time=4ms;100;200"
      ],
      "schedule_end":1603992238.040406,
      "schedule_start":1603992233.241183,
      "state":0.0,
      "ttl":0.0,
      "type":"CheckResult",
      "vars_after":{
         "attempt":1.0,
         "reachable":false,
         "state":0.0,
         "state_type":1.0
      },
      "vars_before":{
         "attempt":1.0,
         "reachable":true,
         "state":0.0,
         "state_type":1.0
      }
   },
   "downtime_depth":0.0,
   "host":"windowshost",
   "service":"windows-icmp",
   "timestamp":1603992238.042634,
   "type":"CheckResult"
}
```

**Comment by thozook** [comment] 2020-10-29 21:24
@Yonas-net Are you using an Icinga build with the code from your pull request? That might be interfering with trying to get the invalid output.

**Comment by Al2Klimov** [comment] 2020-10-30 09:26
@Yonas-net Try stopping Icinga, removing /var/lib/icinga2/icinga2.state and starting Icinga again.

**Comment by Al2Klimov** [comment] 2020-10-30 09:43
If you still won't be able to reproduce the problem, please explain the problem step-by-step and the reason for your way #8421 of solving it.

**Comment by Yonas-net** [comment] 2020-11-06 08:42
Hallo @thozook , unfortunately I still can't reproduce the bug. Can you still reproduce it and if so, can you explain the steps you have taken please?.

**Comment by Al2Klimov** [comment] 2021-09-07 16:01
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.

**Closed by Al2Klimov** 2021-09-07 16:01 UTC
Labels: needs feedback
