### ISSUE TITLE
Icinga object  rebuild, database tables "icinga_objects" is_active value not update

### ISSUE THREAD

**Issue by silenceJI** [Icinga/icinga2#5386] opened 2017-06-29 02:59 UTC
## Current Behavior
After rebuilding the object, This object has been activated inside ICINGA, but database "icinga_objects" tables   "is_active" value not update to "1",  WEB side does not display this object;

## Possible Solution
unable to find

## Steps to Reproduce (for bugs)

1. add object: 
```
curl -k -s -u root:593ca8254532d301 -H 'Accept: application/json' -X PUT 'https://10.90.0.82:5665/v1/objects/hosts/l-yshow.fe.cn1' -d '{ "templates": [ "generic-host" ], "attrs": { "address": "l-yshow.fe.cn1", "check_command": "hostalive", "vars.os" : "Linux", "zone": "zone-cn2"}}'
```
2. Query the database: 
```
MariaDB [icinga]> select * from icinga_objects where name1 = "l-yshow.fe.cn1" ;
+-----------+-------------+---------------+----------------+-------+-----------+
| object_id | instance_id | objecttype_id | name1          | name2 | is_active |
+-----------+-------------+---------------+----------------+-------+-----------+
|       214 |           1 |             1 | l-yshow.fe.cn1 | NULL  |         1 |
+-----------+-------------+---------------+----------------+-------+-----------+
```
3. Delete object: 
```
curl -k -s -u root:593ca8254532d301 -H 'Accept: application/json' -X DELETE 'https://10.90.0.81:5665/v1/objects/hosts/l-yshow.fe.cn1?cascade=1'
```
4. Query the database: 
```
MariaDB [icinga]> select * from icinga_objects where name1 = "l-yshow.fe.cn1" ;
+-----------+-------------+---------------+----------------+-------+-----------+
| object_id | instance_id | objecttype_id | name1          | name2 | is_active |
+-----------+-------------+---------------+----------------+-------+-----------+
|       214 |           1 |             1 | l-yshow.fe.cn1 | NULL  |         0 |
+-----------+-------------+---------------+----------------+-------+-----------+
```
5. Repeat 1.:
```
curl -k -s -u root:593ca8254532d301 -H 'Accept: application/json' -X PUT 'https://10.90.0.82:5665/v1/objects/hosts/l-yshow.fe.cn1' -d '{ "templates": [ "generic-host" ], "attrs": { "address": "l-yshow.fe.cn1", "check_command": "hostalive", "vars.os" : "Linux", "zone": "zone-cn2"}}'
```
6. Query the database: 
```
MariaDB [icinga]> select * from icinga_objects where name1 = "l-yshow.fe.cn1" ;
+-----------+-------------+---------------+----------------+-------+-----------+
| object_id | instance_id | objecttype_id | name1          | name2 | is_active |
+-----------+-------------+---------------+----------------+-------+-----------+
|       214 |           1 |             1 | l-yshow.fe.cn1 | NULL  |         0 |
+-----------+-------------+---------------+----------------+-------+-----------+
```

## Your Environment

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: v2.6.3)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-327.36.3.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```
* Operating System and version:
```
CentOS Linux release 7.2.1511 (Core)
Kernel version: 3.10.0-327.36.3.el7.x86_64
```
* Enabled features (`icinga2 feature list`):
```
Disabled features: compatlog gelf graphite ido-pgsql influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command debuglog ido-mysql mainlog notification
```
* Icinga Web 2 version and modules (System - About):
```
Version
2.4.1
Git commit
d74124bd12f53d13b5a6ea5408e9783cc5190d1e
```
* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: v2.6.3)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: l-qicingam1.ops.cn2
warning/Zone: The Zone object 'zone-cn2' has more than two endpoints. Due to a known issue this type of configuration is strongly discouraged and may cause Icinga to use excessive amounts of CPU time.
warning/ApplyRule: Apply rule 'mail-notification' (in /etc/icinga2/zones.d/global-templates/notifications.conf: 10:1-10:49) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'ivr-notification' (in /etc/icinga2/zones.d/global-templates/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
information/ConfigItem: Instantiated 4 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 2 FileLoggers.
information/ConfigItem: Instantiated 6 Endpoints.
information/ConfigItem: Instantiated 3 Notifications.
information/ConfigItem: Instantiated 3 NotificationCommands.
information/ConfigItem: Instantiated 202 CheckCommands.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3 Hosts.
information/ConfigItem: Instantiated 4 Users.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 48 Dependencies.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 4 ServiceGroups.
information/ConfigItem: Instantiated 48 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
```
Endpoint:
Object 'l-qicingam1.ops.cn2' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 6:1-6:37
  * __name = "l-qicingam1.ops.cn2"
  * host = "10.90.0.81"
    % = modified in '/etc/icinga2/zones.conf', lines 7:2-7:20
  * log_duration = 300
    % = modified in '/etc/icinga2/zones.conf', lines 8:2-8:18
  * name = "l-qicingam1.ops.cn2"
  * package = "_etc"
  * port = "5665"
  * templates = [ "l-qicingam1.ops.cn2" ]
    % = modified in '/etc/icinga2/zones.conf', lines 6:1-6:37
  * type = "Endpoint"
  * zone = ""

Object 'l-qicingan2.ops.cn2' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 21:1-21:37
  * __name = "l-qicingan2.ops.cn2"
  * host = "10.90.0.84"
    % = modified in '/etc/icinga2/zones.conf', lines 22:2-22:20
  * log_duration = 300
    % = modified in '/etc/icinga2/zones.conf', lines 23:2-23:18
  * name = "l-qicingan2.ops.cn2"
  * package = "_etc"
  * port = "5665"
  * templates = [ "l-qicingan2.ops.cn2" ]
    % = modified in '/etc/icinga2/zones.conf', lines 21:1-21:37
  * type = "Endpoint"
  * zone = ""

Object 'l-cn0qicingan1.ops.cn2' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 26:1-26:40
  * __name = "l-cn0qicingan1.ops.cn2"
  * host = "10.90.0.85"
    % = modified in '/etc/icinga2/zones.conf', lines 27:2-27:20
  * log_duration = 300
    % = modified in '/etc/icinga2/zones.conf', lines 28:2-28:18
  * name = "l-cn0qicingan1.ops.cn2"
  * package = "_etc"
  * port = "5665"
  * templates = [ "l-cn0qicingan1.ops.cn2" ]
    % = modified in '/etc/icinga2/zones.conf', lines 26:1-26:40
  * type = "Endpoint"
  * zone = ""

Object 'l-cn0qicingan2.ops.cn2' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 31:1-31:40
  * __name = "l-cn0qicingan2.ops.cn2"
  * host = "10.90.0.86"
    % = modified in '/etc/icinga2/zones.conf', lines 32:2-32:20
  * log_duration = 300
    % = modified in '/etc/icinga2/zones.conf', lines 33:2-33:18
  * name = "l-cn0qicingan2.ops.cn2"
  * package = "_etc"
  * port = "5665"
  * templates = [ "l-cn0qicingan2.ops.cn2" ]
    % = modified in '/etc/icinga2/zones.conf', lines 31:1-31:40
  * type = "Endpoint"
  * zone = ""

Object 'l-qicingam2.ops.cn2' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 11:1-11:37
  * __name = "l-qicingam2.ops.cn2"
  * host = "10.90.0.82"
    % = modified in '/etc/icinga2/zones.conf', lines 12:2-12:20
  * log_duration = 300
    % = modified in '/etc/icinga2/zones.conf', lines 13:2-13:18
  * name = "l-qicingam2.ops.cn2"
  * package = "_etc"
  * port = "5665"
  * templates = [ "l-qicingam2.ops.cn2" ]
    % = modified in '/etc/icinga2/zones.conf', lines 11:1-11:37
  * type = "Endpoint"
  * zone = ""

Object 'l-qicingan1.ops.cn2' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 16:1-16:37
  * __name = "l-qicingan1.ops.cn2"
  * host = "10.90.0.83"
    % = modified in '/etc/icinga2/zones.conf', lines 17:2-17:20
  * log_duration = 300
    % = modified in '/etc/icinga2/zones.conf', lines 18:2-18:18
  * name = "l-qicingan1.ops.cn2"
  * package = "_etc"
  * port = "5665"
  * templates = [ "l-qicingan1.ops.cn2" ]
    % = modified in '/etc/icinga2/zones.conf', lines 16:1-16:37
  * type = "Endpoint"
  * zone = ""
```
```
ZONE:
Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 46:1-46:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 47:9-47:21
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 46:1-46:30
  * type = "Zone"
  * zone = ""

Object 'master' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 36:1-36:20
  * __name = "master"
  * endpoints = [ "l-qicingam1.ops.cn2", "l-qicingam2.ops.cn2" ]
    % = modified in '/etc/icinga2/zones.conf', lines 37:2-37:61
  * global = false
  * name = "master"
  * package = "_etc"
  * parent = ""
  * templates = [ "master" ]
    % = modified in '/etc/icinga2/zones.conf', lines 36:1-36:20
  * type = "Zone"
  * zone = ""

Object 'zone-cn2' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 40:1-40:22
  * __name = "zone-cn2"
  * endpoints = [ "l-qicingan1.ops.cn2", "l-qicingan2.ops.cn2", "l-cn0qicingan1.ops.cn2", "l-cn0qicingan2.ops.cn2" ]
    % = modified in '/etc/icinga2/zones.conf', lines 41:2-41:113
  * global = false
  * name = "zone-cn2"
  * package = "_etc"
  * parent = "master"
    % = modified in '/etc/icinga2/zones.conf', lines 42:2-42:18
  * templates = [ "zone-cn2" ]
    % = modified in '/etc/icinga2/zones.conf', lines 40:1-40:22
  * type = "Zone"
  * zone = ""
```
```
Debug log:
[2017-06-29 10:54:38 +0800] notice/ApiListener: Received update for object: {"config":"object Host \"l-yshow.fe.cn1\" {\n\timport \"generic-host\"\n\n\taddress = \"l-yshow.fe.cn1\"\n\tcheck_command = \"hostalive\"\n\tvars[\"os\"] = \"Linux\"\n\tversion = 1498704878.054915\n\tzone = \"zone-cn2\"\n}\n","modified_attributes":{},"name":"l-yshow.fe.cn1","original_attributes":[],"type":"Host","version":1498704878.0549149513}
[2017-06-29 10:54:38 +0800] notice/ApiListener: Processing config update for object 'l-yshow.fe.cn1': Object version 1.49865e+09 is older than the received version 1.4987e+09.
[2017-06-29 10:54:38 +0800] debug/HostDbObject: host dependencies for 'l-yshow.fe.cn1'
[2017-06-29 10:54:38 +0800] debug/HostDbObject: host contacts: l-yshow.fe.cn1
[2017-06-29 10:54:38 +0800] debug/HostDbObject: host contactgroups: l-yshow.fe.cn1
[2017-06-29 10:54:38 +0800] debug/IdoMysqlConnection: Query: UPDATE icinga_hosts SET action_url = '',  active_checks_enabled = '1',  address = 'l-yshow.fe.cn1',  address6 = '',  alias = 'l-yshow.fe.cn1',  check_command_args = '',  check_command_object_id = 35,  check_interval = '5',  config_hash = '8ba9deb80bff4b2ce419e96edc4f014cd44f83c3a2d07ec28f42d2bd02384ea8',  config_type = '1',  display_name = 'l-yshow.fe.cn1',  event_handler_enabled = '1',  failure_prediction_enabled = '0',  flap_detection_enabled = '0',  freshness_checks_enabled = '1',  freshness_threshold = '300',  high_flap_threshold = '30',  host_object_id = 214,  icon_image = '',  icon_image_alt = '',  instance_id = 1,  low_flap_threshold = '30',  max_check_attempts = '3',  notes = '',  notes_url = '',  notification_interval = '30',  notifications_enabled = '1',  notify_on_down = '0',  notify_on_downtime = '1',  notify_on_flapping = '1',  notify_on_recovery = '1',  notify_on_unreachable = '0',  obsess_over_host = '0',  passive_checks_enabled = '1',  process_performance_data = '1',  retain_nonstatus_information = '1',  retain_status_information = '1',  retry_interval = '1' WHERE host_object_id = 214
[2017-06-29 10:54:50 +0800] notice/ApiListener: Received update for object: {"name":"l-yshow.fe.cn1","type":"Host","version":1498704878.0549149513}
[2017-06-29 10:55:19 +0800] debug/HttpRequest: line: GET /v1/objects/hosts/l-yshow.fe.cn1 HTTP/1.1, tokens: 3
[2017-06-29 10:55:19 +0800] information/HttpServerConnection: Request: GET /v1/objects/hosts/l-yshow.fe.cn1 (from [100.80.158.219]:52005, user: root)
[2017-06-29 10:55:24 +0800] notice/ApiListener: Received update for object: {"config":"object Host \"l-yshow.fe.cn1\" {\n\timport \"generic-host\"\n\n\taddress = \"l-yshow.fe.cn1\"\n\tcheck_command = \"hostalive\"\n\tvars[\"os\"] = \"Linux\"\n\tversion = 1498704924.431518\n\tzone = \"zone-cn2\"\n}\n","modified_attributes":{},"name":"l-yshow.fe.cn1","original_attributes":[],"type":"Host","version":1498704924.4315180779}
[2017-06-29 10:55:24 +0800] notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/_api/l-qicingam2.ops.cn2-1495008033-0/conf.d/hosts/l-yshow.fe.cn1.conf
[2017-06-29 10:55:24 +0800] debug/HostDbObject: host dependencies for 'l-yshow.fe.cn1'
[2017-06-29 10:55:24 +0800] debug/HostDbObject: host contacts: l-yshow.fe.cn1
[2017-06-29 10:55:24 +0800] debug/HostDbObject: host contactgroups: l-yshow.fe.cn1
[2017-06-29 10:55:24 +0800] notice/ApiListener: Discarding config update for object 'l-yshow.fe.cn1': Object version 1498704924.431518 is more recent than the received version 1498704924.431518.
[2017-06-29 10:55:25 +0800] debug/IdoMysqlConnection: Query: UPDATE icinga_hosts SET action_url = '',  active_checks_enabled = '1',  address = 'l-yshow.fe.cn1',  address6 = '',  alias = 'l-yshow.fe.cn1',  check_command_args = '',  check_command_object_id = 35,  check_interval = '5',  config_hash = '8ba9deb80bff4b2ce419e96edc4f014cd44f83c3a2d07ec28f42d2bd02384ea8',  config_type = '1',  display_name = 'l-yshow.fe.cn1',  event_handler_enabled = '1',  failure_prediction_enabled = '0',  flap_detection_enabled = '0',  freshness_checks_enabled = '1',  freshness_threshold = '300',  high_flap_threshold = '30',  host_object_id = 214,  icon_image = '',  icon_image_alt = '',  instance_id = 1,  low_flap_threshold = '30',  max_check_attempts = '3',  notes = '',  notes_url = '',  notification_interval = '30',  notifications_enabled = '1',  notify_on_down = '0',  notify_on_downtime = '1',  notify_on_flapping = '1',  notify_on_recovery = '1',  notify_on_unreachable = '0',  obsess_over_host = '0',  passive_checks_enabled = '1',  process_performance_data = '1',  retain_nonstatus_information = '1',  retain_status_information = '1',  retry_interval = '1' WHERE host_object_id = 214
[2017-06-29 10:55:26 +0800] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus SET acknowledgement_type = '0',  active_checks_enabled = '1',  check_command = 'nrpe',  check_source = 'l-cn0qicingan2.ops.cn2',  check_type = '0',  current_check_attempt = '1',  current_notification_number = '0',  current_state = '0',  endpoint_object_id = 211,  event_handler = '',  event_handler_enabled = '1',  execution_time = '0.769622',  flap_detection_enabled = '0',  has_been_checked = '1',  instance_id = 1,  is_flapping = '0',  is_reachable = '1',  last_check = FROM_UNIXTIME(1498704925),  last_hard_state = '0',  last_hard_state_change = FROM_UNIXTIME(1498448241),  last_state_change = FROM_UNIXTIME(1498448241),  last_time_ok = FROM_UNIXTIME(1498704925),  latency = '0.000376',  long_output = '',  max_check_attempts = '2',  next_check = FROM_UNIXTIME(1498704984),  normal_check_interval = '1',  notifications_enabled = '1',  original_attributes = 'null',  output = 'OK - Process salt-minion Process Number: 3. Process salt-minion CPU Usage: 0%. Version: salt 2016.3.0 (Boron)',  passive_checks_enabled = '1',  percent_state_change = '0',  perfdata = '',  problem_has_been_acknowledged = '0',  process_performance_data = '1',  retry_check_interval = '1',  scheduled_downtime_depth = '0',  service_object_id = 241,  should_be_scheduled = '1',  state_type = '1',  status_update_time = FROM_UNIXTIME(1498704925) WHERE service_object_id = 241
[2017-06-29 10:56:18 +0800] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus SET is_reachable = '1' WHERE instance_id = 1 AND service_object_id = 241
[2017-06-29 10:56:26 +0800] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus SET acknowledgement_type = '0',  active_checks_enabled = '1',  check_command = 'nrpe',  check_source = 'l-cn0qicingan2.ops.cn2',  check_type = '0',  current_check_attempt = '1',  current_notification_number = '0',  current_state = '0',  endpoint_object_id = 211,  event_handler = '',  event_handler_enabled = '1',  execution_time = '0.789167',  flap_detection_enabled = '0',  has_been_checked = '1',  instance_id = 1,  is_flapping = '0',  is_reachable = '1',  last_check = FROM_UNIXTIME(1498704985),  last_hard_state = '0',  last_hard_state_change = FROM_UNIXTIME(1498448241),  last_state_change = FROM_UNIXTIME(1498448241),  last_time_ok = FROM_UNIXTIME(1498704985),  latency = '0.000340',  long_output = '',  max_check_attempts = '2',  next_check = FROM_UNIXTIME(1498705044),  normal_check_interval = '1',  notifications_enabled = '1',  original_attributes = 'null',  output = 'OK - Process salt-minion Process Number: 3. Process salt-minion CPU Usage: 0%. Version: salt 2016.3.0 (Boron)',  passive_checks_enabled = '1',  percent_state_change = '0',  perfdata = '',  problem_has_been_acknowledged = '0',  process_performance_data = '1',  retry_check_interval = '1',  scheduled_downtime_depth = '0',  service_object_id = 241,  should_be_scheduled = '1',  state_type = '1',  status_update_time = FROM_UNIXTIME(1498704985) WHERE service_object_id = 241
```

**Comment by dnsmichi** [comment] 2017-06-29 09:49
Thanks for your report, that's a duplicate of #5205.

**Closed by dnsmichi** 2017-06-29 09:49 UTC
Labels: API, DB IDO
