### ISSUE TITLE
Some kind of print() statement for API Console

### ISSUE THREAD

**Issue by b33rcity** [Icinga/icinga2#6764] opened 2018-11-09 20:21 UTC
## Expected Behavior

To allow for easier testing of logic to be used in .conf files, it should be possible to have output of eg. a function print to the console. For example, 

```
<1> => function test(name) {
<1> ..   print("Hello " + name)
<1> .. }
<2>=> test("world")
```

should output "Hello world" to the console.

## Current Behavior

Currently the closest thing is the `log()` function:

```
<1> => function test(name) {
<1> ..   log("Hello " + name)
<1> .. }
```

but running this function returns `null` to the console. For a function named "log", I think this is fine--the console is not and should not be a log, not even if it's in a screen session!

## Possible Solution
Implement a function, `print()`, whose function is merely to take data and print it out on the console. 

For simplicity's sake, this should be a separate function from `log()` so as to 1) not break existing configs that use `log()` and may be sensitive to implementation changes, and 2) not make developers worry about 1. 

I also think "print" as the name for this function is a good choice because it is analogous to dozens of languages' print statements. "echo" would be a decent alternative for the same reason. Either would be widely understood by users to mean "sends given parameters to some kind of stdout". 

## Context

This would be extremely helpful for prototyping logic in conf files. When I discovered this functionality was lacking, I was trying to write a for-loop on the console for iterating through all Zone objects to return a given value from the Object. However, anything I tried return `null`, and I could not get the data that I wanted.

I spent over an hour assuming that my for-loop was malformed, then that I wasn't giving `log()` all that it needed, before finally concluding that this was either a bug or a lacking feature.

**Comment by Crunsher** [comment] 2018-11-12 10:40
Sounds like a great issue for someone who wishes to work on one of the less peripheral modules of Icinga 2

**Comment by dnsmichi** [comment] 2019-05-07 11:42
Should be taken into account with #4712

**Comment by htriem** [comment] 2020-01-22 11:01
This will be implemented with #7395. Therefore I'm closing this ticket.

**Closed by htriem** 2020-01-22 11:01 UTC
Labels: enhancement, good first issue

**Comment by Al2Klimov** [comment] 2020-01-23 13:26
@htriem Isn't #7395 about a `printf()` function and this one about where logs of `log()` in the console go to?

**Comment by dnsmichi** [comment] 2020-01-23 15:21
@Al2Klimov not the logs should go to the console, but the call to `log()` should print something inside the console. This is similar to what printf() and variants will be doing.

In order to keep the issue tracker clean, only one working issue is open, the others are closed.

Your PR implements a totally different thing btw.

**Comment by Al2Klimov** [comment] 2020-01-23 15:23
> not the logs should go to the console, but the call to `log()` should print something inside the console

So that *something* are not the logs caused by the call to `log()`?

**Comment by dnsmichi** [comment] 2020-01-23 15:27
Something like this, and that's primarily related to printf() too.

```
<1> var n = "Alex"
<2> print "hello " + n
"Hello Alex" 
```

**Comment by Al2Klimov** [comment] 2020-01-23 15:28
OK, but this seems not to differ a lot from #7775.
