### ISSUE TITLE
using icinga director, remove hosts (with empty zone as result) doesn't work

### ISSUE THREAD

**Issue by tlo8640** [Icinga/icinga2#5722] opened 2017-11-07 08:36 UTC
Hello
coming from

Icinga/icingaweb2-module-director#1219

Don't know if this is a Icingaweb2 Director Problem or an Icinga2 Problem.
Tried it on different icinga2 setupups and ran always into this problem.

Using Icinga Director for configuring icinga2. When you try to remove hosts, wich would lead into an empty zone. The hosts will be removed from Director, but they still exist in icinga2 config after deploying the director config.
Expected Behavior

Host should be removed from Icinga2 config, too.

Current Behavior

When you are using Icinga Director for configuring Icinga2 and you want to remove some hosts and after removing a zone would be empty, these hosst aren't removed from icinga2, but they are removed from Icinga2 Director.
Possible Solution

Don't know how Icinga Director deploys its config. When deploying the new config with the empty zone, no hostz config for the empty zone is created (seem to me) and therefore this zone will not be touched and keeps it former config?
Steps to Reproduce (for bugs)

1.setup icinga2 with director
2.create one or more zones
3. deploy one or more hosts into the zone(s), only hostchecks are ok
4. remove all hosts from one zone so that the zone should be empty
5. deploy new config with director
6. voila: the removed hosts still exist in icinga2, but are removed from director

Context

First we ran into this problem when we tried configuration with Icinga Director, because not so many Hosts where in the testing environment and they were often added and removed.
Also in production the problem could be a problem, for instance, when you redesign your zones infrastructure or something like this and you have to move servers between zones.
Your Environment

    Director version (System - About): 1.4.1
    Version used (icinga2 --version): 2.7.1.1
    Operating System and version: RHEL 7.4

**Comment by dnsmichi** [comment] 2017-11-07 09:44
What exactly do you mean with "still exist in Icinga 2"?

- query the REST API endpoints /v1/objects/hosts and /v1/objects/services and post your findings on the objects here
- ls -lR /var/lib/icinga2/api/packages

**Comment by tlo8640** [comment] 2017-11-15 15:11
Hello,
trying to give you all infos you requested, hopefully it will help.
starting with empty icinga2 config
removed all existing host an service definitions

notes:
- replaced "real" master hostname with icinga2-master1.FQDN
- replaced "real" testserver hostname with "testserver"
- replaced "real" testerver IP with XXX.XXX.XXX.XXX

### Icinga is empty

#### querying REST API

root@icinga2-master1: # curl -k -s -u admin:admin 'https://localhost:5665/v1/objects/services'|python -m json.tool
{
    "results": []
}
root@icinga2-master1: # curl -k -s -u admin:admin 'https://localhost:5665/v1/objects/hosts'|python -m json.tool
{
    "results": []
}

#### ls -lR /var/lib/icinga2/api/packages/

root@icinga2-master1: # ls -lR /var/lib/icinga2/api/packages/
/var/lib/icinga2/api/packages/:
total 0
root@icinga2-master1: # 

### creating testserver

now adding one host (without any services) to the Checkzone "app-chk2" using icingaweb2-director

#### querying REST API

root@icinga2-master1: # curl -k -s -u admin:admin 'https://localhost:5665/v1/objects/hosts'|python -m json.tool
{
    "results": [
        {
            "attrs": {
                "__name": "testserver",
                "acknowledgement": 0.0,
                "acknowledgement_expiry": 0.0,
                "action_url": "",
                "active": true,
                "address": "XXX.XXX.XXX.XXX",
                "address6": "",
                "check_attempt": 1.0,
                "check_command": "hostalive4",
                "check_interval": 60.0,
                "check_period": "",
                "check_timeout": null,
                "command_endpoint": "",
                "display_name": "testserver",
                "downtime_depth": 0.0,
                "enable_active_checks": true,
                "enable_event_handler": true,
                "enable_flapping": false,
                "enable_notifications": true,
                "enable_passive_checks": true,
                "enable_perfdata": true,
                "event_command": "",
                "flapping": false,
                "flapping_last_change": 0.0,
                "flapping_negative": 0.0,
                "flapping_positive": 0.0,
                "flapping_threshold": 30.0,
                "force_next_check": false,
                "force_next_notification": false,
                "groups": [],
                "ha_mode": 0.0,
                "icon_image": "",
                "icon_image_alt": "",
                "last_check": -1.0,
                "last_check_result": null,
                "last_hard_state": 1.0,
                "last_hard_state_change": 1510756529.8256,
                "last_reachable": true,
                "last_state": 1.0,
                "last_state_change": 1510756529.8256,
                "last_state_down": 0.0,
                "last_state_type": 0.0,
                "last_state_unreachable": 0.0,
                "last_state_up": 0.0,
                "max_check_attempts": 3.0,
                "name": "testserver",
                "next_check": 1510756589.840762,
                "notes": "",
                "notes_url": "",
                "original_attributes": null,
                "package": "director",
                "paused": false,
                "retry_interval": 20.0,
                "severity": 24.0,
                "source_location": {
                    "first_column": 0.0,
                    "first_line": 1.0,
                    "last_column": 39.0,
                    "last_line": 1.0,
                    "path": "/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/zones.d/app-chk2/hosts.conf"
                },
                "state": 1.0,
                "state_type": 0.0,
                "templates": [
                    "testserver",
                    "generic_host"
                ],
                "type": "Host",
                "vars": null,
                "version": 0.0,
                "volatile": false,
                "zone": "app-chk2"
            },
            "joins": {},
            "meta": {},
            "name": "testserver",
            "type": "Host"
        }
    ]
}
root@icinga2-master1: # curl -k -s -u admin:admin 'https://localhost:5665/v1/objects/services'|python -m json.tool
{
    "results": []
}
root@icinga2-master1: # 

#### ls -lR /var/lib/icinga2/api/packages/

root@icinga2-master1: # ls -lR /var/lib/icinga2/api/packages/
/var/lib/icinga2/api/packages/:
total 0
drwx------ 3 icinga icinga 112 Nov 15 15:35 director

/var/lib/icinga2/api/packages/director:
total 12
-rw-r--r-- 1 icinga icinga 472 Nov 15 15:35 active.conf
-rw-r--r-- 1 icinga icinga  39 Nov 15 15:35 active-stage
-rw-r--r-- 1 icinga icinga  25 Nov 15 15:35 include.conf
drwx------ 4 icinga icinga  88 Nov 15 15:35 icinga2-master1.FQDN-1510756527-0

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0:
total 12
drwx------ 2 icinga icinga    6 Nov 15 15:35 conf.d
-rw-r--r-- 1 icinga icinga  171 Nov 15 15:35 include.conf
-rw-r--r-- 1 icinga icinga 3640 Nov 15 15:35 startup.log
-rw-r--r-- 1 icinga icinga    1 Nov 15 15:35 status
drwx------ 5 icinga icinga   59 Nov 15 15:35 zones.d

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/conf.d:
total 0

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/zones.d:
total 0
drwxr-x--- 2 icinga icinga  24 Nov 15 15:35 app-chk2
drwxr-x--- 2 icinga icinga 273 Nov 15 15:35 director-global
drwxr-x--- 2 icinga icinga 113 Nov 15 15:35 master

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/zones.d/app-chk2:
total 4
-rw-r--r-- 1 icinga icinga 101 Nov 15 15:35 hosts.conf

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/zones.d/director-global:
total 36
-rw-r--r-- 1 icinga icinga  518 Nov 15 15:35 001-director-basics.conf
-rw-r--r-- 1 icinga icinga 1357 Nov 15 15:35 commands.conf
-rw-r--r-- 1 icinga icinga  420 Nov 15 15:35 hostgroups.conf
-rw-r--r-- 1 icinga icinga 1027 Nov 15 15:35 host_templates.conf
-rw-r--r-- 1 icinga icinga    0 Nov 15 15:35 service_apply.conf
-rw-r--r-- 1 icinga icinga 1370 Nov 15 15:35 servicesets.conf
-rw-r--r-- 1 icinga icinga 1808 Nov 15 15:35 service_templates.conf
-rw-r--r-- 1 icinga icinga  364 Nov 15 15:35 timeperiods.conf
-rw-r--r-- 1 icinga icinga  123 Nov 15 15:35 timeperiod_templates.conf
-rw-r--r-- 1 icinga icinga  263 Nov 15 15:35 user_templates.conf

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/zones.d/master:
total 16
-rw-r--r-- 1 icinga icinga 565 Nov 15 15:35 notification_apply.conf
-rw-r--r-- 1 icinga icinga 352 Nov 15 15:35 notification_templates.conf
-rw-r--r-- 1 icinga icinga 214 Nov 15 15:35 usergroups.conf
-rw-r--r-- 1 icinga icinga 235 Nov 15 15:35 users.conf
root@icinga2-master1: # 

Everything seems to be fine.
Host is in Icinga2 and is monitored using ping check

### removing testserver

Now I try to remove this host from Iicnga2 using Icingaweb2 Director
- Remove Host in Director
- Deploy changes in Director
- Host is removed from Director
- but still exists in Icinga2
- I still can see the host in icingaweb2

#### querying REST API

BUT, surprise!
Querying the icinga2 API doesn't give back anything:
root@icinga2-master1: # curl -k -s -u admin:admin 'https://localhost:5665/v1/objects/hosts'|python -m json.tool
{
    "results": []
}
root@icinga2-master1: # 

#### ls -lR /var/lib/icinga2/api/packages/

But, the packages folder has still some content:
root@icinga2-master1: # ls -lR /var/lib/icinga2/api/packages/
/var/lib/icinga2/api/packages/:
total 0
drwx------ 4 icinga icinga 159 Nov 15 15:42 director

/var/lib/icinga2/api/packages/director:
total 12
-rw-r--r-- 1 icinga icinga 472 Nov 15 15:42 active.conf
-rw-r--r-- 1 icinga icinga  39 Nov 15 15:42 active-stage
-rw-r--r-- 1 icinga icinga  25 Nov 15 15:42 include.conf
drwx------ 4 icinga icinga  88 Nov 15 15:35 icinga2-master1.FQDN-1510756527-0
drwx------ 4 icinga icinga  88 Nov 15 15:42 icinga2-master1.FQDN-1510756967-0

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0:
total 12
drwx------ 2 icinga icinga    6 Nov 15 15:35 conf.d
-rw-r--r-- 1 icinga icinga  171 Nov 15 15:35 include.conf
-rw-r--r-- 1 icinga icinga 3640 Nov 15 15:35 startup.log
-rw-r--r-- 1 icinga icinga    1 Nov 15 15:35 status
drwx------ 5 icinga icinga   59 Nov 15 15:35 zones.d

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/conf.d:
total 0

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/zones.d:
total 0
drwxr-x--- 2 icinga icinga  24 Nov 15 15:35 app-chk2
drwxr-x--- 2 icinga icinga 273 Nov 15 15:35 director-global
drwxr-x--- 2 icinga icinga 113 Nov 15 15:35 master

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/zones.d/app-chk2:
total 4
-rw-r--r-- 1 icinga icinga 101 Nov 15 15:35 hosts.conf

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/zones.d/director-global:
total 36
-rw-r--r-- 1 icinga icinga  518 Nov 15 15:35 001-director-basics.conf
-rw-r--r-- 1 icinga icinga 1357 Nov 15 15:35 commands.conf
-rw-r--r-- 1 icinga icinga  420 Nov 15 15:35 hostgroups.conf
-rw-r--r-- 1 icinga icinga 1027 Nov 15 15:35 host_templates.conf
-rw-r--r-- 1 icinga icinga    0 Nov 15 15:35 service_apply.conf
-rw-r--r-- 1 icinga icinga 1370 Nov 15 15:35 servicesets.conf
-rw-r--r-- 1 icinga icinga 1808 Nov 15 15:35 service_templates.conf
-rw-r--r-- 1 icinga icinga  364 Nov 15 15:35 timeperiods.conf
-rw-r--r-- 1 icinga icinga  123 Nov 15 15:35 timeperiod_templates.conf
-rw-r--r-- 1 icinga icinga  263 Nov 15 15:35 user_templates.conf

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/zones.d/master:
total 16
-rw-r--r-- 1 icinga icinga 565 Nov 15 15:35 notification_apply.conf
-rw-r--r-- 1 icinga icinga 352 Nov 15 15:35 notification_templates.conf
-rw-r--r-- 1 icinga icinga 214 Nov 15 15:35 usergroups.conf
-rw-r--r-- 1 icinga icinga 235 Nov 15 15:35 users.conf

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0:
total 12
drwx------ 2 icinga icinga    6 Nov 15 15:42 conf.d
-rw-r--r-- 1 icinga icinga  171 Nov 15 15:42 include.conf
-rw-r--r-- 1 icinga icinga 3595 Nov 15 15:42 startup.log
-rw-r--r-- 1 icinga icinga    1 Nov 15 15:42 status
drwx------ 4 icinga icinga   43 Nov 15 15:42 zones.d

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/conf.d:
total 0

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d:
total 0
drwxr-x--- 2 icinga icinga 273 Nov 15 15:42 director-global
drwxr-x--- 2 icinga icinga 113 Nov 15 15:42 master

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global:
total 36
-rw-r--r-- 1 icinga icinga  518 Nov 15 15:42 001-director-basics.conf
-rw-r--r-- 1 icinga icinga 1357 Nov 15 15:42 commands.conf
-rw-r--r-- 1 icinga icinga  420 Nov 15 15:42 hostgroups.conf
-rw-r--r-- 1 icinga icinga 1027 Nov 15 15:42 host_templates.conf
-rw-r--r-- 1 icinga icinga    0 Nov 15 15:42 service_apply.conf
-rw-r--r-- 1 icinga icinga 1370 Nov 15 15:42 servicesets.conf
-rw-r--r-- 1 icinga icinga 1808 Nov 15 15:42 service_templates.conf
-rw-r--r-- 1 icinga icinga  364 Nov 15 15:42 timeperiods.conf
-rw-r--r-- 1 icinga icinga  123 Nov 15 15:42 timeperiod_templates.conf
-rw-r--r-- 1 icinga icinga  263 Nov 15 15:42 user_templates.conf

/var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/master:
total 16
-rw-r--r-- 1 icinga icinga 565 Nov 15 15:42 notification_apply.conf
-rw-r--r-- 1 icinga icinga 352 Nov 15 15:42 notification_templates.conf
-rw-r--r-- 1 icinga icinga 214 Nov 15 15:42 usergroups.conf
-rw-r--r-- 1 icinga icinga 235 Nov 15 15:42 users.conf
root@icinga2-master1: #

**Comment by dnsmichi** [comment] 2017-11-15 15:30
Good analysis so far 👍 

Config packages used by the Director push stages. There only is one active stage, others are not active. You can manually find out with `cat /var/lib/icinga2/api/packages/director/active-stage` pointing to the included directory. `icinga2 daemon -C -x notice | grep director` will also show you the loaded configuration files.

As you've already gone through the API steps, Icinga 2 does not know anything about the object. This seems to be related to the IDO database backend where Icinga Web 2 retrieves its data from.

Try to query to backend manually from such a host/service. Details on the DB schema are found in the docs.

```
select * from icinga_hosts h join icinga_objects oh on h.host_object_id=oh.object_id where oh.name1='testserver';

select * from icinga_hostsatus hs join icinga_objects ohs on hs.host_object_id=ohs.object_id where ohs.name1='testserver';
```

The `is_active` column must be 0 in this case. If not, investigate on why your backend is not updated, e.g. by turning on debug log and checking for the respective IDO queries for that host.

**Comment by tlo8640** [comment] 2017-11-16 10:55
very interesting, at least if the host still exists in idodb with flag "is_active=1" it will showed in icingaweb2.

Updating these entries in idodb (last check time and others) stopped right after deleting the host using director. So icinga2 really doesn't know this host. but somehow the "is_active" flag is still set to "1".

Did I already told you, that this only happens when the host I want to delete is the last one in the zone? 

I tried it with two hosts, I mean, I added two hosts into one zone and removed one of them. Then, the "is_active" Flag was set to "0".

Here come the output from the commands you gave in your previous comment, 

#### cat /var/lib/icinga2/api/packages/director/active-stage

root@icinga2-master1: # cat /var/lib/icinga2/api/packages/director/active-stage
icinga2-master1.FQDN-1510756967-0
root@icinga2-master1: # 

#### icinga2 daemon -C -x notice | grep director

root@icinga2-master1: # icinga2 daemon -C -x notice | grep director
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/include.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/include.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/include.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756527-0/../active.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/../active.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/001-director-basics.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/commands.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/host_templates.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/hostgroups.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/service_apply.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/service_templates.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/servicesets.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/timeperiod_templates.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/timeperiods.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/user_templates.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/master/notification_apply.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/master/notification_templates.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/master/usergroups.conf
notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/master/users.conf
notice/ConfigCompiler: Registered authoritative config directories for zone 'director-global': /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global
notice/config: Ignoring non local config include for zone 'director-global': We already have an authoritative copy included.
notice/ConfigCompiler: Registered authoritative config directories for zone 'global-templates': /etc/icinga2/zones.d/global-templates
notice/ConfigCompiler: Registered authoritative config directories for zone 'master': /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/master
warning/ApplyRule: Apply rule 'host-notification' (in /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/master/notification_apply.conf: 1:0-1:45) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'service-notification' (in /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/master/notification_apply.conf: 9:1-9:52) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'check_load' (in /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/servicesets.conf: 5:1-5:26) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'check_disk' (in /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/servicesets.conf: 14:1-14:26) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'check_ssh' (in /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/servicesets.conf: 23:1-23:25) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'check_swap' (in /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/servicesets.conf: 32:1-32:26) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'check_icinga' (in /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/servicesets.conf: 41:1-41:28) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'check_mysql' (in /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/servicesets.conf: 50:1-50:27) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'check_galera_cluster_sync' (in /var/lib/icinga2/api/packages/director/icinga2-master1.FQDN-1510756967-0/zones.d/director-global/servicesets.conf: 61:1-61:41) for type 'Service' does not match anywhere!

#### mysql queries

MariaDB [ido_db_test1]> select * from icinga_hosts h join icinga_objects oh on h.host_object_id=oh.object_id where oh.name1='testerver'\G
*************************** 1. row ***************************
                          host_id: 13
                      instance_id: 13
                      config_type: 1
                   host_object_id: 1490
                            alias: testerver
                     display_name: testerver
                          address: XXX.XXX.XXX.XXX
                         address6: 
          check_command_object_id: 209
               check_command_args: 
   eventhandler_command_object_id: 0
        eventhandler_command_args: NULL
notification_timeperiod_object_id: 0
       check_timeperiod_object_id: 0
       failure_prediction_options: 
                   check_interval: 1
                   retry_interval: 0.333333
               max_check_attempts: 3
         first_notification_delay: 0
            notification_interval: 1
                   notify_on_down: 0
            notify_on_unreachable: 0
               notify_on_recovery: 0
               notify_on_flapping: 0
               notify_on_downtime: 0
                      stalk_on_up: 0
                    stalk_on_down: 0
             stalk_on_unreachable: 0
           flap_detection_enabled: 0
             flap_detection_on_up: 0
           flap_detection_on_down: 0
    flap_detection_on_unreachable: 0
               low_flap_threshold: 30
              high_flap_threshold: 30
         process_performance_data: 1
         freshness_checks_enabled: 1
              freshness_threshold: 60
           passive_checks_enabled: 1
            event_handler_enabled: 1
            active_checks_enabled: 1
        retain_status_information: 1
     retain_nonstatus_information: 1
            notifications_enabled: 1
                 obsess_over_host: 0
       failure_prediction_enabled: 0
                            notes: 
                        notes_url: 
                       action_url: 
                       icon_image: 
                   icon_image_alt: 
                       vrml_image: NULL
                  statusmap_image: NULL
                   have_2d_coords: 0
                             x_2d: 0
                             y_2d: 0
                   have_3d_coords: 0
                             x_3d: 0
                             y_3d: 0
                             z_3d: 0
                      config_hash: 03a4cf9bf3fda7217c6037dafa221d8f5a03240179fa051e132eed4eb52b05a0
                        object_id: 1490
                      instance_id: 13
                    objecttype_id: 1
                            name1: testerver
                            name2: NULL
                        is_active: 1
1 row in set (0.01 sec)

MariaDB [ido_db_test1]> 


MariaDB [ido_db_test1]> select * from icinga_hoststatus hs join icinga_objects ohs on hs.host_object_id=ohs.object_id where ohs.name1='testerver'\G
*************************** 1. row ***************************
                hoststatus_id: 13
                  instance_id: 13
               host_object_id: 1490
           status_update_time: 2017-11-15 15:42:47
                       output: PING OK - Packet loss = 0%, RTA = 2.98 ms
                  long_output: 
                     perfdata: rta=2.982000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0
                 check_source: checkserver
                current_state: 0
             has_been_checked: 1
          should_be_scheduled: 1
        current_check_attempt: 1
           max_check_attempts: 3
                   last_check: 2017-11-15 15:42:47
                   next_check: 2017-11-15 15:43:46
                   check_type: 0
            last_state_change: 2017-11-15 15:36:34
       last_hard_state_change: 2017-11-15 15:36:34
              last_hard_state: 0
                 last_time_up: 2017-11-15 15:42:47
               last_time_down: NULL
        last_time_unreachable: NULL
                   state_type: 1
            last_notification: NULL
            next_notification: NULL
        no_more_notifications: 0
        notifications_enabled: 1
problem_has_been_acknowledged: 0
         acknowledgement_type: 0
  current_notification_number: 0
       passive_checks_enabled: 1
        active_checks_enabled: 1
        event_handler_enabled: 1
       flap_detection_enabled: 0
                  is_flapping: 0
         percent_state_change: 0
                      latency: 0.000653
               execution_time: 4.027573
     scheduled_downtime_depth: 0
   failure_prediction_enabled: 0
     process_performance_data: 1
             obsess_over_host: 0
     modified_host_attributes: 0
          original_attributes: null
                event_handler: 
                check_command: hostalive4
        normal_check_interval: 1
         retry_check_interval: 0.333333
   check_timeperiod_object_id: 0
                 is_reachable: 1
           endpoint_object_id: 1462
                    object_id: 1490
                  instance_id: 13
                objecttype_id: 1
                        name1: testerver
                        name2: NULL
                    is_active: 1
1 row in set (0.01 sec)

#### icinga2 debug output

will follow soon, have to read the manual first...

**Comment by tlo8640** [comment] 2017-11-16 15:22
Hello,
Is there any possibility to show the ido qeries in debug.log?
I enabled debug.log but got not so much information from output:

I added (and removed) the server with the name "testserver3" to icinga2.

The server removal using director started shortly after debug log is starting 

#### debug log (Db* grepped)

Here ist the debug/Db* output (grepped from debug.log):

[2017-11-16 15:48:01 +0100] information/DbConnection: 'ido-mysql' started.
[2017-11-16 15:48:01 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'checkserver1'
[2017-11-16 15:48:01 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'checkserver4'
[2017-11-16 15:48:01 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'checkserver2'
[2017-11-16 15:48:01 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'checkserver3'
[2017-11-16 15:48:01 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'icinga2-master2'
[2017-11-16 15:48:02 +0100] debug/DbEvents: add checkable check history for 'testserver3'
[2017-11-16 15:48:02 +0100] debug/DbEvents: add checkable check history for 'testserver3'
[2017-11-16 15:48:11 +0100] notice/DbConnection: Updating programstatus table.
[2017-11-16 15:48:16 +0100] information/DbConnection: 'ido-mysql' started.
[2017-11-16 15:48:16 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'checkserver1'
[2017-11-16 15:48:16 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'checkserver2'
[2017-11-16 15:48:16 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'checkserver3'
[2017-11-16 15:48:16 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'icinga2-master2'
[2017-11-16 15:48:16 +0100] debug/EndpointDbObject: update is_connected=1 for endpoint 'checkserver4'
[2017-11-16 15:48:26 +0100] notice/DbConnection: Updating programstatus table.
[2017-11-16 15:48:36 +0100] notice/DbConnection: Updating programstatus table.
[2017-11-16 15:48:46 +0100] notice/DbConnection: Updating programstatus table.

The whole debug log is over 100 k.
I attach the complete debug log 


#### ido entry of testserver3

MariaDB [ido_db_test1]> select * from icinga_hoststatus hs join icinga_objects ohs on hs.host_object_id=ohs.object_id where ohs.name1='testserver3'\G
*************************** 1. row ***************************
                hoststatus_id: 13079
                  instance_id: 13
               host_object_id: 15543
           status_update_time: 2017-11-16 15:48:02
                       output: PING OK - Packet loss = 0%, RTA = 3.73 ms
                  long_output: 
                     perfdata: rta=3.726000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0
                 check_source: vimapsst-mock03.it.bwns.ch
                current_state: 0
             has_been_checked: 1
          should_be_scheduled: 1
        current_check_attempt: 1
           max_check_attempts: 3
                   last_check: 2017-11-16 15:48:02
                   next_check: 2017-11-16 15:49:00
                   check_type: 0
            last_state_change: 2017-11-16 15:41:45
       last_hard_state_change: 2017-11-16 15:41:45
              last_hard_state: 0
                 last_time_up: 2017-11-16 15:48:02
               last_time_down: NULL
        last_time_unreachable: NULL
                   state_type: 1
            last_notification: NULL
            next_notification: NULL
        no_more_notifications: 0
        notifications_enabled: 1
problem_has_been_acknowledged: 0
         acknowledgement_type: 0
  current_notification_number: 0
       passive_checks_enabled: 1
        active_checks_enabled: 1
        event_handler_enabled: 1
       flap_detection_enabled: 0
                  is_flapping: 0
         percent_state_change: 0
                      latency: 0.000553
               execution_time: 4.027116
     scheduled_downtime_depth: 0
   failure_prediction_enabled: 0
     process_performance_data: 1
             obsess_over_host: 0
     modified_host_attributes: 0
          original_attributes: null
                event_handler: 
                check_command: hostalive4
        normal_check_interval: 1
         retry_check_interval: 0.333333
   check_timeperiod_object_id: 0
                 is_reachable: 1
           endpoint_object_id: 1462
                    object_id: 15543
                  instance_id: 13
                objecttype_id: 1
                        name1: testserver3
                        name2: NULL
                    is_active: 1
1 row in set (0.01 sec)




[notes3_all_debug.txt](https://github.com/Icinga/icinga2/files/1479066/notes3_all_debug.txt)

**Comment by tlo8640** [comment] 2017-11-17 08:43
forget my previous debug log output.
I recorded it on the passive master node :-(
Try the same steps on the primary node now and resend the debug output.

**Comment by tlo8640** [comment] 2017-11-17 14:47
OK, second try,
After the desaster with debugging on passive master and wondering about minimal output, now I tried on active part of icinga cluster.

At least I made 3 runs
1. testerver4 as the only one in Zone was removed (testserver4 still in ido with "is_active=1")
1. testserver3 and testserver4 in one zone, remove only testserver3 (testserver3 in ido with "is_active=0", worked as expected)
1. remove testserver4 second try (testserver4 still in ido with "is_active=1")

when I removed one of the two servers in the checkzone (2nd test) there was following line in debugging output:
notice/IdoMysqlConnection: Deactivate deleted object name1: 'testserver3' name2: ''
this line didn't appeared in the other two tests
but why?

I attach the debug log from all three tests

[debug.log_remove_testserver3_one_of_two.log_cleaned.log](https://github.com/Icinga/icinga2/files/1482659/debug.log_remove_testserver3_one_of_two.log_cleaned.log)
[debug.log_remove_testserver4.log_cleaned.log](https://github.com/Icinga/icinga2/files/1482660/debug.log_remove_testserver4.log_cleaned.log)
[debug.log_remove_testserver4_2nd_try.log_cleaned.log](https://github.com/Icinga/icinga2/files/1482661/debug.log_remove_testserver4_2nd_try.log_cleaned.log)

**Comment by NeverUsedID** [comment] 2017-12-01 10:47
I would think its the same issue and so it has to do with Iicinga and not with the  director:  

https://github.com/Icinga/icinga2/issues/4191

**Comment by tlo8640** [comment] 2017-12-05 07:14
it seems, that this bugs is quite old.
thanks for the hint with the workaround
creating an empty file sounds like a workaround for the moment, have to test it, but it can't be more then a temporary workaround.
Any chance to get this fixed  in near future?
thanks

**Comment by dnsmichi** [comment] 2018-01-08 13:44
@NeverUsedID thanks for the heads up 👍 

@tlo8640 maybe you can look into the code and make suggestions in a PR in order to fix it.

Closing this one as partial duplicate of #4191.

Cheers,
Michael

**Closed by dnsmichi** 2018-01-08 13:44 UTC
Labels: API, DB IDO, needs-feedback
