### ISSUE TITLE
Commands are not executed on client

### ISSUE THREAD

**Issue by djschilling** [Icinga/icinga2#6335] opened 2018-05-24 13:42 UTC
After upgrading icinga to version `r2.8.1-1` i wanted to change to the new Top Down Config Sync because the old i used was removed. I followed the steps here: https://github.com/Icinga/icinga2/blob/v2.7.0/doc/06-distributed-monitoring.md#bottom-up-migration-to-top-down-

After following the instructions the client that i converted shows up in the icinga2 web but every service is pending. Also when i try to `check now` nothing happens. It seems like the command is not executed on the client.

Here an excerpt from the masters log:

```
[2018-05-24 15:09:41 +0200] information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);
[2018-05-24 15:09:41 +0200] information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate: 0.683333/s (41/min 41/5min 41/15min);
[2018-05-24 15:09:41 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 0, rate: 0.366667/s (22/min 22/5min 22/15min);
[2018-05-24 15:09:41 +0200] information/WorkQueue: #10 (JsonRpcConnection, #0) items: 0, rate: 0.0666667/s (4/min 4/5min 4/15min);
[2018-05-24 15:09:41 +0200] information/WorkQueue: #11 (JsonRpcConnection, #1) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-05-24 15:10:00 +0200] information/ExternalCommandListener: Executing external command: [1527167400] SCHEDULE_FORCED_SVC_CHECK;chat102.ct-srv.de;load;1527167400
[2018-05-24 15:10:17 +0200] information/ExternalCommandListener: Executing external command: [1527167417] SCHEDULE_FORCED_SVC_CHECK;chat102.ct-srv.de;load;1527167417
[2018-05-24 15:10:21 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 2, rate: 2.23333/s (134/min 134/5min 134/15min);
[2018-05-24 15:10:31 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 6, rate: 3.23333/s (194/min 198/5min 198/15min);
[2018-05-24 15:10:41 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 6, rate: 3.7/s (222/min 244/5min 244/15min);
[2018-05-24 15:11:17 +0200] information/ExternalCommandListener: Executing external command: [1527167477] SCHEDULE_FORCED_SVC_CHECK;chat102.ct-srv.de;load;1527167477
[2018-05-24 15:12:23 +0200] information/ExternalCommandListener: Executing external command: [1527167543] SCHEDULE_FORCED_SVC_CHECK;chat102.ct-srv.de;load;1527167543
[2018-05-24 15:13:11 +0200] information/ExternalCommandListener: Executing external command: [1527167591] SCHEDULE_FORCED_SVC_CHECK;chat102.ct-srv.de;load;1527167591
[2018-05-24 15:14:31 +0200] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
[2018-05-24 15:14:51 +0200] information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);
[2018-05-24 15:14:51 +0200] information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate: 1.4/s (84/min 430/5min 471/15min);
[2018-05-24 15:14:51 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 0, rate: 3.51667/s (211/min 1093/5min 1151/15min);
[2018-05-24 15:14:51 +0200] information/WorkQueue: #11 (JsonRpcConnection, #1) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-05-24 15:14:51 +0200] information/WorkQueue: #10 (JsonRpcConnection, #0) items: 0, rate: 0.3/s (18/min 90/5min 97/15min);
[2018-05-24 15:19:11 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 5, rate: 3.58333/s (215/min 1099/5min 2093/15min);
[2018-05-24 15:19:31 +0200] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
[2018-05-24 15:20:01 +0200] information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate: 1.36667/s (82/min 419/5min 890/15min);
[2018-05-24 15:20:01 +0200] information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);
[2018-05-24 15:20:01 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 0, rate: 3.45/s (207/min 1081/5min 2266/15min);
[2018-05-24 15:20:01 +0200] information/WorkQueue: #10 (JsonRpcConnection, #0) items: 0, rate: 0.3/s (18/min 90/5min 190/15min);
[2018-05-24 15:20:01 +0200] information/WorkQueue: #11 (JsonRpcConnection, #1) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-05-24 15:23:21 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 3, rate: 3.55/s (213/min 1093/5min 3012/15min);
[2018-05-24 15:24:31 +0200] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
[2018-05-24 15:25:11 +0200] information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);
[2018-05-24 15:25:11 +0200] information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate: 1.43333/s (86/min 426/5min 1298/15min);
[2018-05-24 15:25:11 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 0, rate: 3.63333/s (218/min 1096/5min 3300/15min);
[2018-05-24 15:25:11 +0200] information/WorkQueue: #11 (JsonRpcConnection, #1) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-05-24 15:25:11 +0200] information/WorkQueue: #10 (JsonRpcConnection, #0) items: 0, rate: 0.3/s (18/min 90/5min 270/15min);
[2018-05-24 15:27:17 +0200] warning/TlsStream: TLS stream was disconnected.
[2018-05-24 15:27:17 +0200] warning/JsonRpcConnection: API client disconnected for identity 'chat102.ct-srv.de'
[2018-05-24 15:27:17 +0200] warning/ApiListener: Removing API client for endpoint 'chat102.ct-srv.de'. 0 API clients left.
[2018-05-24 15:27:17 +0200] information/ApiListener: New client connection for identity 'chat102.ct-srv.de' from [192.168.20.20]:56398
[2018-05-24 15:27:17 +0200] information/ApiListener: Sending config updates for endpoint 'chat102.ct-srv.de' in zone 'chat102.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished sending config file updates for endpoint 'chat102.ct-srv.de' in zone 'chat102.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Syncing runtime objects to endpoint 'chat102.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished syncing runtime objects to endpoint 'chat102.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished sending runtime config updates for endpoint 'chat102.ct-srv.de' in zone 'chat102.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Sending replay log for endpoint 'chat102.ct-srv.de' in zone 'chat102.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished sending replay log for endpoint 'chat102.ct-srv.de' in zone 'chat102.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished syncing endpoint 'chat102.ct-srv.de' in zone 'chat102.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/JsonRpcConnection: Received certificate request for CN 'chat102.ct-srv.de' signed by our CA.
[2018-05-24 15:27:17 +0200] information/JsonRpcConnection: The certificate for CN 'chat102.ct-srv.de' cannot be renewed yet.
[2018-05-24 15:27:31 +0200] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 5, rate: 3.66667/s (220/min 1094/5min 3288/15min);
[2018-05-24 15:27:54 +0200] information/ExternalCommandListener: Executing external command: [1527168474] SCHEDULE_FORCED_SVC_CHECK;chat102.ct-srv.de;load;1527168474
```

Here an excerpt from the clients log:

```
[2018-05-24 15:22:49 +0200] information/WorkQueue: #5 (ApiListener, SyncQueue) items: 0, rate: 0.0166667/s (1/min 3/5min 5/15min);
[2018-05-24 15:22:49 +0200] information/WorkQueue: #4 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-05-24 15:22:49 +0200] information/WorkQueue: #8 (JsonRpcConnection, #0) items: 0, rate: 0.116667/s (7/min 31/5min 105/15min);
[2018-05-24 15:22:49 +0200] information/WorkQueue: #9 (JsonRpcConnection, #1) items: 0, rate: 0.1/s (6/min 39/5min 84/15min);
[2018-05-24 15:26:19 +0200] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
[2018-05-24 15:27:17 +0200] information/Application: Received request to shut down.
[2018-05-24 15:27:17 +0200] information/Application: Shutting down...
[2018-05-24 15:27:17 +0200] information/ApiListener: 'api' stopped.
[2018-05-24 15:27:17 +0200] information/CheckerComponent: 'checker' stopped.
[2018-05-24 15:27:17 +0200] information/CheckerComponent: 'checker' started.
[2018-05-24 15:27:17 +0200] information/ExternalCommandListener: 'command' started.
[2018-05-24 15:27:17 +0200] information/ConfigItem: Activated all objects.
[2018-05-24 15:27:17 +0200] information/ApiListener: Reconnecting to endpoint 'icinga101.ct-srv.de' via host 'icinga101.ct-srv.de' and port '5665'
[2018-05-24 15:27:17 +0200] information/ApiListener: New client connection for identity 'icinga101.ct-srv.de' to [192.168.20.27]:5665
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished reconnecting to endpoint 'icinga101.ct-srv.de' via host 'icinga101.ct-srv.de' and port '5665'
[2018-05-24 15:27:17 +0200] information/ApiListener: Requesting new certificate for this Icinga instance from endpoint 'icinga101.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Sending config updates for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished sending config file updates for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Syncing runtime objects to endpoint 'icinga101.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished syncing runtime objects to endpoint 'icinga101.ct-srv.de'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished sending runtime config updates for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Sending replay log for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished sending replay log for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Finished syncing endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:27:17 +0200] information/ApiListener: Applying config update from endpoint 'icinga101.ct-srv.de' of zone 'master'.
[2018-05-24 15:27:17 +0200] information/ConfigItem: Committing config item(s).
[2018-05-24 15:27:17 +0200] information/ConfigItem: Triggering Start signal for config items
[2018-05-24 15:27:17 +0200] information/ConfigItem: Activated all objects.
[2018-05-24 15:27:27 +0200] information/WorkQueue: #4 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-05-24 15:27:27 +0200] information/WorkQueue: #5 (ApiListener, SyncQueue) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);
[2018-05-24 15:27:27 +0200] information/WorkQueue: #9 (JsonRpcConnection, #1) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-05-24 15:27:27 +0200] information/WorkQueue: #8 (JsonRpcConnection, #0) items: 0, rate: 0.05/s (3/min 3/5min 3/15min);
[2018-05-24 15:29:15 +0200] warning/TlsStream: TLS stream was disconnected.
[2018-05-24 15:29:15 +0200] warning/JsonRpcConnection: API client disconnected for identity 'icinga101.ct-srv.de'
[2018-05-24 15:29:15 +0200] warning/ApiListener: Removing API client for endpoint 'icinga101.ct-srv.de'. 0 API clients left.
[2018-05-24 15:29:15 +0200] information/ApiListener: New client connection for identity 'icinga101.ct-srv.de' from [192.168.20.27]:54036
[2018-05-24 15:29:15 +0200] information/ApiListener: Requesting new certificate for this Icinga instance from endpoint 'icinga101.ct-srv.de'.
[2018-05-24 15:29:15 +0200] information/ApiListener: Applying config update from endpoint 'icinga101.ct-srv.de' of zone 'master'.
[2018-05-24 15:29:15 +0200] information/ApiListener: Sending config updates for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:29:15 +0200] information/ApiListener: Finished sending config file updates for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:29:15 +0200] information/ApiListener: Syncing runtime objects to endpoint 'icinga101.ct-srv.de'.
[2018-05-24 15:29:15 +0200] critical/ApiListener: Could not create object 'chat102.ct-srv.de!load!icinga101-1527165146-0':
[2018-05-24 15:29:15 +0200] critical/ApiListener: Configuration file '/var/lib/icinga2/api/packages/_api/chat102-1498141511-1/conf.d/downtimes/chat102.ct-srv.de!load!icinga101-1527165146-0.conf' already exists.
[2018-05-24 15:29:15 +0200] information/ApiListener: Finished syncing runtime objects to endpoint 'icinga101.ct-srv.de'.
[2018-05-24 15:29:15 +0200] information/ApiListener: Finished sending runtime config updates for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:29:15 +0200] information/ApiListener: Sending replay log for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:29:15 +0200] information/ApiListener: Finished sending replay log for endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:29:15 +0200] information/ApiListener: Finished syncing endpoint 'icinga101.ct-srv.de' in zone 'master'.
[2018-05-24 15:32:17 +0200] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
[2018-05-24 15:32:37 +0200] information/WorkQueue: #5 (ApiListener, SyncQueue) items: 0, rate: 0.0166667/s (1/min 2/5min 2/15min);
[2018-05-24 15:32:37 +0200] information/WorkQueue: #4 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-05-24 15:32:37 +0200] information/WorkQueue: #9 (JsonRpcConnection, #1) items: 0, rate: 0.1/s (6/min 23/5min 23/15min);
[2018-05-24 15:32:37 +0200] information/WorkQueue: #8 (JsonRpcConnection, #0) items: 0, rate: 0.1/s (6/min 16/5min 16/15min);
```
The zones.conf file from the master:

```
/*
 * Generated by Icinga 2 node setup commands
 * on 2018-05-18 10:31:03 +0200
 */

object Endpoint NodeName {
}

object Zone ZoneName {
	endpoints = [ NodeName ]
}

object Zone "global-templates" {
	global = true
}

object Zone "director-global" {
	global = true
}
```

The zones.conf file from the client:

```
/*
 * Generated by Icinga 2 node setup commands
 * on 2018-05-18 10:49:01 +0200
 */

object Endpoint "icinga101.ct-srv.de" {
	host = "icinga101.ct-srv.de"
	port = "5665"
}

object Zone "master" {
	endpoints = [ "icinga101.ct-srv.de" ]
}

object Zone "global-templates" {
	global = true
}

object Zone "director-global" {
	global = true
}

object Endpoint NodeName {
}

object Zone ZoneName {
	endpoints = [ NodeName ]
	parent = "master"
}
```

This is an example of an service object that should trigger a remote execution:

```
Object 'chat102.ct-srv.de!load' of type 'Service':
  % declared in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 61:1-61:21
  * __name = "chat102.ct-srv.de!load"
  * action_url = ""
  * check_command = "load"
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 63:2-63:23
  * check_interval = 300
  * check_period = ""
  * check_timeout = null
  * command_endpoint = "chat102.ct-srv.de"
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 67:2-67:39
  * display_name = "load"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "chat102.ct-srv.de"
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 64:2-64:32
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
  * name = "load"
  * notes = ""
  * notes_url = ""
  * package = "_etc"
  * retry_interval = 60
  * source_location
    * first_column = 1
    * first_line = 61
    * last_column = 21
    * last_line = 61
    * path = "/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf"
  * templates = [ "load", "satellite-service" ]
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 61:1-61:21
    % = modified in '/etc/icinga2/conf.d/satellite.conf', lines 22:1-22:36
  * type = "Service"
  * vars
    * backup_downtime = "02:00-03:00"
      % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 66:2-66:37
    * notification
      * mail
        % = modified in '/etc/icinga2/conf.d/satellite.conf', lines 23:3-25:3
        * groups = [ "icingaadmins" ]
  * volatile = false
  * zone = "chat102.ct-srv.de"
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 65:2-65:27
```

## Your Environment

* Version used (`r2.8.1-1`):
* Operating System and version: ubuntu 18.04
* Enabled features (`icinga2 feature list`): api checker command debuglog ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`):

```
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga101.ct-srv.de
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'phone' (in /etc/icinga2/conf.d/notifications.conf: 44:1-44:37) for type 'Notification' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 2 FileLoggers.
information/ConfigItem: Instantiated 80 Notifications.
information/ConfigItem: Instantiated 5 NotificationCommands.
information/ConfigItem: Instantiated 209 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3 Hosts.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 37 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

master:

```
Object 'chat102.ct-srv.de' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 1:0-1:34
  * __name = "chat102.ct-srv.de"
  * host = "chat102.ct-srv.de"
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 3:2-3:27
  * log_duration = 86400
  * name = "chat102.ct-srv.de"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 4:2-4:14
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 34
    * last_line = 1
    * path = "/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf"
  * templates = [ "chat102.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 1:0-1:34
  * type = "Endpoint"
  * zone = "chat102.ct-srv.de"
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 2:2-2:27

Object 'icinga101.ct-srv.de' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 6:1-6:24
  * __name = "icinga101.ct-srv.de"
  * host = ""
  * log_duration = 86400
  * name = "icinga101.ct-srv.de"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 6
    * last_column = 24
    * last_line = 6
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "icinga101.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.conf', lines 6:1-6:24
  * type = "Endpoint"
  * zone = ""
```

```
Object 'chat102.ct-srv.de' of type 'Zone':
  % declared in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 7:1-7:31
  * __name = "chat102.ct-srv.de"
  * endpoints = [ "chat102.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 8:2-8:36
  * global = false
  * name = "chat102.ct-srv.de"
  * package = "_etc"
  * parent = "icinga101.ct-srv.de"
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 9:2-9:31
  * source_location
    * first_column = 1
    * first_line = 7
    * last_column = 31
    * last_line = 7
    * path = "/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf"
  * templates = [ "chat102.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 7:1-7:31
  * type = "Zone"
  * zone = "chat102.ct-srv.de"
    % = modified in '/etc/icinga2/zones.d/master/chat102.ct-srv.de.conf', lines 10:2-10:27

Object 'director-global' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 17:1-17:29
  * __name = "director-global"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 18:2-18:14
  * name = "director-global"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 17
    * last_column = 29
    * last_line = 17
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "director-global" ]
    % = modified in '/etc/icinga2/zones.conf', lines 17:1-17:29
  * type = "Zone"
  * zone = ""

Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 13:1-13:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 14:2-14:14
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 13
    * last_column = 30
    * last_line = 13
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 13:1-13:30
  * type = "Zone"
  * zone = ""

Object 'icinga101.ct-srv.de' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 9:1-9:20
  * __name = "icinga101.ct-srv.de"
  * endpoints = [ "icinga101.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.conf', lines 10:2-10:25
  * global = false
  * name = "icinga101.ct-srv.de"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 9
    * last_column = 20
    * last_line = 9
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "icinga101.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.conf', lines 9:1-9:20
  * type = "Zone"
  * zone = ""
```

client:

```
Object 'chat102.ct-srv.de' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 23:1-23:24
  * __name = "chat102.ct-srv.de"
  * host = ""
  * log_duration = 86400
  * name = "chat102.ct-srv.de"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 23
    * last_column = 24
    * last_line = 23
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "chat102.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.conf', lines 23:1-23:24
  * type = "Endpoint"
  * zone = ""

Object 'icinga101.ct-srv.de' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 6:1-6:37
  * __name = "icinga101.ct-srv.de"
  * host = "icinga101.ct-srv.de"
    % = modified in '/etc/icinga2/zones.conf', lines 7:2-7:29
  * log_duration = 86400
  * name = "icinga101.ct-srv.de"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 8:2-8:14
  * source_location
    * first_column = 1
    * first_line = 6
    * last_column = 37
    * last_line = 6
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "icinga101.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.conf', lines 6:1-6:37
  * type = "Endpoint"
  * zone = ""
```

```
Object 'chat102.ct-srv.de' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 26:1-26:20
  * __name = "chat102.ct-srv.de"
  * endpoints = [ "chat102.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.conf', lines 27:2-27:25
  * global = false
  * name = "chat102.ct-srv.de"
  * package = "_etc"
  * parent = "master"
    % = modified in '/etc/icinga2/zones.conf', lines 28:2-28:18
  * source_location
    * first_column = 1
    * first_line = 26
    * last_column = 20
    * last_line = 26
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "chat102.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.conf', lines 26:1-26:20
  * type = "Zone"
  * zone = ""

Object 'director-global' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 19:1-19:29
  * __name = "director-global"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 20:2-20:14
  * name = "director-global"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 19
    * last_column = 29
    * last_line = 19
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "director-global" ]
    % = modified in '/etc/icinga2/zones.conf', lines 19:1-19:29
  * type = "Zone"
  * zone = ""

Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 15:1-15:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 16:2-16:14
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 15
    * last_column = 30
    * last_line = 15
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 15:1-15:30
  * type = "Zone"
  * zone = ""

Object 'master' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 11:1-11:20
  * __name = "master"
  * endpoints = [ "icinga101.ct-srv.de" ]
    % = modified in '/etc/icinga2/zones.conf', lines 12:2-12:38
  * global = false
  * name = "master"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 11
    * last_column = 20
    * last_line = 11
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "master" ]
    % = modified in '/etc/icinga2/zones.conf', lines 11:1-11:20
  * type = "Zone"
  * zone = ""
```

**Comment by mcktr** [comment] 2018-05-24 18:45
I really appreciate that you included all the details, this helps a lot for tracking down the issue. :+1:

Please ensure that you commented out the `conf.d` directory inside the `icinga2.conf` on your client. If the conf.d directory is enabled the client reads the local objects and while receiving the configuration from the master, the client will ran into problems like this, because an object with an identical name already exist.  

```
[2018-05-24 15:29:15 +0200] critical/ApiListener: Could not create object 'chat102.ct-srv.de!load!icinga101-1527165146-0':
[2018-05-24 15:29:15 +0200] critical/ApiListener: Configuration file '/var/lib/icinga2/api/packages/_api/chat102-1498141511-1/conf.d/downtimes/chat102.ct-srv.de!load!icinga101-1527165146-0.conf' already exists.
```

I am closing here, since I believe this is a configuration issue and not a bug. Please join the community channels like https://monitoring-portal.org/ to get help on configuration questions.

Kind regards
Michael

**Closed by mcktr** 2018-05-24 18:45 UTC

**Comment by djschilling** [comment] 2018-05-24 20:51
@mcktr Thanks for your answer.

Sadly the problem still remains because i already had deleted the include of `conf.d`.
I created a new topic in the monitoring portal, with updated information: https://monitoring-portal.org/t/commands-are-not-executed-on-client/2581

Maybe you can have a look over there.
