### ISSUE TITLE
Hosts on satellite/cluster not visible

### ISSUE THREAD

**Issue by JanaFischinger** [Icinga/icinga2#7577] opened 2019-10-16 16:28 UTC
i created a satellite endpoint with director.
When i configure hosts normal way they are visible in icingaweb2.
But when i change the cluster zone the host(s) are not longer listed. but still reporting perfdata (wich lower latency) so will be execured at satellite

**Comment by dnsmichi** [comment] 2019-10-17 09:50
Hi,

I'm not sure what exactly is going on. Please always fill in the issue templates and add more details about your setup and how to reproduce the problem you are seeing - https://github.com/Icinga/icinga2/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Cheers,
Michael

**Comment by JanaFischinger** [comment] 2019-10-17 12:51
## Describe the bug

Host(s) are missing which are assigned to satellite.
Same issue like in this video:
https://www.youtube.com/watch?v=V5o-LHGQEB4

## To Reproduce
i used this following as base:
https://www.youtube.com/watch?v=XsmdsNXgCxE

1. Edited zones.conf via ssh and added the new endpoint as zone on master and endpoint.
2. Same on Endpoint edited zones.conf and added the master.
3. In director used kickstart to import endpoint and zone.
4. created a new host with same name as satellite, custer-zone is endpoint zone and icinga2 agent is enabled.
5. deployed but new host is not visible in icingaweb2
6. same with additional hosts, when i change cluster zone to master then host(s) are visible. but then checks running on master and not on satellite.

## Expected behavior

Show host in icingaweb2

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga2 r2.11.0-1
* Debian 10
* Enabled features: api checker ido-mysql mainlog notification
* Icinga Web 2 2.6.2 with director and monitoring module
* Config validation (information/cli: Finished validating the configuration file(s).)

**Comment by JanaFischinger** [comment] 2019-10-17 19:01
Hi Michael

I found the problem but i dont know why this happen:
on master1 an folder with endpoint name sat1 exists in /var/lib/icinga2/api/zones/
but on master2 the folder does not exist and thats why icinga2 dont know this hosts/services.

> object Endpoint "master1" {
>         host = "192.168.0.1"
> }
> object Endpoint "master2" {
>         host = "192.168.0.2"
> }
> 
> object Zone "master" {
>         endpoints = [ "master1","master2" ]
> }
> 
> object Zone "global-templates" {
>         global = true
> }
> 
> object Zone "director-global" {
>         global = true
> }
> 
> object Endpoint "sat1" {
> }
> object Zone "sat1" {
>   endpoints = [ "sat1" ]
>   parent = "master"
> }
config on both masters are the same.

**Comment by dnsmichi** [comment] 2019-10-18 12:42
Mh please don't edit topics and replies, no-one can follow up on this later. Rather create another reply.

Try purging `/var/lib/icinga2/api/zones/*` manually on both nodes, restart them both and re-deploy again. To me, this more looks like a configuration issue, and for future topics, I'd suggest moving to https://community.icinga.com reaching a wider audience.

**Comment by dnsmichi** [comment] 2019-10-22 07:24
I'm closing this in favor of https://community.icinga.com/t/master-master-cluster-with-satellite-not-working/2537

**Closed by dnsmichi** 2019-10-22 07:24 UTC
Labels: needs-feedback
