### ISSUE TITLE
Icinga 2 Config reload/validation crashes (sometimes) with segfault on RHEL 7.5

### ISSUE THREAD

**Issue by Clasko** [Icinga/icinga2#6331] opened 2018-05-24 08:19 UTC
## Expected Behavior
Icinga 2 Config reload/validation doesn't crash with "Segmentation fault"

## Current Behavior
Icinga 2 Config reload/validation crashes with "Segmentation fault" every 2nd run after Upgrade from RHEL 7.4 to 7.5

[root@icinga2-1 ~]# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.8.4-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga2-1.domain.com
Segmentation fault

/var/log/messages:
`May 24 09:32:36 icinga2 kernel: icinga2[6739]: segfault at 7fe01f371000 ip 00007fe01ef22d60 sp 00007fe018569b80 error 4 in libcrypto.so.1.0.2k[7fe01eea9000+234000]`

## Possible Solution
It looks like openssl(-libs) Version 1:1.0.2k-12.el7 causes the problem. Downgrade to 1:1.0.2k-8.el7 seems to fix the issue.

## Steps to Reproduce (for bugs)
Maybe not easy. The issue only occurs on our Prod HA Cluster + Satellites. No issue on our small Test enviroment.

1. Upgrade von RHEL 7.4 to 7.5
2. icinga2 daemon -C

## Your Environment
* Version used (`icinga2 --version`):

icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.5 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-862.2.3.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Operating System and version: RHEL 7.5
* Enabled features (`icinga2 feature list`): api checker command ido-mysql livestatus mainlog notification perfdata
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
[root@icinga2-1 ~]# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.8.4-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga2-1.domain.com
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 6 Zones.
information/ConfigItem: Instantiated 8 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 3 ApiUsers.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 6 UserGroups.
information/ConfigItem: Instantiated 8 NotificationCommands.
information/ConfigItem: Instantiated 15244 Notifications.
information/ConfigItem: Instantiated 268 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 887 Hosts.
information/ConfigItem: Instantiated 137 HostGroups.
information/ConfigItem: Instantiated 6358 Dependencies.
information/ConfigItem: Instantiated 597 Downtimes.
information/ConfigItem: Instantiated 12 TimePeriods.
information/ConfigItem: Instantiated 23 Users.
information/ConfigItem: Instantiated 34 Comments.
information/ConfigItem: Instantiated 28 ServiceGroups.
information/ConfigItem: Instantiated 10882 Services.
information/ConfigItem: Instantiated 345 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 2 LivestatusListeners.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

object Zone "global-templates" {
        global = true
}

object Zone "config-ha-master" {
        endpoints = [ "icinga2-1.domain.com", "icinga2-2.domain.com" ]
}

object Zone "customer1-satellite" {
        endpoints = [ "sat1.customer1.com", "sat2.customer1.com" ]
        parent = "config-ha-master"
}

object Zone "customer2-satellite" {
        endpoints = [ "sat1.customer2.com", "sat2.customer2.com" ]
        parent = "config-ha-master"
}

object Zone "customer3-satellite" {
        endpoints = [ "sat1.customer3.com" ]
        parent = "config-ha-master"
}

object Zone "customer4-satellite" {
        endpoints = [ "sat1.customer4.com" ]
        parent = "config-ha-master"
}

object Endpoint "icinga2-1.domain.com" {
        host = "icinga2-1.domain.com"
}

object Endpoint "icinga2-2.domain.com" {
        host = "icinga2-2.domain.com"
}

object Endpoint "sat1.customer1.com" {
}

object Endpoint "sat2.customer1.com" {
}

object Endpoint "sat1.customer2.com" {
}

object Endpoint "sat1.customer3.com" {
}

object Endpoint "sat1.customer4.com" {
}

**Comment by dnsmichi** [comment] 2018-05-24 08:28
You can test the snapshot packages, that's already been reported with #6279 and fixed.

**Comment by dnsmichi** [comment] 2018-05-24 08:31
Duplicate of #6279

**Comment by Clasko** [comment] 2018-05-24 08:33
Sound good, i have to clearify if i can install the snapshot packages in production. Otherwise we will wait for the next stable release. :) We can life with the downgraded openssl version for now.

Thanks for the extremly fast response!

**Comment by dnsmichi** [comment] 2018-05-28 15:31
Would appreciate just a small test on one of your hosts, maybe with a VM clone to just see whether snapshot packages work or not.

**Comment by Clasko** [comment] 2018-05-29 09:53
Not that easy (and/or fast) with an active Change Management but i'm on it.

**Comment by Clasko** [comment] 2018-05-31 13:07
No issue with Snapshot Packages. Looks good!

**Comment by dnsmichi** [comment] 2018-06-01 11:45
Top, thank you ❤️

**Closed** 2018-06-01 11:46 UTC
Labels: Crash, duplicate
