### ISSUE TITLE
[bug] icinga2 api user cli 'caught unhandled exception' crash (boost::bad_any_cast)

### ISSUE THREAD

**Issue by bbczeuz** [Icinga/icinga2#6190] opened 2018-03-29 15:42 UTC
## Setup
- current Debian9 VM (x86_64, 2 CPU, 2GiB RAM)
- icinga2 from ```deb https://packages.icinga.com/debian icinga-stretch main```
- same for icingaweb2
- Postgresql as DB for icinga and icingaweb2
```
# uname -a
Linux icinga2 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-1)
...
# icinga2 feature list
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-pgsql mainlog notification
```

## Expected Behavior
Copied from the documentation at https://www.icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#creating-apiusers
```
$ icinga2 api user --user icingaweb2 --password icinga
object ApiUser "icingaweb2" {
  password_hash ="$5$d5f1a17ea308acb6$9e9fd5d24a9373a16e8811765cc5a5939687faf9ef8ed496db6e7f1d0ae9b2a9"
  // client_cn = ""

  permissions = [ "*" ]
}
```

## Current Behavior
```
$ icinga2 api user --user icingaweb2 --password icinga
critical/Application: Error: boost::bad_any_cast: failed conversion using boost::any_cast


Additional information is available in '/var/log/icinga2/crash/report.1522337367.284183'

Aborted
```

or:
```
# gdb /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2...(no debugging symbols found)...done.
(gdb) run api user --user icingaweb2 --password icinga
Starting program: /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 api user --user icingaweb2 --password icinga
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff14a2700 (LWP 32149)]
[New Thread 0x7ffff0ca1700 (LWP 32150)]
[New Thread 0x7fffebfff700 (LWP 32151)]
[New Thread 0x7fffeb7fe700 (LWP 32152)]
[New Thread 0x7fffeaffd700 (LWP 32153)]
[New Thread 0x7fffea7fc700 (LWP 32154)]
[Thread 0x7fffea7fc700 (LWP 32154) exited]
[Thread 0x7fffeaffd700 (LWP 32153) exited]
[Thread 0x7fffeb7fe700 (LWP 32152) exited]
[Thread 0x7fffebfff700 (LWP 32151) exited]
[Thread 0x7ffff0ca1700 (LWP 32150) exited]
[Thread 0x7ffff14a2700 (LWP 32149) exited]
process 32145 is executing new program: /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7fd5700 (LWP 32161)]
[New Thread 0x7ffff7f94700 (LWP 32162)]
[New Thread 0x7ffff7f53700 (LWP 32163)]
[New Thread 0x7ffff7f12700 (LWP 32164)]
[New Thread 0x7ffff7ed1700 (LWP 32165)]
[New Thread 0x7ffff7e90700 (LWP 32166)]
critical/Application: Error: boost::bad_any_cast: failed conversion using boost::any_cast


Additional information is available in '/var/log/icinga2/crash/report.1522337499.575644'


Thread 1 "icinga2" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) back
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff3db742a in __GI_abort () at abort.c:89
#2  0x00007ffff5ff3a0d in icinga::Application::ExceptionHandler() () from /usr/lib/x86_64-linux-gnu/icinga2/libbase.so.2.8.2
#3  0x00007ffff46cc066 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff46cc0b1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff46cc2c9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff5f9628f in __cxa_throw () from /usr/lib/x86_64-linux-gnu/icinga2/libbase.so.2.8.2
#7  0x00007ffff695d45e in ?? () from /usr/lib/x86_64-linux-gnu/icinga2/libcli.so.2.8.2
#8  0x00007ffff69b3a3b in ?? () from /usr/lib/x86_64-linux-gnu/icinga2/libcli.so.2.8.2
#9  0x00007ffff6979a32 in ?? () from /usr/lib/x86_64-linux-gnu/icinga2/libcli.so.2.8.2
#10 0x0000555555561b95 in ?? ()
#11 0x000055555555f52b in ?? ()
#12 0x00007ffff3da32e1 in __libc_start_main (main=0x55555555f4e0, argc=8, argv=0x7fffffffec78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffec68) at ../csu/libc-start.c:291
#13 0x000055555555f6ca in ?? ()
```

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
0. Install icinga2 from the Repo. No config changes except enabling the api-feature
1. ```icinga2 api setup```
2. ```systemctl restart icinga2```
3. see above

## Context
Somehow the API interface is broken. With curl I always get error 401.
```
# cat /etc/icinga2/conf.d/api-users.conf 
/**
 * The APIUser objects are used for authentication against the API.
 */
object ApiUser "root" {
  password = "icinga"
  permissions = [ "*" ]
}

# curl -k -s -u root:icinga 'https://root@localhost:5665/v1' 
<h1>Unauthorized. Please check your user credentials.</h1>
```

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by mcktr** [comment] 2018-03-29 19:40
Hi,

thanks for reporting. This is a duplicate of #6178.

Best regards
Michael

**Closed by mcktr** 2018-03-29 19:40 UTC
Labels: duplicate
