### ISSUE TITLE
Change order of configuration object loading

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icinga2#5769] opened 2017-11-16 09:31 UTC
Scenario:
* Icinga 2 (Config)master with objects from files (e.g. host-template "generic-host" via "/etc/icinga2/zones.d/global-templates/templates.conf") and autogenerated objects via Icinga 2 API (e.g. hosts with template "generic-host")
* New Icinga 2 satellite from scratch

Problem:
The new Icinga 2 satellite retrieves the whole configuration (file- and api-objects) from the (config)master and doesn't know about the objects from files (e.g. "generic-host"-template) before loading the api-objects. So the restart fails:

```
[2017-11-10 10:38:43 +0000] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/global-templates//_etc/templates.conf
[2017-11-10 10:38:43 +0000] information/ApiListener: Restarting after configuration change.
[2017-11-10 10:38:43 +0000] information/ApiListener: Restarting after configuration change.
[2017-11-10 10:38:43 +0000] information/ConfigItem: Committing config item(s).
[2017-11-10 10:38:43 +0000] critical/config: Error: Import references unknown template: 'generic-host'
...
[2017-11-10 10:38:45 +0000] information/Application: Got reload command: Starting new instance.
[2017-11-10 10:38:45 +0000] information/Application: Received request to shut down.
[2017-11-10 10:38:46 +0000] information/Application: Shutting down...
[2017-11-10 10:38:46 +0000] information/CheckerComponent: Checker stopped.
[2017-11-10 10:38:46 +0000] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
[2017-11-10 10:38:46 +0000] information/IcingaApplication: Icinga has shut down.
```

A manual restart of Icinga 2 after the problem works.

## Environment
* Version used (`icinga2 --version`): 2.6.3
* Operating System and version: CentOS 7.4

**Comment by dnsmichi** [comment] 2017-11-16 16:25
This needs intensive tests if the sync order (filesync vs config object sync) is changed for this issue.

**Comment by dnsmichi** [comment] 2017-12-04 14:50
I think the problem is related to a 2 way sync here.

- The configuration objects are created via REST API at runtime, and are immediately synced. The satellite does not have any zones.d config sync files at this time. This stops the reload.
- Once the global-templates zones.d files are synced, this would be fine. But still, at this point there's no runtime creation event anymore. You'll never reach this point in time here.

Possible workaround: Deploy the global templates beforehand and ensure they're live, before actually deploying runtime objects via API.

This likely affects the entire config sync and staging ideas we had with #4354 too.

**Comment by dnsmichi** [comment] 2018-01-18 11:25
This has been tested by 3 different people now, and neither of them is able to reproduce the issue with the currently supported 2.8 tree. Closing this as invalid.

**Closed** 2018-04-17 19:36 UTC
Labels: Cluster, Configuration, invalid
