### ISSUE TITLE
Performance data don't show thresholds with negative numbers

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icinga2#9194] opened 2022-01-26 23:35 UTC
## Describe the bug
I want to define a threshold from -100 to 4000.
It works inside the check but the rendering in icingadb-web is incomplete

performance data is:
`| humidity=78 pressure=1027 temp=2.04;-100.0:4000;-100.0:4000 wind_speed=1.79`

## To Reproduce
set up a check with negative values for critical and warning in perf data

## Expected behavior
should render 

## Screenshots
works in the old monitoring module
<img width="177" alt="2022-01-27 00_28_28-CMD check_weather __ icinga-master __ Services __ Icinga Web" src="https://user-images.githubusercontent.com/29682206/151264609-a115afe6-0856-4740-849b-6d2e034cdd38.png">

doesnt work in icingadb-web
<img width="561" alt="2022-01-27 00_28_49-Service __ Icinga Web" src="https://user-images.githubusercontent.com/29682206/151264617-77293b79-cdb7-4b17-9e3f-11c2853acf5a.png">

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0-rc2
* Icinga Web 2 version (System - About): 2.9.5
* Web browser: Chrome
* Icinga 2 version (`icinga2 --version`): 2.13.2
* Icinga DB version (`icingadb --version`): rc2
* PHP version used (`php --version`): 7.4
* Server operating system and version: Ubuntu 20.04

**Comment by nilmerg** [comment] 2022-01-27 08:18
The column `normalized_performance_data` doesn't contain *any* threshold, be it positive or negative. The column `performance_data` on the other hand has them included, so they do exist.

**Comment by julianbrost** [comment] 2022-01-27 08:53
This is actually not about negative numbers but rather about ranges in thresholds, so this is actually a duplicate of #9038

```
object Host "github-9194" {
	check_command = "dummy"
	vars.dummy_text = "Test | test1=42;-100.0:4000;-100.0:4000 test2=23;100.0:4000;100.0:4000 test3=2.04;-100.0;-100.0"
}
```

![20220127_09h51m13s_grim](https://user-images.githubusercontent.com/18552/151324695-28b390e4-f848-4397-a7d3-be216284de31.png)

**Closed by julianbrost** 2022-01-27 08:53 UTC
Labels: bug, area/icingadb
