### ISSUE TITLE
Master-master HA configuration breaks on "Zone master" recovery

### ISSUE THREAD

**Issue by dmitriy-terzeman** [Icinga/icinga2#7581] opened 2019-10-18 17:07 UTC
## Describe the bug
Found a bug in Icinga2 cluster failover mechanism, issue shows up ONLY when primary master get recovered after failure/downtime.
With current implementation when primary master gets recovered, it becomes zone master automatically, while IDO feature still stays on secondary master, secondary master don't send any data to database because its not zone master anymore, but it(secondary master) still holds IDO feature on its endpoint.

When this issue takes place we losing data in database and can see Late Check results in our Icingaweb2
https://example.com/icingaweb2/dashboard?pane=Overdue

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Go to primary master and execute: killall /usr/lib64/icinga2/sbin/icinga2
2. Wait for 5 minutes and ensure that everything covered by secondary master
3. Go to https://example.com/icingaweb2/dashboard?pane=Overdue and ensure that there is no Late Results
4. Go to primary master and execute: systemctl start icinga2
5. Wait for 5 minutes to ensure that recovery failover triggered again
6. Go to https://example.com/icingaweb2/dashboard?pane=Overdue and ensure that Late Results showed up

## Expected behavior
Expected that it will be no Late check results in Reproduce step 6.

## Your Environment
My /etc/icinga2/zones.conf (edited fqdns):
object Endpoint "icinga-master1" {
	host = "icinga-master1"
	log_duration = 0
}

object Endpoint "icinga-master2" {
	host = "icinga-master2"
	log_duration = 0
}

object Zone "master" {
 endpoints = [ "icinga-master1", "icinga-master2" ]
}

object Zone "global-templates" {
 global = true
}

object Zone "director-global" {
 global = true
}

object Endpoint "icinga-satellite1" {
	log_duration = 0
}

object Endpoint "icinga-satellite2" {
	log_duration = 0
}

object Zone "satellite-a" {
 endpoints = [ "icinga-satellite2", "icinga-satellite2" ]
 parent = "master"
}

all clients configured through Icinga2 Director module.
Working environment:

 Service Checks | Per Host
 -- | --
124980 | 49.93
124980 | 49.93

Check Performance | Checks | Latency | Execution time
-- | -- | -- | --
Host Checks | 2503 | 0.003s | 0.006s
Service Checks | 124980 | 0.001s | 0.000s

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version
2.7.1
Git commit: b0bf9c4b0637f6113adb788e78c2bcf619225dd8
PHP Version: 7.1.31

icingacli module list
MODULE         VERSION   STATE     DESCRIPTION
director       1.6.2     enabled   Director - Config tool for Icinga 2
fileshipper    1.1.0     enabled   Fileshipper for Icinga Director
incubator      v0.3.0    enabled   Incubator provides bleeding-edge libraries
ipl            v0.3.0    enabled   The Icinga PHP library
monitoring     2.7.1     enabled   Icinga monitoring module
reactbundle    v0.6.0    enabled   ReactPHP-based 3rd party libraries

* Web browser used:
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.0-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.21.3.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
* PHP version used (`php --version`):
PHP 7.1.31 (cli) (built: Jul 31 2019 09:59:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
* Server operating system and version:

## Additional context
I did a deep investigation before making this bug report, please go through all topics because it could be important.

### Restore cluster
When issue takes effect you can very easily restore cluster work with following steps:

1. Go to secondary master and execute: killall /usr/lib64/icinga2/sbin/icinga2 
2. Wait until IDO DB feature will switch to primary master (can be verified in Icingaweb2: https://example.com/icingaweb2/monitoring/health/info)
3. Go to secondary master and execute: systemctl start icinga2
4. Go to https://example.com/icingaweb2/dashboard?pane=Overdue and ensure that there is no Late Results and cluster functional again

### Research of root cause
I've tried to find root cause of the problem by my self, during my investigation&research i found that for correct work of cluster current "Zone master" must have DB IDO feature enabled on its endpoint, also i've got through some technical concepts provided in official documentation:
- Election of "Zone master" inside of zone: https://icinga.com/docs/icinga2/latest/doc/19-technical-concepts/#high-availability-object-authority
- Election of DB IDO master: https://icinga.com/docs/icinga2/latest/doc/19-technical-concepts/#high-availability-db-ido
This 2 Elections works in a different way:

a) Zone master election is sticky to endpoint names:
object Zone "master" {
 endpoints = [ "icinga-master1", "icinga-master2" ]
}
in this case Zone icinga-master2 will always provide leadership to icinga-master1 once it will become online.

b) DB IDO master election is sticky to status table in database:
if table was not updated by current master that set in database table, then execute failover procedure. In this situation icinga-master1 can't get it's DB IDO feature back until icinga-master1 holds it.

When cluster is healthy and operates normally we can see those records in the logs /var/log/icinga2/icinga2.log on side of current "Zone master":
[2019-10-18 03:43:20 -0700] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 612, rate: 4155.95/s (249357/min 1263219/5min 3790261/15min);
[2019-10-18 03:43:30 -0700] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 276, rate: 4202.42/s (252145/min 1263109/5min 3790918/15min);
[2019-10-18 03:43:40 -0700] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 285, rate: 4167.82/s (250069/min 1263585/5min 3790921/15min);
[2019-10-18 03:43:50 -0700] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 232, rate: 4206.33/s (252380/min 1262812/5min 3791169/15min);
[2019-10-18 03:44:00 -0700] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 280, rate: 4183.37/s (251002/min 1262486/5min 3791052/15min);
[2019-10-18 03:44:10 -0700] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 248, rate: 4166.87/s (250012/min 1261944/5min 3791101/15min);
[2019-10-18 03:44:20 -0700] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 221, rate: 4216.73/s (253004/min 1262491/5min 3790999/15min);
[2019-10-18 03:44:30 -0700] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 292, rate: 4171.67/s (250300/min 1262699/5min 3791050/15min);

When we facing this issue with HA you can see that WorkQueue worker with IdoMysqlConnection method not send any data to database, as supposed to be. Unfortunately i'm not strong in C++, so i'm not able to dive deeper and search for error in the code. 

### Workaround
I found a configuration workaround for cluster auto-recovery, it might be not a 100% working solution for all error handling, etc. but actually it works for my test cluster under load with 2k clients, i've tested it with a different failure situations for 6 days and for now it works like a charm.

To implement this workaround you need to force "Zone master" e.g. icinga-master1 ( **it's very importent** ) to take over IDO DB feature once it will become online. To make it happen i disabled enable_ha feature only on "Zone master" side.

Config of /etc/icinga2/features-available/ido-mysql.conf on icinga-master1:
object IdoMysqlConnection "ido-mysql" {
  user = "icinga"
  password = "password"
  host = "database.example.com"
  database = "icinga"
  enable_ha = false
  failover_timeout = 60
}

Config of /etc/icinga2/features-available/ido-mysql.conf on icinga-master2:
object IdoMysqlConnection "ido-mysql" {
  user = "icinga"
  password = "password"
  host = "database.example.com"
  database = "icinga"
  enable_ha = true
  failover_timeout = 60
}

When primary master recovered, it instantly updates table in the database "icinga_programstatus", that time secondary master see that icinga-master1 updated record in this table and stops writing to database, in logs on icinga-master2 i see the following:
[2019-10-18 04:40:33 -0700] information/IdoMysqlConnection: Last update by endpoint 'icinga-master1' was 11.7505s ago (< failover timeout of 60s). Retrying.

While this solution is working it still can cause some unexpected errors or crashes that i might be missed or didn't cached. And correct cluster work expects that you will enable HA feature for DB IDO on both masters so it would be nice if it could be fixed.

Please let me know if you need some additional info or help from my side to debug/fix it.

P.S. during my tests i also tried to catch any errors in HA functionality with satellites, but didn't found any issues, works like a charm, issue reproduces only on master nodes with active DB IDO features.

With best regards,
Dmitriy.

**Comment by dnsmichi** [comment] 2019-10-21 14:20
The zone master is not necessarily the one where the IDO feature is resumed. The object authority is calculated independent from that, and also the failover mechanism for the IDO feature uses the database programstatus table as quorum in the middle. 

Whenever check results arrive, they are shared between the two instances. The endpoint which currently has the IDO feature enabled, will write to the backend and populate the data. Your analysis sounds more like as if actual check results are missing during the failover period. Do you actually see them on both ends, e.g. via API event streams?

**Comment by dmitriy-terzeman** [comment] 2019-10-21 14:47
Hello Michael,

>The endpoint which currently has the IDO feature enabled, will write to the backend and populate the data.
Yes, it should be independent from Zone master according to your documentation , but during my investigation described in "Research of root cause" chapter, icinga-master2 continue updating programstatus, but not send any data to MySQL(database located on separate server), it stops sending data to only MySQL once icinga-master1 cluster shows up e.g. with my tests i shut down icinga-master1 for an hour, it worked perfectly on icinga-master2, no late check results, all works like a charm, once i start daemon on icinga-master1 it instantly becomes a zone master(could be tracked in debug.log), and icinga-master2 stop writes of check results to MySQL, while continue updating programstatus table.
I left cluster in this state for a night and it didn't recovered during this time.

>Your analysis sounds more like as if actual check results are missing during the failover period
Not really, they are missing only if i recover my primary master, and until i will switch IDO DB feature on it from secondary master.

I didn't tried to get the data via API, will try to catch it, is there any suggested calls for better debug?

Please let me know if something additional required from my side.

With best regards,
Dmitriy.

**Comment by dnsmichi** [comment] 2019-10-21 15:33
> icinga-master2 continue updating programstatus, but not send any data to MySQL(database located on separate server)

Extract these queries from the debug log please.

**Comment by dmitriy-terzeman** [comment] 2019-10-21 20:05
Sorry for hard readable queries
To minimize amount of possible output here i'll provide several requests with cutted output, hope it will be more readable for analyze.

During this snapshot i started icinga2 daemon on primary master at Mon Oct 21 12:15:24 MST 2019 with command:
```
[root@i2-m1 icinga2]# systemctl start icinga2 && date
Mon Oct 21 12:15:24 MST 2019
```

On secondary master:
```
[root@i2-m2 icinga2]# grep '2019-10-21 12:13' -A999999 /var/log/icinga2/debug.log | grep 'IdoMysqlConnection: Query: UPDATE' | awk -F'SET' '{print $1}' | grep '2019-10-21 12:16' -B999999 | wc -l
9486
```
```
[root@i2-m2 icinga2]# grep '2019-10-21 12:17' -A999999 /var/log/icinga2/debug.log | grep 'IdoMysqlConnection: Query: UPDATE' | awk -F'SET' '{print $1}' | grep '2019-10-21 12:40' -B999999 | wc -l
144
```
Following 2 queries can show you amount of messages related to mysql, before and after restoring my primary master.

Here is more detailed view on filtered messages, i've cut output to make it readable in git comments. Here from `tail` we can see that secondary master only updated icinga_programstatus for last 4 minutes. No other updates:

```
[root@i2-m2 icinga2]# grep '2019-10-21 12:17' -A999999 /var/log/icinga2/debug.log | grep 'IdoMysqlConnection: Query: UPDATE' | awk -F'SET' '{print $1}' | grep '2019-10-21 12:40' -B999999 | tail -n 30
```
```
[2019-10-21 12:36:02 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:36:12 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:36:22 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:36:32 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:36:42 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:36:52 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:37:02 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:37:12 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:37:22 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:37:32 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:37:42 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:37:52 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:38:02 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:38:12 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:38:22 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:38:32 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:38:42 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:38:52 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:39:02 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:39:12 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:39:22 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:39:32 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:39:42 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:39:52 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:40:02 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:40:12 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:40:22 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:40:32 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:40:42 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
[2019-10-21 12:40:52 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
```

In next query i'm excluding messages with update of icinga_programstatus, to see what else is IdoMysqlConnection worker is doing:
```
[root@i2-m2 icinga2]# grep '2019-10-21 12:13' -A999999 /var/log/icinga2/debug.log | grep 'IdoMysqlConnection: Query: UPDATE' | awk -F'SET' '{print $1}' | grep '2019-10-21 12:40' -B999999 | grep -v 'UPDATE icinga_programstatus' | tail -n 30
```
```
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:25 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus
[2019-10-21 12:15:34 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_endpointstatus
```
Here you could see that last update to icinga_servicestatus was at 2019-10-21 12:15:34, after ~10 seconds when my primary master showed up.

I also collected 33MB of debug logs for this period from my secondary master, can share with it for deeper analytics if you would tell me how better to resend it to you.

With best regards,
Dmitriy

**Comment by dmitriy-terzeman** [comment] 2019-10-21 20:28
Here some start-up logs from primary master on `ido` query
```
[root@i2-m1 icinga2]# grep '2019-10-21 12:15:24' -A999999 /var/log/icinga2/debug.log | grep -i ido | head -n 20
```
```
[2019-10-21 12:15:24 -0700] information/DbConnection: 'ido-mysql' started.
[2019-10-21 12:15:24 -0700] information/IdoMysqlConnection: 'ido-mysql' resumed.
[2019-10-21 12:15:24 -0700] notice/WorkQueue: Spawning WorkQueue threads for 'IdoMysqlConnection, ido-mysql'
[2019-10-21 12:15:24 -0700] information/DbConnection: Resuming IDO connection: ido-mysql
[2019-10-21 12:15:24 -0700] debug/IdoMysqlConnection: Reconnect: Clearing ID cache.
[2019-10-21 12:15:24 -0700] notice/IdoMysqlConnection: Reconnect: 'ido-mysql' is now connected to database 'icinga'.
[2019-10-21 12:15:24 -0700] debug/IdoMysqlConnection: Query: SELECT @@global.max_allowed_packet AS max_allowed_packet
[2019-10-21 12:15:24 -0700] debug/IdoMysqlConnection: Query: SELECT version FROM icinga_dbversion WHERE name='idoutils'
[2019-10-21 12:15:24 -0700] debug/IdoMysqlConnection: Query: SELECT instance_id FROM icinga_instances WHERE instance_name = 'default'
[2019-10-21 12:15:24 -0700] debug/IdoMysqlConnection: Query: SELECT UNIX_TIMESTAMP(status_update_time) AS status_update_time, endpoint_name FROM icinga_programstatus WHERE instance_id = 1
[2019-10-21 12:15:24 -0700] information/IdoMysqlConnection: Last update by endpoint 'i2-m2.example.com' was 2.85751s ago (< failover timeout of 60s). Retrying.
[2019-10-21 12:15:34 -0700] information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 0, rate: 29.2333/s (1754/min 1754/5min 1754/15min);
[2019-10-21 12:15:34 -0700] debug/IdoMysqlConnection: Reconnect: Clearing ID cache.
[2019-10-21 12:15:34 -0700] notice/IdoMysqlConnection: Reconnect: 'ido-mysql' is now connected to database 'icinga'.
[2019-10-21 12:15:34 -0700] debug/IdoMysqlConnection: Query: SELECT @@global.max_allowed_packet AS max_allowed_packet
[2019-10-21 12:15:34 -0700] debug/IdoMysqlConnection: Query: SELECT version FROM icinga_dbversion WHERE name='idoutils'
[2019-10-21 12:15:34 -0700] debug/IdoMysqlConnection: Query: SELECT instance_id FROM icinga_instances WHERE instance_name = 'default'
[2019-10-21 12:15:34 -0700] debug/IdoMysqlConnection: Query: SELECT UNIX_TIMESTAMP(status_update_time) AS status_update_time, endpoint_name FROM icinga_programstatus WHERE instance_id = 1
[2019-10-21 12:15:34 -0700] information/IdoMysqlConnection: Last update by endpoint 'i2-m2.example.com' was 2.85438s ago (< failover timeout of 60s). Retrying.
[2019-10-21 12:15:44 -0700] debug/IdoMysqlConnection: Reconnect: Clearing ID cache.
```
Also i've tried to catch any UPDATEs on primary master since start:
```
[root@i2-m1 icinga2]# grep '2019-10-21 12:15:24' -A999999 /var/log/icinga2/debug.log | grep 'IdoMysqlConnection: Query: UPDATE' | wc -l
```
```
0
```

**Comment by dmitriy-terzeman** [comment] 2019-10-30 17:56
Is there any additional info required?

**Comment by dnsmichi** [comment] 2019-10-31 13:27
I can see that this line

```
[2019-10-21 12:15:34 -0700] information/IdoMysqlConnection: Last update by endpoint 'i2-m2.example.com' was 2.85438s ago (< failover timeout of 60s). Retrying.
```

Detects the update from the secondary master and does not fail over. Therefore `i2-m2.example.com` should still be writing to the database.

IIRC I have lowered the failover timeout to 30s default in 2.11, which may have an influence here with your 60s changed setting. 

The first master should never instantly update the programstatus table, following this from the original post ...

> When primary master recovered, it instantly updates table in the database "icinga_programstatus", that time secondary master see that icinga-master1 updated record in this table and stops writing to database, in logs on icinga-master2 i see the following:
[2019-10-18 04:40:33 -0700] information/IdoMysqlConnection: Last update by endpoint 'icinga-master1' was 11.7505s ago (< failover timeout of 60s). Retrying.

That leads to the assumption that master2 pauses the IDO feature when master1 recovers. Is there an entry in the log which tells exactly that?

Also, query the REST API for the runtime state of both features. `curl -k -s -u root:icinga https://localhost:5665/v1/objects/idomysqlconnections` and verify that `paused` is not true for master2 in case of such a recovery. 

Also, lowering the failover timeout may be of help here.

**Comment by dmitriy-terzeman** [comment] 2019-10-31 15:43
@dnsmichi 
>The first master should never instantly update the programstatus table, following this from the original post ...
Please take note that it's described under my "Workaround" solution, only when i set `enable_ha = false` on primary master and `enable_ha = true` on secondary master, so that's whats working for me right now, but not the default expected behavior.

Logs that i've listed only related to normal HA cluster configuration e.g. with option `enable_ha = true` on both instances

>Detects the update from the secondary master and does not fail over. Therefore i2-m2.example.com should still be writing to the database.

Yeah, but take a look above on i2-m2.example.com log listing, it keeps updating icinga_programstatus table, with records like:
```
[2019-10-21 12:36:02 -0700] debug/IdoMysqlConnection: Query: UPDATE icinga_programstatus
```
but stop any icinga_servicestatus or icinga_hoststatus updates.

>IIRC I have lowered the failover timeout to 30s default in 2.11, which may have an influence here with your 60s changed setting.

I've tried several options, default 30, 60 and 300 sec, result is the same, secondary master stop all updates except of icinga_programstatus in 5-10 sec after primary master recovery.

I'll provide REST API reply hopefully little bit later today.

P.S. By the way have you had a chance for reproducing it?

**Comment by dnsmichi** [comment] 2019-11-02 10:53
No, I am hopping between conferences, trainings, workshops and OSMC preparations. My schedule is full for the next three weeks unfortunately.

**Comment by dmitriy-terzeman** [comment] 2019-11-04 14:05
Here is output from https://localhost:5665/v1/objects/idomysqlconnections?pretty=1 .
i2-m1.example.com (primary master):
```
{
    "results": [
        {
            "attrs": {
                "__name": "ido-mysql",
                "active": true,
                "categories": [
                    "DbCatConfig",
                    "DbCatState",
                    "DbCatAcknowledgement",
                    "DbCatComment",
                    "DbCatDowntime",
                    "DbCatEventHandler",
                    "DbCatFlapping",
                    "DbCatNotification",
                    "DbCatProgramStatus",
                    "DbCatRetention",
                    "DbCatStateHistory"
                ],
                "cleanup": {},
                "connected": false,
                "database": "icinga",
                "enable_ha": true,
                "enable_ssl": false,
                "failover_timeout": 30.0,
                "ha_mode": 0.0,
                "host": "i2-web1.example.com",
                "instance_description": "",
                "instance_name": "default",
                "last_failover": 1572874806.787285,
                "name": "ido-mysql",
                "original_attributes": null,
                "package": "_etc",
                "password": "password",
                "paused": false,
                "port": 3306.0,
                "schema_version": "1.14.3",
                "should_connect": false,
                "socket_path": "",
                "source_location": {
                    "first_column": 1.0,
                    "first_line": 6.0,
                    "last_column": 37.0,
                    "last_line": 6.0,
                    "path": "/etc/icinga2/features-enabled/ido-mysql.conf"
                },
                "ssl_ca": "",
                "ssl_capath": "",
                "ssl_cert": "",
                "ssl_cipher": "",
                "ssl_key": "",
                "table_prefix": "icinga_",
                "templates": [
                    "ido-mysql"
                ],
                "type": "IdoMysqlConnection",
                "user": "icinga",
                "version": 0.0,
                "zone": ""
            },
            "joins": {},
            "meta": {},
            "name": "ido-mysql",
            "type": "IdoMysqlConnection"
        }
    ]
}
```
The same for i2-web1.example.com (primary master):
```
{
    "results": [
        {
            "attrs": {
                "__name": "ido-mysql",
                "active": true,
                "categories": [
                    "DbCatConfig",
                    "DbCatState",
                    "DbCatAcknowledgement",
                    "DbCatComment",
                    "DbCatDowntime",
                    "DbCatEventHandler",
                    "DbCatFlapping",
                    "DbCatNotification",
                    "DbCatProgramStatus",
                    "DbCatRetention",
                    "DbCatStateHistory"
                ],
                "cleanup": {},
                "connected": true,
                "database": "icinga",
                "enable_ha": true,
                "enable_ssl": false,
                "failover_timeout": 30.0,
                "ha_mode": 0.0,
                "host": "i2-web1.example.com",
                "instance_description": "",
                "instance_name": "default",
                "last_failover": 1572875514.598105,
                "name": "ido-mysql",
                "original_attributes": null,
                "package": "_etc",
                "password": "password",
                "paused": false,
                "port": 3306.0,
                "schema_version": "1.14.3",
                "should_connect": true,
                "socket_path": "",
                "source_location": {
                    "first_column": 1.0,
                    "first_line": 6.0,
                    "last_column": 37.0,
                    "last_line": 6.0,
                    "path": "/etc/icinga2/features-enabled/ido-mysql.conf"
                },
                "ssl_ca": "",
                "ssl_capath": "",
                "ssl_cert": "",
                "ssl_cipher": "",
                "ssl_key": "",
                "table_prefix": "icinga_",
                "templates": [
                    "ido-mysql"
                ],
                "type": "IdoMysqlConnection",
                "user": "icinga",
                "version": 0.0,
                "zone": ""
            },
            "joins": {},
            "meta": {},
            "name": "ido-mysql",
            "type": "IdoMysqlConnection"
        }
    ]
}
```

**Comment by dmitriy-terzeman** [comment] 2019-11-04 14:11
Also i've updated all icinga2 components to newer version: 2.11.2-1 (from 2.11.0-1), but issue is still reproducible.

**Comment by fireheadman** [comment] 2019-12-18 19:50
sub'd, very interesting so far.

**Comment by agougo** [comment] 2020-05-18 13:09
I am also getting the exact same behavior when using the PostgreSQL IDO. When setting up a master master HA configuration and adding a host using the director everything works fine. When shutting down the first master the secondary takes over as expected. When the primary comes up it breaks the services monitored and it shows them as Overdue. The peculiar thing is that not all services are shown as overdue, only some of them.

Scenarios:

When shutting down the secondary master, the primary shows all services as expected. Nothing is overdue. When the secondary master is coming up then services are shown as overdue.

When shutting down the primary master, the secondary master picks up and the services there work as expected. Nothing is overdue. When the primary comes up again, it takes over the back end. The services then are starting to show as overdue but not all of them.

**Comment by htriem** [comment] 2020-07-03 07:54
@Al2Klimov

**Comment by agougo** [comment] 2020-07-03 10:21
> 
> 
> I am also getting the exact same behavior when using the PostgreSQL IDO. When setting up a master master HA configuration and adding a host using the director everything works fine. When shutting down the first master the secondary takes over as expected. When the primary comes up it breaks the services monitored and it shows them as Overdue. The peculiar thing is that not all services are shown as overdue, only some of them.
> 
> Scenarios:
> 
> When shutting down the secondary master, the primary shows all services as expected. Nothing is overdue. When the secondary master is coming up then services are shown as overdue.
> 
> When shutting down the primary master, the secondary master picks up and the services there work as expected. Nothing is overdue. When the primary comes up again, it takes over the back end. The services then are starting to show as overdue but not all of them.

As it turns out, I am guessing that the overdue services are there because the last check timestamp is not valid. As a workaround, when the primary master takes over (after the outage), I can schedule a custom check in lets say 3 minutes. If i do that then the correct time time stamp is picked up by the service and it is not overdue anymore. Then the check interval is valid and the service is checked as designed.

**Comment by Al2Klimov** [comment] 2020-08-07 15:50
Hello @dmitriy-terzeman and thank you for reporting!

Please try v2.12.0.

Best,
AK

**Comment by Al2Klimov** [comment] 2021-09-07 15:36
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.

**Closed by Al2Klimov** 2021-09-07 15:36 UTC
Labels: area/distributed, area/db-ido, needs feedback
