### ISSUE TITLE
Using icingacli-businessprocess check command does not work correctly if SELinux is enabled.

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [Icinga/icinga2#7497] opened 2019-09-12 21:51 UTC
Icinga 2 Version: 2.10.5
Icinga Web 2 Version: 2.6.3

When using SELinux on an Icinga Web 2 server, access to the `/etc/icingaweb2` directory and other assets is denied when attempting to use the `icingacli-businessprocess` CheckCommand.

The error in the icingaweb2 interface is:
```
Module path "/usr/share/icingaweb2/modules" does not exist
ERROR: Cannot read enabled modules. Config directory "/etc/icingaweb2" is not readable
```

Oddly enough, executing an equivalent `icingacli` command from icingacli at command line executes just fine. SELinux was found to be the culprit.

Three steps are needed to all the CheckCommand to work:
1. `usermod -G icingweb2 icinga` (if not already added to that group)
2. `setenforce 0` (since the contexts do not match)
3. Restart the icinga2 process on the web server.

**Comment by dnsmichi** [comment] 2019-09-13 07:26
@dgoetz Can you have a look please? I thought we have added an SELinux for that already.

**Comment by dgoetz** [comment] 2019-09-13 08:40
Pull request https://github.com/Icinga/icingaweb2/pull/3369 for this was declined by @lippserd, so please assign him.

**Comment by dnsmichi** [comment] 2019-09-13 11:13
I see. 

I've just tested it in a VM, modifying the user group is sufficient - doesn't matter in regard of the SELinux policies.

```
[vagrant@icinga2 ~]$ sudo -i
[root@icinga2 ~]# sudo -u icinga icingacli x509
ERROR: Cannot read enabled modules. Config directory "/etc/icingaweb2" is not readable
[root@icinga2 ~]# usermod -a -G icingaweb2 icinga
[root@icinga2 ~]# id icinga
uid=996(icinga) gid=993(icinga) groups=993(icinga),992(icingacmd),989(icingaweb2)
[root@icinga2 ~]# sudo -u icinga icingacli x509
USAGE: icingacli x509 <command> [<action>] [options]

Available commands:

  check
  import
  jobs
  scan
  verify

Show help on a specific command: icingacli help x509 <command>
[root@icinga2 ~]# setenforce 1
[root@icinga2 ~]# sudo -u icinga icingacli x509
USAGE: icingacli x509 <command> [<action>] [options]

Available commands:

  check
  import
  jobs
  scan
  verify

Show help on a specific command: icingacli help x509 <command>
```

**Comment by dnsmichi** [comment] 2019-09-13 11:14
The original PR is https://github.com/Icinga/icingaweb2/issues/3235 whereas the documentation points to https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#icingacli

**Comment by Al2Klimov** [comment] 2020-03-18 12:43
@lippserd [You said](https://github.com/Icinga/icingaweb2/pull/3369#issuecomment-467370346) this issue is just about documentation, right?

**Comment by lippserd** [comment] 2020-03-19 08:51
> @lippserd [You said](https://github.com/Icinga/icingaweb2/pull/3369#issuecomment-467370346) this issue is just about documentation, right?

Yep. A section somewhere in our Icinga 2 docs explaining how to configure checks that require access to Icinga Web 2 should suffice.

**Comment by Al2Klimov** [comment] 2020-03-19 09:25
Any idea why I can't assign @dgoetz?

**Comment by lippserd** [comment] 2020-03-19 09:49
> Any idea why I can't assign @dgoetz?

Why? I think we should just add the section 😆

**Comment by Al2Klimov** [comment] 2020-03-19 09:50
Because I have almost no idea about SELinux. Or do I oversee anything?

**Comment by lippserd** [comment] 2020-03-19 10:17
> Because I have almost no idea about SELinux. Or do I oversee anything?

But maybe @htriem or @N-o-X has

**Comment by Al2Klimov** [comment] 2021-09-07 16:00
@htriem @N-o-X Is @lippserd right?

**Comment by htriem** [comment] 2022-11-16 15:18
@Al2Klimov As far as I can tell, the section has already been added to the Icinga 2 docs. So I'll close this.

**Closed by htriem** 2022-11-16 15:18 UTC
Labels: area/documentation, area/setup, needs feedback

**Comment by ronnybremer** [comment] 2022-11-22 10:07
Unfortunately, I just saw this post today....

@dnsmichi you wrote:
I've just tested it in a VM, modifying the user group is sufficient - doesn't matter in regard of the SELinux policies.

This is unfortunately only works for exactly the case you have tested, the command line execution with sudo. As soon as you run in through the icinga2 service, you continue to get the errors.

I reproduced the issue and turned on permissive mode of SELinux, after a few checks I turned it back off. This is the result from audit2allow, which would somehow needs to make it into any of the icinga2*selinux packages in order to work out of the box:

```
#============= icinga2_t ==============
allow icinga2_t icingaweb2_config_t:dir { getattr open read search };
allow icinga2_t icingaweb2_config_t:file { getattr open read };
allow icinga2_t icingaweb2_config_t:lnk_file { getattr read };
allow icinga2_t icingaweb2_content_t:dir { getattr open read search };
allow icinga2_t icingaweb2_content_t:file { getattr open read };
allow icinga2_t icingaweb2_rw_content_t:dir getattr;
```

There are a few more SELinux errors, but I think they are related to email notification:
```
#============= postfix_local_t ==============
allow postfix_local_t icinga2_spool_t:dir search;

#============= postfix_postdrop_t ==============
allow postfix_postdrop_t icinga2_t:fifo_file { getattr write };

#============= system_mail_t ==============
allow system_mail_t icinga2_t:fifo_file getattr;
```

So I do believe this issue should be re-opened and the selinux packages adopted.

**Comment by julianbrost** [comment] 2023-06-20 15:22
If you think there still is an issue, please open a new one with an up-to-date problem description. It's not really clear whether the problems described in comments are the same as in the first post and issues where the actual problem description is spread around all of its history are always hard to work with.

**Comment by NavidSassan** [comment] 2023-06-20 15:57
sure :) https://github.com/Icinga/icinga2/issues/9796
