### ISSUE TITLE
multiple OR operators in assign where cause syntax error, unexpected $end

### ISSUE THREAD

**Issue by m4k5ym** [Icinga/icinga2#7473] opened 2019-09-05 12:36 UTC
## Describe the bug

Service should be applied to only four hosts, so I build some ugly but should work ```assign where``` clause with four logical ```OR``` operators.

Now we come to the thing I don't understand  if I verify my code via ```icinga2 daemon -C``` the complier is reporting "```critical/config: Error: syntax error, unexpected $end```". While I'm building the exact same clause in Director, the core is taking the director one without complaining.

## To Reproduce

1. Create a service with following apply rule:
```
apply Service "test1" {
    import "test1"

    assign where host.display_name == "**confidential**" || host.display_name == "**confidential**" || host.display_name == "**confidential**" || host.display_name == "**confidential**"
}
```
2. Create an another service with following apply rule:
```
apply Service "test2" {
    import "test2"

    assign where host.display_name == "**confidential**" || host.display_name == "**confidential**" || host.display_name == "**confidential**" || host.display_name == "**confidential**"
}
```
3. Run following command:
```
icinga2 daemon -C
```
4. Final error:
```
[2019-09-05 14:22:34 +0200] information/cli: Icinga application loader (version: r2.10.5-1)
[2019-09-05 14:22:34 +0200] information/cli: Loading configuration file(s).
[2019-09-05 14:22:34 +0200] critical/config: Error: syntax error, unexpected $end
Location: in /etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf: 78:52-78:52
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(76):     import "test1"
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(77):
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(78):     assign where host.display_name == "**confidential**" || host.display_name == "**confidential**" || host.display_name == "**confidential**" || host.display_name == "**confidential**"
                                                                                                                            ^
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(79): }
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(80):
```

## Expected behavior

Since both are the same - same but generate a different result I'd prefer to have one and same result.

## Workaround

The beautiful way to solve this is:
```
    assign where host.display_name in [ "**confidential**", "**confidential**", "**confidential**", "**confidential**" ]
```

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.10.5-1
* Operating System and version: SUSE Linux Enterprise Server 12 SP4
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): No relevance
* Config validation (`icinga2 daemon -C`):
```
[2019-09-05 13:28:21 +0200] information/cli: Icinga application loader (version: r2.10.5-1)
[2019-09-05 13:28:21 +0200] information/cli: Loading configuration file(s).
[2019-09-05 13:28:21 +0200] critical/config: Error: syntax error, unexpected $end
Location: in /etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf: 13:52-13:52
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(11):     import "lin-mem"
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(12):
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(13):     assign where host.display_name == "**confidential**" || host.display_name == "**confidential**" && host.display_name == "**confidential**" && host.display_name == "**confidential**"
                                                                                                                            ^
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(14): }
/etc/icinga2/zones.d/global-linux/services/agent-ssh/set-basic.conf(15):
```

**Comment by dnsmichi** [comment] 2019-09-05 14:17
Since you've removed the display_name values, it is hard to guess. Are there any characters inside which would require escaping?

**Comment by m4k5ym** [comment] 2019-09-05 14:30
Hi,

no its just a string containing letters and numbers like abc123.

Sincerely,

**Comment by dnsmichi** [comment] 2019-09-13 08:07
Maybe the Windows/Linux terminal and editor added some hidden UTF8 characters which cause trouble here. I am not able to reproduce this here.

**Comment by Al2Klimov** [comment] 2020-03-04 16:54
@m4k5ym Please share a hex dump of a config file which doesn't work.

**Comment by m4k5ym** [comment] 2020-03-04 16:56
It's kinda to late for this I'm sorry.

I used my workaround to solve this and I have no access to them anymore. Probably they even don't exists anymore.

Sincerly

**Comment by Al2Klimov** [comment] 2020-03-04 16:58
@N-o-X IMAO there was just an invisible character. Can we close this one?

**Closed** 2020-03-05 13:45 UTC
Labels: area/configuration, needs-feedback
