### ISSUE TITLE
Missing recovery notification after a downtime with new hard state change

### ISSUE THREAD

**Issue by icurga** [Icinga/icinga2#9054] opened 2021-10-29 12:16 UTC
## Describe the bug

Recovery message will be lost or displaced, when - after the last notified problem -
new hard state(s) followed by the recovery, occur inside a downtime or outside of a notification time period.
When entering the notification window again, no recovery notification is triggered.

In this case notifications are configured only for `states = [ OK, Critical ]` and `types = [ Problem, Recovery ]`.

## To Reproduce

For a detailed overview, please look at the screenshots below. 

1. Let a service become `Critical` and notify yourself
2. Start a downtime
3. Create a hard state change or more
4. Fix the service and set it to `OK`
5. Remove or let the downtime expire
6. Recovery notification will not be triggered

- Workaround to trigger the notification:
7. Set the service to a **hard state** which is not notifying
8. Fix the service again to `OK` state
9. Recovery notification is now send

## Expected behavior

* For the last notified problem, the recovery notification is send when leaving a notification suppressed window with an `OK`, also if other states happened inside it.
* Currently it is also like this, when no other hard state changes, except the one from `Critical` to `OK`, happening inside a downtime, the recovery message will triggered with the end of the downtime. 
See #4662

## Screenshots

Downtime starts with a `Critical` state and ends with an `OK`.
In between this states, some new hard state change or flapping irritates the future recovery notification.

Unknown - Critical | OK - Critical
------------ | -------------
![MissingRecovery_after_StateChange_in_DT1](https://user-images.githubusercontent.com/93325902/139404753-cdf56b9c-7dcf-4a0f-97c0-b2afd8fa54a2.png)|![MissingRecovery_after_StateChange_in_DT2](https://user-images.githubusercontent.com/93325902/139405724-33890b7b-6f30-499b-80db-df322b54517d.png)

## Your Environment

* Version used (`icinga2 --version`): `2.12.5-1`
* Operating System and version: `CentOS 7 x86_64`
* Enabled features (`icinga2 feature list`): `api checker ido-mysql mainlog notification`
* Icinga Web 2 version and modules (System - About): `2.9.3`
* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: 2.12.5-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga2master-1.monitoring.test
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 4 TimePeriods.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 Service.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 2 Notifications.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 1 Comment.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 236 CheckCommands.
information/ConfigItem: Instantiated 1 ApiListener.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

## Additional context

This bug was reported by our customer and then reproduced in a fresh installed Icinga single setup.
Same behavior was also tested outside a notification period instead a downtime.
Here the relevant objects:

templates.conf
```
template Notification "mail-host-notification" {
  command = "mail-host-notification"

  states = [ Up, Down ]
  types = [ Problem, Recovery ]

  period = "24x7"
}

template Notification "mail-service-notification" {
  command = "mail-service-notification"

  states = [ OK, Critical ]
  types = [ Problem, Recovery ]

  period = "24x7"
}
```
notifications.conf
```
apply Notification "mail-icingaadmin" to Host {
  import "mail-host-notification"
  user_groups = host.vars.notification.mail.groups
  users = host.vars.notification.mail.users

  assign where host.vars.notification.mail
}

apply Notification "mail-icingaadmin" to Service {
  import "mail-service-notification"
  user_groups = host.vars.notification.mail.groups
  users = host.vars.notification.mail.users

  assign where host.vars.notification.mail
}
```
users.conf
```
object User "icingaadmin" {
  import "generic-user"

  display_name = "Icinga 2 Admin"
  groups = [ "icingaadmins" ]
  email = "root@localhost"
}
```

**Comment by lippserd** [comment] 2021-11-04 14:24
ref/IP/36860

**Comment by icurga** [comment] 2021-11-12 10:39
The bug was also reproduced with the latest version `2.13.1-1` and is still present there.

**Comment by Al2Klimov** [comment] 2021-11-15 16:16
## Confirmed

![Bildschirmaufnahme 2021-11-15 um 16 37 36](https://user-images.githubusercontent.com/6053266/141814712-f312a1a7-e7e4-4333-b953-4b77faac99e9.gif)

## No add. hard state change = no problem

![Bildschirmaufnahme 2021-11-15 um 16 42 06](https://user-images.githubusercontent.com/6053266/141815891-66a1084f-2df3-4061-93a1-ad044ac1cd19.gif)

**Comment by BorisTrnka** [comment] 2022-01-19 09:45
Hello, let me add my 50 cents ...
Reporting the same issue brought us to an idea/question: isn’t it intended the recovery notification should be sent even during the active downtime?
I mean, it does not make much sense to wait till end of the downtime to confirm the issue was fixed in meantime (esp. when the downtime is defined e.g., for 2 days). Or?
Wouldn't such approach also prevent/fix this bug?

Downtime should prevent to trigger NON-OK state's notifications (type: "Problem"), but it's still fine to get OK state's notifications (type: Recovery), right?

Thanks for your insight.

**Comment by julianbrost** [comment] 2022-01-19 10:06
For downtimes, you can reason that this behavior might be desired. But that would be a larger change in behavior than what we'd want to do in a bugfix release.

Also, there are other reasons where notifications are suppressed, like time periods set on notifications. I think these should behave somewhat consistent and you certainly don't want the notification restricted to business hours to fire on the weekend just because something just decided to recover.

**Comment by BorisTrnka** [comment] 2022-01-19 10:36
> Also, there are other reasons where notifications are suppressed, ...

Sure, no doubt about that. 
But I don't expect the "downtime" and "time-period" affect each-other directly, or?

I mean, having defined downtime and "office-hours" time-period, I would expect to get 
- all notifications outside the downtime-period during office hours (downtime = false; notification-period = true), 
- recovery notification during the downtime & office hours (downtime = true; notification-period = true)
- and no notification at all during non-office ours; does not matter if downtime defined or not (downtime = true/false; notification-period = false).

**Comment by julianbrost** [comment] 2022-01-19 11:04
At the moment, we plan to address this in the next round of bugfix releases, so we're focusing on a fix that does not introduce too big changes in behavior. For now, [the documentation](https://icinga.com/docs/icinga-2/latest/doc/08-advanced-topics/#downtimes) says "Downtimes suppress notifications" so I think someone can reasonably assume that during a downtime, they can do whatever they want to a service, without generating notifications.

Of course that doesn't mean that this behavior is set in stone and could be discussed for 2.14 or a later version.

**Comment by BorisTrnka** [comment] 2022-01-19 11:53
@julianbrost ok, fully understand. I just wanted to share our "real-life user experience" ... I'm not saying all others have same expectations or must follow same usage approach ... Just my 50cents to discussion and a point to think about.
Thanks.

**Comment by carraroj** [comment] 2022-01-21 11:02
ref/NC/742883

**Closed** 2022-03-07 08:05 UTC
Labels: bug, ref/IP, ref/NC
