### ISSUE TITLE
You need to add at least one master/satellite endpoint.

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#5895] opened 2017-12-20 10:54 UTC
## Expected Behavior

I run the *Steps to Reproduce* and it works OOTB.

## Current Behavior

I run the *Steps to Reproduce* and it fails w/ *You need to add at least one master/satellite endpoint.*

## Possible Solution

I'd like to hear one from you.

## Steps to Reproduce (for bugs)

1. Download "MSEdge on Win10" from [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and inside that VM...
2. Install the latest Icinga 2
3. Run the setup wizard
4. Don't change any settings and press next

## Context

https://github.com/Icinga/icingaweb2-module-graphite/issues/71

## Your Environment

See *Steps to Reproduce*.

**Comment by Crunsher** [comment] 2017-12-20 11:55
The setup wizard exists to add endpoints and is not required to be run, but if you do, you'll need to add endpoints ^_^

Closing this as it is the intended behavior.

**Closed by Crunsher** 2017-12-20 11:55 UTC
