### ISSUE TITLE
Too long UPDATE icinga_downtimehistory

### ISSUE THREAD

**Issue by xbulat** [Icinga/icinga2#5093] opened 2017-03-26 22:28 UTC
Updating icinga_downtimehistory blocks all service status updates, and at this time icingaweb2 shows my status "Backend icinga is not running", because "Last Status Update" is 20 minutes. We set about 6K downtime every night and this gap time is serious problem. How to can reduce the time of the operation "update icinga_downtimehistory"  and stop blocking other operations.

icinga2-ido-mysql                    2.6.2-1~debmon8+1 
percona-server-common-5.6            5.6.27-75.0-1.jessie

**Comment by gunnarbeutner** [comment] 2017-03-27 04:15
Could this be a duplicate of #5080?

**Comment by dnsmichi** [comment] 2017-03-27 08:13
Yep, definitely. We should consider adding the fix in #5080 to 2.6.3.

**Closed** 2017-03-27 08:15 UTC
Labels: bug, DB IDO
