### ISSUE TITLE
abort() in `InfluxdbCommonWriter::Flush()`

### ISSUE THREAD

**Issue by s-blottk** [Icinga/icinga2#9039] opened 2021-10-14 15:52 UTC
## Describe the bug

Icinga2 is crashing sporadically without any pattern.

## To Reproduce

I was not able to reproduce this issue. Mostly this happens at night.

## Expected behavior

Icinga2 should not crash.

## Your Environment

Red Hat Enterprise Linux Server release 7.9 (Maipo)

* Version used (`icinga2 --version`): Application version: 2.13.1-1
* Operating System and version: Red Hat Enterprise Linux Server release 7.9 (Maipo)
* Enabled features (`icinga2 feature list`): api checker command debuglog ido-mysql influxdb mainlog notification syslog
* Icinga Web 2 version and modules (System - About): setup company cube director doc grafana incubator ipl monitoring reactbundle 
* Config validation (`icinga2 daemon -C`): ok
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context

Icinga crashes sporadically for multiple hours and does not come back by itself.

**icinga2.log-20211014**
`[2021-10-14 00:27:46 +0200] information/WorkQueue: #5 (InfluxdbWriter, influxdb) items: 1, rate: 25.6667/s (1540/min 3606/5min 3606/15min);
[2021-10-14 00:28:22 +0200] information/Checkable: Notifications are disabled for checkable 'Helion MGMT 10.116.236.23 - otncloud-ccp-nn-m1!ping4'.
[2021-10-14 00:28:53 +0200] warning/InfluxdbWriter: Ignoring invalid perfdata for checkable 'VSA - ac-VSA01!vsa_network' and command 'check_vsa_network' with value: sent={sent}
Context:
        (0) Processing check result for 'VSA - ac-VSA01!vsa_network'

[2021-10-14 00:28:53 +0200] warning/InfluxdbWriter: Ignoring invalid perfdata for checkable 'VSA - ac-VSA01!vsa_network' and command 'check_vsa_network' with value: received={received}".format(received=calc_data_recv(),
Context:
        (0) Processing check result for 'VSA - ac-VSA01!vsa_network'

[2021-10-14 00:28:53 +0200] warning/InfluxdbWriter: Ignoring invalid perfdata for checkable 'VSA - ac-VSA01!vsa_network' and command 'check_vsa_network' with value: sent=calc_data_sent())
Context:
        (0) Processing check result for 'VSA - ac-VSA01!vsa_network'

[2021-10-14 00:29:39 +0200] information/Checkable: Notifications are disabled for checkable 'Helion MGMT 10.116.236.24 - otncloud-ccp-nn-m2!ping4'.
[2021-10-14 00:30:08 +0200] information/Application: Received request to shut down.
[2021-10-14 00:30:08 +0200] information/Application: Shutting down...
[2021-10-14 00:30:08 +0200] information/CheckerComponent: 'checker' stopped.
[2021-10-14 00:30:08 +0200] information/NotificationComponent: 'notification' stopped.
[2021-10-14 00:30:08 +0200] information/ExternalCommandListener: 'command' stopped.
[2021-10-14 00:30:08 +0200] information/DbConnection: Pausing IDO connection: ido-mysql
[2021-10-14 00:30:08 +0200] information/IdoMysqlConnection: Disconnected from 'ido-mysql' database 'icinga_ido'.
[2021-10-14 00:30:08 +0200] information/IdoMysqlConnection: 'ido-mysql' paused.
[2021-10-14 00:30:08 +0200] information/DbConnection: 'ido-mysql' stopped.
[2021-10-14 00:30:08 +0200] critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in '/var/log/icinga2/crash/report.1634164208.828381'
[2021-10-14 02:57:06 +0200] information/Checkable: Checkable 'Helion F.IP 10.116.239.29 (3dxfcsm53) in 3DX-Network-3!HLN_ping4' has 2 notification(s). Checking filters for type 'Problem', sends will be logged.
[2021-10-14 02:57:06 +0200] information/Notification: Sending 'Problem' notification 'Helion F.IP 10.116.239.29 (3dxfcsm53) in 3DX-Network-3!HLN_ping4!mattermost_service' for user 'mattermost'
[2021-10-14 02:57:06 +0200] information/Notification: Sending 'Problem' notification 'Helion F.IP 10.116.239.29 (3dxfcsm53) in 3DX-Network-3!HLN_ping4!Email-Alerts-Services' for user 'cloudsquad'
[2021-10-14 02:58:56 +0200] information/Checkable: Checkable 'Helion F.IP 10.116.238.107 (3dxftsm03) in 3DX-Network-3!HLN_ping4' has 2 notification(s). Checking filters for type 'Problem', sends will be logged.
[2021-10-14 02:58:56 +0200] information/Notification: Sending 'Problem' notification 'Helion F.IP 10.116.238.107 (3dxftsm03) in 3DX-Network-3!HLN_ping4!Email-Alerts-Services' for user 'cloudsquad'
[2021-10-14 02:58:56 +0200] information/Notification: Sending 'Problem' notification 'Helion F.IP 10.116.238.107 (3dxftsm03) in 3DX-Network-3!HLN_ping4!mattermost_service' for user 'mattermost'
`

**/var/log/icinga2/crash/report.1634164208.828381**
`Caught SIGABRT.
Current time: 2021-10-14 00:30:08 +0200

  Application version: 2.13.1-1

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1127.10.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-507-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Stacktrace:
 0# icinga::Application::SigAbrtHandler(int) in /usr/lib64/icinga2/sbin/icinga2
 1# 0x00007FCE7A4C5630 in /lib64/libpthread.so.0
 2# gsignal in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# 0x00007FCE7A160F67 in /lib64/libc.so.6
 5# 0x00007FCE7A167474 in /lib64/libc.so.6
 6# 0x00007FCE7A1696A4 in /lib64/libc.so.6
 7# icinga::InfluxdbCommonWriter::Flush() in /usr/lib64/icinga2/sbin/icinga2
 8# icinga::InfluxdbCommonWriter::FlushTimeoutWQ() in /usr/lib64/icinga2/sbin/icinga2
 9# icinga::WorkQueue::RunTaskFunction(std::function<void ()> const&) in /usr/lib64/icinga2/sbin/icinga2
10# icinga::WorkQueue::WorkerThreadProc() in /usr/lib64/icinga2/sbin/icinga2
11# 0x00007FCE7C3C5954 in /lib64/libboost_thread.so.1.69.0
12# 0x00007FCE7A4BDEA5 in /lib64/libpthread.so.0
13# clone in /lib64/libc.so.6

***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***`

**Comment by linionbb** [comment] 2021-11-16 10:54
I had the same stack trace (also on RHEL7.9), even though Icinga2 didn't crash. Figure it has something to do with libboost.
On my end only InfluxdbWriter didn't work anymore after upgrading Icinga2 to v2.13.1.

The cause for the stack trace what that I set "ssl_enable = false" in /etc/icinga2/features-enabled/influxdb.conf.

The reason I did this was due to InfluxdbWriter spamming TLS errors (due to [CVE ](https://icinga.com/blog/2021/08/19/icinga-2-13-1-security-release/)fix). Sadly Icinga2 doesn't evaluate the OS trusted certificate store or I wouldn't even have noticed this... Fixed it by enabling ssl and speciyfing the ssl_ca_cert explicitely.


ssl_enable = true
changed to:
ssl_enable = true
ssl_ca_cert = "path/to/ca.crt"

**Comment by Al2Klimov** [comment] 2021-11-16 10:57
@s-blottk Please confirm.

**Comment by formorer** [comment] 2021-11-16 15:50
We had the same crash two times in the last weeks on a customer system (Production, therefore no dump). We weren't able to reproduce it until now, but the SIGABRT somewhere in Influx and icinga::Checkable looks very similar. 

[report.1636663934.190418.log](https://github.com/Icinga/icinga2/files/7547887/report.1636663934.190418.log)
[report.1635174870.466450.log](https://github.com/Icinga/icinga2/files/7547888/report.1635174870.466450.log)

**Comment by Al2Klimov** [comment] 2021-11-17 09:30
> Production, therefore no dump

I.. don't understand? Can't you enable them there?

**Comment by formorer** [comment] 2021-11-17 09:33
> > Production, therefore no dump
> 
> I.. don't understand? Can't you enable them there?

Exactly, and even if we would we would not able to share the dump (customer specific data)

**Comment by Al2Klimov** [comment] 2021-11-17 09:46
And why can't you **enable** it?

**Comment by formorer** [comment] 2021-11-17 09:53
The customer doesn't want to enable Coredumps

**Comment by s-blottk** [comment] 2021-12-07 09:32
@Al2Klimov what is included in the core dump? Where can I find those files?

**Comment by Al2Klimov** [comment] 2021-12-07 13:28
1. The complete memory of the Icinga 2 process
2. Whereever you put them: https://icinga.com/docs/icinga-2/latest/doc/21-development/#development-debug-core-dump

**Comment by Al2Klimov** [comment] 2021-12-13 17:32
> Stack trace was caused by setting "ssl_enable = false" in /etc/icinga2/features-enabled/influxdb.conf.

Strange, shouldn’t cause an abort()..

```
[2021-12-13 18:17:41 +0100] warning/InfluxdbWriter: Failed to parse HTTP response from host '127.0.0.1' port '5665': Error: end of stream

Stacktrace:
 0# __cxa_throw in /Users/aklimov/NET/WS/icinga2/prefix/lib/icinga2/sbin/icinga2
 1# void boost::throw_exception<boost::system::system_error>(boost::system::system_error const&, boost::source_location const&) in /Users/aklimov/NET/WS/icinga2/prefix/lib/icinga2/sbin/icinga2
 2# unsigned long boost::beast::http::read<icinga::Shared<boost::asio::buffered_stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> > >, boost::beast::basic_flat_buffer<std::__1::allocator<char> >, false>(icinga::Shared<boost::asio::buffered_stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> > >&, boost::beast::basic_flat_buffer<std::__1::allocator<char> >&, boost::beast::http::basic_parser<false>&) in /Users/aklimov/NET/WS/icinga2/prefix/lib/icinga2/sbin/icinga2
 3# icinga::InfluxdbCommonWriter::Flush() in /Users/aklimov/NET/WS/icinga2/prefix/lib/icinga2/sbin/icinga2
 4# icinga::InfluxdbCommonWriter::FlushTimeoutWQ() in /Users/aklimov/NET/WS/icinga2/prefix/lib/icinga2/sbin/icinga2
 5# icinga::WorkQueue::RunTaskFunction(std::__1::function<void ()> const&) in /Users/aklimov/NET/WS/icinga2/prefix/lib/icinga2/sbin/icinga2
 6# icinga::WorkQueue::WorkerThreadProc() in /Users/aklimov/NET/WS/icinga2/prefix/lib/icinga2/sbin/icinga2
 7# boost::(anonymous namespace)::thread_proxy(void*) in /Users/aklimov/NET/WS/icinga2/prefix/lib/icinga2/sbin/icinga2
 8# _pthread_start in /usr/lib/system/libsystem_pthread.dylib
[2021-12-13 18:17:41 +0100] critical/InfluxdbWriter: Exception during InfluxDB operation: Verify that your backend is operational!
```

**Comment by Al2Klimov** [comment] 2021-12-13 17:51
Also it’s not https://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/ref/boost__beast__http__basic_fields/operator_lb__rb_.html 's value result captured by ref:

https://github.com/Icinga/icinga2/blob/4951cdf5610f6ab37ac86263143d99a9c0c8beb3/lib/perfdata/influxdbcommonwriter.cpp#L511

```
[2021-12-13 18:48:25 +0100] warning/InfluxdbWriter: Unexpected response code: OK
[2021-12-13 18:48:25 +0100] warning/InfluxdbWriter: Unexpected Content-Type:
```

**Comment by Al2Klimov** [comment] 2021-12-13 17:57
However it **may be** a remote returning `Content-Type: application/json` and `null`:

```
[2021-12-13 18:55:40 +0100] warning/InfluxdbWriter: Unexpected response code: OK
➜  icinga2 git:(4951cdf56) echo $?
139
➜  icinga2 git:(4951cdf56)
```

**Comment by julianbrost** [comment] 2021-12-14 11:43
Definitely looks like an issue, but I think this is something different from this issue. The stack in the issue show abort being called from libc. For the issue you found, I'd expect one of the following behaviors depending on the build configuration (compiled with `-DNDEBUG` or not):
* `intrusive_ptr` performs no check -> null pointer dereferenced -> SIGSEGV
* `intrusive_ptr` performs a check -> calls abort -> stack should show icinga2 directly calling `abort()` as this is done in a boost header.

**Comment by Al2Klimov** [comment] 2021-12-14 11:45
I agree that my linked PRs are unlikely to be related, but it **could** also be the inlined `Dictionary#Get()` -> **stdlib** map.

**Comment by julianbrost** [comment] 2021-12-14 12:31
Okay right, the first operation performed on the null pointer might also be some from the stdlib. But that should rather be the ObjectLock mutex than the std::map, but that's only a detail. What kind of build did you test with as that shows exit code 139, i.e. SIGSEGV.

**Comment by Al2Klimov** [comment] 2021-12-14 12:54
Errm..

```bash
cmake \
        -GNinja \
        -DCMAKE_CXX_FLAGS=-DI2_DEBUG=1 \
        -DBOOST_ROOT=/Users/aklimov/NET/WS/boost_1_74_0 \
        "-DCMAKE_C_COMPILER=$(echo /usr/local/Cellar/ccache/*/libexec/cc)" \
        "-DCMAKE_CXX_COMPILER=$(echo /usr/local/Cellar/ccache/*/libexec/c++)" \
        "-DOPENSSL_ROOT_DIR=$(brew --prefix)/Cellar/openssl@1.1/1.1.1l_1" \
        -DICINGA2_UNITY_BUILD=OFF \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        "-DCMAKE_INSTALL_PREFIX=$(dirname "$(pwd)")/prefix$FAKENODE" \
        -DICINGA2_USER=aklimov \
        -DICINGA2_GROUP=staff \
        "-DICINGA2_PLUGINDIR=$(dirname "$(pwd)")/prefix$FAKENODE/usr/lib/nagios/
plugins" \
        -DCMAKE_VERBOSE_MAKEFILE=ON \
        -DICINGA2_WITH_PGSQL=ON \
        -DICINGA2_WITH_COMPAT=OFF \
        -DICINGA2_WITH_LIVESTATUS=OFF \
        -DBUILD_TESTING=off \
        ..
```

**Comment by julianbrost** [comment] 2021-12-14 14:38
`-DCMAKE_BUILD_TYPE=RelWithDebInfo` should lead to `-DNDEBUG`, so no null checks in `intrusive_ptr`. On the other hand macOS, so probably not the same libc als RHEL 7 anyways.

**Comment by Al2Klimov** [comment] 2021-12-14 14:39
... but the same Icinga 2 code which doesn't check $POINTER.

**Comment by julianbrost** [comment] 2021-12-14 14:50
Yeah, but one may observe a segfault while the other aborts for the same operation with undefined behavior.

**Comment by julianbrost** [comment] 2021-12-15 14:41
> [2021-10-14 00:30:08 +0200] information/Application: Received request to shut down.
> [2021-10-14 00:30:08 +0200] information/Application: Shutting down...
> [...]
> [2021-10-14 00:30:08 +0200] critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in '/var/log/icinga2/crash/report.1634164208.828381'

As this crashes while icinga2 is shutting down, this crash has probably the same cause as what I determined as the cause in https://github.com/Icinga/icinga2/issues/9102#issuecomment-994848575.

I'm closing this issue as the other one now contains the analysis that should help fixing the bug.

Duplicate of #9102

**Closed by julianbrost** 2021-12-15 14:41 UTC
Labels: core/crash
