### ISSUE TITLE
after 2.10.2 upgrade icinga2 API stalls

### ISSUE THREAD

**Issue by zahodi** [Icinga/icinga2#6930] opened 2019-02-06 01:27 UTC
Noticed that after upgrade to 2.10.2 icinga2 api stalls. I tried both an upgrade path and a clean install. The api responds after I empty zone.conf and hosts.conf.  

```
curl -k -s -u root:mypasword 'https://localhost:5665/v1' -vv
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5665 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 608 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* Operation timed out after 0 milliseconds with 0 out of 0 bytes received
* Closing connection 0
```

My icingaweb2 responds in the same way as noted in this ticket: https://github.com/Icinga/icingaweb2/issues/3651
* Version used (`icinga2 --version`):
```
 icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 16.04.5 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-1030-aws
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: 409e1113863b

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid 
```

```
icinga2 feature list
Disabled features: compatlog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata syslog
Enabled features: api checker command debuglog ido-mysql mainlog notification statusdata
```

```
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
```

`Linux staging-icinga 4.4.0-1030-aws #39-Ubuntu SMP Wed Aug 9 09:43:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by dnsmichi** [comment] 2019-02-06 08:17
> The api responds after I empty zone.conf and hosts.conf.

What do you mean by that?

In terms of problems, this sounds like a similar issue as with #6816. Can you test the snapshot packages?

**Comment by zahodi** [comment] 2019-02-07 01:26
@dnsmichi basically I cleared out all the hosts/nodes objects. 
I tried upgrade to snapshot version and apt fails.

{code}
dpkg: error processing package icinga2-common (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of icinga2-bin:
 icinga2-bin depends on icinga2-common (= 2.10.2+214.g4339240.2019.02.05+1.xenial-0); however:
  Package icinga2-common is not configured yet.

dpkg: error processing package icinga2-bin (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of icinga2:
 icinga2 depends on icinga2-bin (= 2.10.2+214.g4339240.2019.02.05+1.xenial-0); however:
  Package icinga2-bin is not configured yet.
 icinga2 depends on icinga2-common (= 2.10.2+214.g4339240.2019.02.05+1.xenial-0); however:
  Package icinga2-common is not configured yet.

dpkg: error processing package icinga2 (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent configuration of icinga2-ido-mysql:
 icinga2-ido-mysql depends on icinga2-bin (= 2.10.2+214.g4339240.2019.02.05+1.xenial-0); however:
  Package icinga2-bin is not configured yet.
 icinga2-ido-mysql depends on icinga2-common (= 2.10.2+214.g4339240.2019.02.05+1.xenial-0); however:
  Package icinga2-common is not configured yet.

dpkg: error processing package icinga2-ido-mysql (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 icinga2-common
 icinga2-bin
 icinga2
 icinga2-ido-mysql
E: Sub-process /usr/bin/dpkg returned an error code (1)
{code}

**Comment by dnsmichi** [comment] 2019-02-08 14:49
Keep a backup of your config. Try purging the previous packages, disable the stable repo, install the snapshot packages, do your tests and then rollback.

**Comment by zahodi** [comment] 2019-02-12 01:44
successfully upgraded to latest snapshot version. After removing command_endpoint attributes in my config everything is running except the api still hangs with no response or failure.

```
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.10.2-219-ge555b2f)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 16.04.5 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-1075-aws
  Architecture: x86_64
```

**Comment by zahodi** [comment] 2019-02-13 22:08
Is there anything else I can do to test this issues? Will 2.10.3 be released soon?

**Comment by dnsmichi** [comment] 2019-02-14 13:24
Since this didn't solve your problem, there's no point in releasing a 2.10.3.

Can you do me a favour and extract the full gdb backtrace from the running process after firing such a REST API query? The details are described in the development docs: https://icinga.com/docs/icinga2/latest/doc/21-development/#gdb-backtrace-from-running-process

**Comment by zahodi** [comment] 2019-02-14 19:25
[gdb_bt_312_1550171206.log](https://github.com/Icinga/icinga2/files/2866517/gdb_bt_312_1550171206.log)
[gdb_bt_32730_1550171205.log](https://github.com/Icinga/icinga2/files/2866518/gdb_bt_32730_1550171205.log)

**Comment by dnsmichi** [comment] 2019-02-15 08:54
Thanks. I can see lots of threads hanging in TCP::Connect(), which happens when reconnecting to endpoints. 

```
Thread 64 (Thread 0x7f480cf45700 (LWP 389)):
#0  0x00007f481473414d in connect () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x0000000000626ca5 in icinga::TcpSocket::Connect(icinga::String const&, icinga::String const&) ()
No symbol table info available.
#2  0x000000000067b165 in icinga::ApiListener::AddConnection(boost::intrusive_ptr<icinga::Endpoint> const&) ()
```

```
$ grep 'connect ()' gdb_bt_32730_1550171205.log | wc -l
      63
```

Is your distributed setup built in the way that the master actively connects to the child zone endpoints? I would also check whether their connection is slow or even blocked resulting in TCP timeouts. 

Maybe the satellite/agents connect themselves, so the master does unwanted work here and blocks other sessions like the REST API (there is a problem somewhere in the API threadpool, but we need to mitigate this).

**Comment by zahodi** [comment] 2019-02-15 18:00
Yea, we have icinga agents running on our endpoints and master connects to all of them. We have almost 1000 endpoints and 10000 services in our icinga right now and most of them we are checking over a satellite connection, which has high latency on a good day and constant timeouts on a bad day.

**Comment by dnsmichi** [comment] 2019-02-18 14:16
Ok, last question - your upgrade path was from 2.9.x or older directly to 2.10.2, you did not have 2.10.{0,1} installed before this, right?

**Comment by zahodi** [comment] 2019-02-18 18:36
We actually went from 2.8.x to 2.10.1. I've also tested this on fresh install with 2.10.1 and 2.10.2

**Comment by zahodi** [comment] 2019-02-19 06:46
I went looking through icinga2 documentation and it seems that we have an unnecessary config on our clients to allow establishment of client -> master communication on top of master -> client communication. https://icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#distributed-monitoring-advanced-hints-connection-direction

We'll clean this up but I don't think this is core of the problem since the issue occurs on both our prod and staging icinga. Our clients do not establish a connection direction to staging icinga. 

Are we possibly running into the limits of how many endpoints a single master can support?

**Comment by dnsmichi** [comment] 2019-02-19 09:45
It is a side effect, and everything which reduces the amount of possible drawbacks, is a good thing imho. You're like running into the following problem:

- Previous versions just spawned a thread for every connection (outbound and inbound), so those hanging connects plus incoming requests were just firing hundreds of threads. Icinga was reacting slow, but you didn't really recognize it, since connections happened.
- 2.10 moved a thread pool in the middle which arbitrarily controls the needed amount of threads and likely stalls at some point.

We're currently investigating on this, and are in the midst of rewriting the network stack parts involved here (there's one developer working full time on it). This is a bigger change and will happen with 2.11. As such, I am assigning this issue for 2.11.

**Comment by einar-indrida** [comment] 2019-02-21 18:15
Further info, if it helps.

Over time we see more and more API connections getting to the state of "CLOSE_WAIT", and eventually, the API stops working.  I have not done the stacktrace (etc) described above yet, as it just fell on my desk.  But does this increase in "CLOSE_WAIT" statuses help in anyway in finding this bug in the API?

**Comment by Al2Klimov** [comment] 2019-03-11 15:12
This issue has been addressed by #7005.

**Comment by dnsmichi** [comment] 2019-04-11 14:44
Hi @einar-indrida and @zahodi,

snapshot packages are available for testing. Additional details about them can be found here: https://icinga.com/docs/icinga2/snapshot/doc/21-development/#snapshot-packages-nightly-builds

Thanks,
Michael

**Comment by einar-indrida** [comment] 2019-04-11 15:23
Thanks, Michael.  I did already upgrade to 2.10-3 (I think), and am currently one "official repo version" behind on Icinga, on the master machines.  (Upgrade is due on next monday, or so...)

This upgrade fixed our problems with the API hanging in "Close_Wait" TCP state.

Thanks,
EinarI

**Comment by dnsmichi** [comment] 2019-04-11 15:33
Oh, ok, thanks for reporting back. I thought the problem was more general, but it is good that the current stable release already fixes this. 2.10.4 only fixes some regressions and bugs in other areas.

Cheers,
Michael

**Closed by dnsmichi** 2019-04-11 15:33 UTC
Labels: API, bug
