### ISSUE TITLE
Fixed downtime which got not triggered does not set actual_end_time in ido

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icinga2#5020] opened 2017-02-22 10:53 UTC
I tried several constellations for downtimes to find out when actual_end_time is not set in IDO.

See the mysql output, I replaced row with testcase

```
*************************** Fixed downtime, triggered, canceled - fine ***************************
    downtimehistory_id: 39
           instance_id: 1
         downtime_type: 2
             object_id: 220
            entry_time: 2017-02-22 08:34:21
           author_name: icingaadmin
          comment_data: Foo
  internal_downtime_id: 1
       triggered_by_id: 0
              is_fixed: 1
              duration: 0
  scheduled_start_time: 2017-02-22 08:34:15
    scheduled_end_time: 2017-02-22 09:34:15
           was_started: 1
     actual_start_time: 2017-02-22 08:34:21
actual_start_time_usec: 492888
       actual_end_time: 2017-02-22 08:42:43
  actual_end_time_usec: 258759
         was_cancelled: 1
          is_in_effect: 0
          trigger_time: 2017-02-22 08:34:21
                  name: host!director.localdomain-1487752461-0
    endpoint_object_id: 1
*************************** Fixed Downtime, triggered, ended - fine ***************************
    downtimehistory_id: 40
           instance_id: 1
         downtime_type: 1
             object_id: 226
            entry_time: 2017-02-22 08:39:25
           author_name: icingaadmin
          comment_data: Foo
  internal_downtime_id: 2
       triggered_by_id: 0
              is_fixed: 1
              duration: 0
  scheduled_start_time: 2017-02-22 08:39:08
    scheduled_end_time: 2017-02-22 08:40:08
           was_started: 1
     actual_start_time: 2017-02-22 08:39:25
actual_start_time_usec: 66755
       actual_end_time: 2017-02-22 08:40:33
  actual_end_time_usec: 731173
         was_cancelled: 0
          is_in_effect: 0
          trigger_time: 2017-02-22 08:39:25
                  name: host!Service - httpd!director.localdomain-1487752765-0
    endpoint_object_id: 1
*************************** Fixed Downtime, not triggered, ended - no actual_end_time ***************************
    downtimehistory_id: 41
           instance_id: 1
         downtime_type: 2
             object_id: 220
            entry_time: 2017-02-22 08:45:13
           author_name: icingaadmin
          comment_data: Foo
  internal_downtime_id: 3
       triggered_by_id: 0
              is_fixed: 1
              duration: 0
  scheduled_start_time: 2017-02-22 08:48:00
    scheduled_end_time: 2017-02-22 09:00:00
           was_started: 0
     actual_start_time: 2017-02-22 08:48:00
actual_start_time_usec: 0
       actual_end_time: NULL
  actual_end_time_usec: 0
         was_cancelled: 0
          is_in_effect: 0
          trigger_time: NULL
                  name: host!director.localdomain-1487753113-1
    endpoint_object_id: 1
*************************** Flexibel Downtime, triggered, ended - fine  ***************************
    downtimehistory_id: 42
           instance_id: 1
         downtime_type: 2
             object_id: 220
            entry_time: 2017-02-22 10:34:08
           author_name: icingaadmin
          comment_data: Foo
  internal_downtime_id: 1
       triggered_by_id: 0
              is_fixed: 0
              duration: 600
  scheduled_start_time: 2017-02-22 10:33:48
    scheduled_end_time: 2017-02-22 10:35:48
           was_started: 1
     actual_start_time: 2017-02-22 10:34:08
actual_start_time_usec: 764108
       actual_end_time: 2017-02-22 10:36:42
  actual_end_time_usec: 305236
         was_cancelled: 0
          is_in_effect: 0
          trigger_time: 2017-02-22 10:34:08
                  name: host!director.localdomain-1487759648-0
    endpoint_object_id: 1
*************************** Flexible Downtime, not triggered, ended - no actual_start_time ***************************
    downtimehistory_id: 43
           instance_id: 1
         downtime_type: 1
             object_id: 227
            entry_time: 2017-02-22 10:37:39
           author_name: icingaadmin
          comment_data: Foo
  internal_downtime_id: 2
       triggered_by_id: 0
              is_fixed: 0
              duration: 600
  scheduled_start_time: 2017-02-22 10:37:23
    scheduled_end_time: 2017-02-22 10:39:23
           was_started: 0
     actual_start_time: NULL
actual_start_time_usec: 0
       actual_end_time: 2017-02-22 10:39:42
  actual_end_time_usec: 303169
         was_cancelled: 0
          is_in_effect: 0
          trigger_time: NULL
                  name: host!Service - icinga2!director.localdomain-1487759859-1
    endpoint_object_id: 1
*************************** Fixed Downtime, not triggered, canceled - fine ***************************
    downtimehistory_id: 45
           instance_id: 1
         downtime_type: 2
             object_id: 220
            entry_time: 2017-02-22 10:43:07
           author_name: icingaadmin
          comment_data: Foo
  internal_downtime_id: 4
       triggered_by_id: 0
              is_fixed: 1
              duration: 0
  scheduled_start_time: 2017-02-22 10:43:51
    scheduled_end_time: 2017-02-22 11:42:51
           was_started: 0
     actual_start_time: 2017-02-22 10:43:51
actual_start_time_usec: 0
       actual_end_time: 2017-02-22 10:43:19
  actual_end_time_usec: 738272
         was_cancelled: 1
          is_in_effect: 0
          trigger_time: NULL
                  name: host!director.localdomain-1487760187-3
    endpoint_object_id: 1
```

So at least for fixed Downtime not triggered a actual_downtime_end should be set.

**Comment by Al2Klimov** [comment] 2017-02-24 13:15
I'm afraid you're wrong.
If a downtime never gets started, it has no end.

**Comment by dnsmichi** [comment] 2017-02-24 14:28
A fixed downtime always sets start/end time, we were not able to reproduce that issue either. But we've found another issue dealing with the actual_end_time being set for flexible downtimes when it hasn't been triggered yet.

Closing this issue as invalid.

**Closed by dnsmichi** 2017-02-24 14:28 UTC
Labels: DB IDO
