### ISSUE TITLE
Windows Installation 2.11.2 MSI empty icinga2.conf

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icinga2#7627] opened 2019-11-14 14:29 UTC
The windows installation in the version 2.11.2 creates an empty icinga2.conf and even after the wizard is done the icinga2.conf is still empty.

This issues was experienced on a windows 2008 

## To Reproduce

Install Icinga2 v2.11.2 on windows.

## Your Environment
* Version used (`icinga2 --version`): 2.11.2
* Operating System and version: Windows 2008 R2

**Comment by dnsmichi** [comment] 2019-11-14 14:56
Permission problem with a group policy intercepting here?

**Comment by mkayontour** [comment] 2019-11-14 15:18
It works fine when installing the version 2.11.1, the update to 2.11.2 afterwards works also fine.

**Comment by dnsmichi** [comment] 2019-11-14 15:26
Interesting. The diff between .1 and .2 only contains config sync related fixes, nothing changed in regard of the windows package. Can you reliably reproduce this?

**Comment by Al2Klimov** [comment] 2021-09-07 15:09
_PING_ @mkayontour

**Comment by julianbrost** [comment] 2022-07-25 13:27
Closing due to missing feedback.

**Closed by julianbrost** 2022-07-25 13:27 UTC
Labels: area/setup, needs feedback, area/windows
