### ISSUE TITLE
Since version upgrade 2.7.0 match() filter via API get wrong results

### ISSUE THREAD

**Issue by blacks7** [Icinga/icinga2#5480] opened 2017-08-09 05:07 UTC
Since updating to Version 2.7.0 we get wrong results when we query icinga via API with following filters:

Query Services of all member of an host group
`match("*debian-server*", host.groups)`

Some behavior when querying all Services of an Service Group
`match("*http-server*", service.groups)`

**Comment by gunnarbeutner** [comment] 2017-08-09 05:37
Can you show me an example of the expected behavior and the input values you're using? match() had an unspecified behavior for arrays in versions older than 2.7, i.e. what you were doing was probably incorrect. Also, there don't seem to be any wildcards (*, ?) in your pattern. Is this on purpose?

**Comment by blacks7** [comment] 2017-08-09 07:28
sry the Wildcards will be erase by comment function of github. Now i post as code.

`match("*printers-server*", host.groups)
`

**The Hostgroup is definied as follow:**
```
object HostGroup "printers-server" {
  display_name = "Microsoft Printer Server"

  assign where match("*Printer*", host.vars.application) && host.vars.os == "Windows"
}
```

**The Host ist definied as follow:**
```
object Host "printserver1"{
  import "windows-host"
  display_name = "Drucker Server printserver1"
  address = "printserver1.int.fhh-infra.de"
  check_command = "hostalive"

  vars.application = "Printer"
}
```

Expected are the following result see at screenshot, which works fine in icingaweb2.
![printer_expected](https://user-images.githubusercontent.com/19566519/29109583-ce082ec0-7ce3-11e7-9ba0-06fd73f9dfc7.PNG)

When querying this via API call with on URL "https://icinga1-server:5665/v1/objects/services" i get following result:

  Service: webserver1!/
  Service: webserver2!HTTP Site - Login
  Service: webserver2!HTTP Site - Startseite
  Service: fileserver1!/
  Service: fileserver1!HTTP Site - Certficate Expiration
  [...]

Since Version upgrade to 2.7.0 the code works correct, which we are using in Icinga Dashing.

**Comment by dnsmichi** [comment] 2017-08-09 07:59
@gunnarbeutner is correct about the fact that match() did not reliably work for arrays < 2.7.0. The new corrected behaviour adds `MatchAny` or `MatchAll` as additional parameters. The latter is the default.

https://www.icinga.com/docs/icinga2/latest/doc/18-library-reference/#match

```
michi@mbmif ~/coding/icinga/icinga-vagrant (feature/enhance-map-module-demo=) $ icinga2 console
Icinga 2 (version: v2.7.0-3-ga740da2c2)
<1> => arr = [ "printer1", "printer2", "foo", "bar" ]
null
<2> => match("*printer*", arr)
false
<3> => match("*printer*", arr, MatchAny)
true
<4> => match("*printer*", arr, MatchAll)
false
```

Might need to update the docs example.

**Comment by blacks7** [comment] 2017-08-09 09:28
Hallo, thanks for answer. but the value  host.vars.application has not an Array value. It's only one text word "Printer"

**Comment by dnsmichi** [comment] 2017-08-09 16:04
The initial question was about

```
match("*debian-server*", host.groups)
```

is it this filter applied via API already which returns nothing, or is it something with the HostGroup assign rule itself?

**Comment by dnsmichi** [comment] 2017-08-11 13:04
I've updated the docs. This one looks like a configuration issue to me. Please provide more details, as otherwise I'll close it.

**Comment by blacks7** [comment] 2017-08-14 05:15
Is ok. U can close it

**Comment by lazyfrosch** [comment] 2017-08-14 06:48
Hopefully we could help you with your initial problem :wink:

**Closed by lazyfrosch** 2017-08-14 06:48 UTC
Labels: Configuration, feedback
