### ISSUE TITLE
notification concurrency/frequency limit

### ISSUE THREAD

**Issue by tclh123** [Icinga/icinga2#6221] opened 2018-04-12 10:01 UTC
Does icinga2 provide a notification concurrency/frequency limit?
Too many notification process triggered is just like a fork bomb, which crashes my box immediately.

**Comment by Crunsher** [comment] 2018-04-12 10:06
You can use notification delays to even them out and disable re-notifcations to cut down on the spam.
https://www.icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#notification-delay

**Comment by tclh123** [comment] 2018-04-12 10:15
@Crunsher Only `times.begin = <random number>` can do the "even", or the the fork bomb just take place some minutes after. And it's not good.

A rate limit function should be implemented. also need a queue to put notifications to consume.

**Comment by dnsmichi** [comment] 2018-04-12 10:24
That's a duplicate of #4594.

**Comment by tclh123** [comment] 2018-04-12 10:40
@dnsmichi Okay, I really need this for my cluster stability. Maybe you can describe your plan about how to implement it. I will see if I can make some homemade patch.

**Comment by dnsmichi** [comment] 2018-04-12 12:04
Currently there are no such plans unfortunately. The idea was to establish the same queueing mechanism as with the checkercomponent, but there's no concrete design for that.

**Comment by Crunsher** [comment] 2018-04-12 13:09
I'm closing this as duplicate.

**Closed by Crunsher** 2018-04-12 13:09 UTC
Labels: question
