### ISSUE TITLE
REST API Documentation: event streams do not work as documented

### ISSUE THREAD

**Issue by mrdsam** [Icinga/icinga2#8832] opened 2021-06-09 14:27 UTC
## Describe the bug

The example at https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#event-stream-response does not work, API returns: 

`{"error":404.0,"status":"The requested path 'v1/events' could not be found or the request method is not valid for this path."}
`
The example works if you put the parameters 'queue' and 'type' into the URL.

## To Reproduce
Try the example documented on an Icinga2-Server available to you.

## Expected behavior

Documented examples should work because otherwise you might search for mistakes for hours.

In this case, it should be clear which parameter should go into the data part and which one must appear as URL parameter. The following request works:

```
$ curl -k -s -u root:icinga -H 'Accept: application/json' \ 
 -X POST 'https://localhost:5665/v1/events?queue=myqueue&types=CheckResult' \ 
 -d '{ "filter": "event.check_result.exit_status==2" }'

```

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga 2 Version: r2.12.3-1
* Operating System and version: FreeBSD 12.2-RELEASE-p6
* Enabled features (`icinga2 feature list`): api checker ido-mysql influxdb mainlog notification

**Comment by Al2Klimov** [comment] 2021-07-12 16:31
Duplicate of #8076.

**Closed by Al2Klimov** 2021-07-12 16:31 UTC
