### ISSUE TITLE
Bug: High CPU load with Icinga2 Agent on a Windows Server 2012R2

### ISSUE THREAD

**Issue by hypermagicmountain** [Icinga/icinga2#5639] opened 2017-09-30 16:11 UTC
Problem:

We were running "Windows disk" and "Windows Memory" as checks on this server with default configuration.
Icinga2 showed the status of this server's services as "unknown" all of the sudden.

The task manager showed a CPU usage of 100% with most of it being Icinga2. After installing a newer version of the client, the problem was gone temporarily - however, it reappeared today.

We uninstalled it and are hoping for a solution / suggestions

**Agent versions we tried:**

- 2.6.2
- 2.7.0
- 2.7.1

**Windows checks we used:**

- Windows disk
- Windows memory

**Icinga2 Version:**

- r2.7.0-1

Icinga Web Version:
- 2.4.1

**Enabled features:**

- api
- checker
- command
- graphite
- ido-mysql
- mainlog
- notification

**daemon check:**
information/cli: Icinga application loader (version: r2.7.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga2
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 11 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 9 Endpoints.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 58 Notifications.
information/ConfigItem: Instantiated 207 CheckCommands.
information/ConfigItem: Instantiated 2 Downtimes.
information/ConfigItem: Instantiated 21 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 9 HostGroups.
information/ConfigItem: Instantiated 8 Dependencies.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 2 Users.
information/ConfigItem: Instantiated 61 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 23 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 CheckerComponent.

**Comment by lazyfrosch** [comment] 2017-09-30 21:37
duplicate of #5105 I guess.

Could your provide more details about your environment there? Does it happen everywhere, or just on some systems?

**Comment by lazyfrosch** [comment] 2017-09-30 21:38
duplicates #5105

**Closed by lazyfrosch** 2017-09-30 21:38 UTC

**Comment by Insurgentes** [comment] 2017-10-06 09:15
Have had this on some servers too (a handful of servers out of 500) - what
do the ones with the problem have in common? Windows2012R2 1vcpu. I am not
sure if the OS there is relevant but the 1vcpu definitely is.  As soon as
we change the server with the issue to 2vcpus there is no issue with the
Icinga2 service going to 100% (and staying there).

**Comment by hypermagicmountain** [comment] 2017-10-17 06:19
@Insurgentes 
Now that you say it...actually the machine I have trouble with runs on one virtual CPU as well. That's why the other ones dont have any problems.
Thank you!
