### ISSUE TITLE
nscp-local-disk absolute Parameter

### ISSUE THREAD

**Issue by Razorbob** [Icinga/icinga2#5447] opened 2017-08-02 08:46 UTC
![doku_wrong](https://user-images.githubusercontent.com/8940098/28865079-ea06bdc8-776e-11e7-9b68-0da6efbeb797.PNG)

If used as described

example:
nscp_disk_free = true
nscp_disk_warning = "20GB"
nscp_disk_crit = "10GB"

The Error - "Failed to validate filter see log for details: Warning expression not valid" appears.

Workaround via plugin parameters:

example:
nscp_disk_free = true
nscp_disk_warning = "20g" //or 20M for Megabyte
nscp_disk_crit = "10g" // or 10M for Megabyte

yields correct output.

Regards,
Vincent

**Comment by Crunsher** [comment] 2017-08-02 09:43
So this is a documentation issue? ("absolut" is also spelled incorrectly)

Since you already know what the issue is, you can open a PR for this~

**Comment by Razorbob** [comment] 2017-08-02 09:49
@Crunsher depends on what u guys want it to be, either  GB MB (than we would need to change code) or M g (than just fix the Doku)

**Comment by Crunsher** [comment] 2017-08-02 09:51
We don't control the plugin code. It's possible they changed their arguments, what nscp version are you using?

**Comment by Razorbob** [comment] 2017-08-02 09:56
@Crunsher, y but u guys controll the plugin call i guess.

NSClient++ 0.5.0.62 x64 (2016-09-14).
Was installed with icinga 2.6.3

**Comment by Crunsher** [comment] 2017-08-02 10:00
Nope, we could change the check command to translate GB to g for example... but I'd rather not. The current docs for nscp use single letters. I think we just need to update our docs

**Comment by Razorbob** [comment] 2017-08-02 10:05
Thats what I ment with the plugin call actually... Okay, I just thought for consistency reasons - GB MB would be the way to go, but if u want it to correspond to the nscp usage than there is no problem.

**Comment by Crunsher** [comment] 2017-08-02 11:04
@dnsmichi @gunnarbeutner Well, which is it?

**Comment by Crunsher** [comment] 2018-01-19 16:09
I decided we are not going to change but keep to it like that - for consistency. The typo has been fixed in `88730edfcf`

**Closed by Crunsher** 2018-01-19 16:09 UTC
Labels: Documentation
