### ISSUE TITLE
Icinga Agent Windows 2.8.0 msvcr120.dll is missing

### ISSUE THREAD

**Issue by Copis** [Icinga/icinga2#5780] opened 2017-11-20 15:29 UTC
## Expected Behavior

Install Icinga agent without error

## Current Behavior

Installation error "msvcr120.dll is missing"

## Possible Solution

Install Visual C++ Redistributable 2013
https://www.microsoft.com/en-us/download/details.aspx?id=40784

## Steps to Reproduce (for bugs)

1. Windows Server 2012 R2 without Visual C++ Redistributable 2013
2. Install the Update for Universal C Runtime in Windows as mentioned in documentation https://github.com/Icinga/icinga2/blob/master/doc/06-distributed-monitoring.md

## Context

Regarding the documentation, "https://github.com/Icinga/icinga2/blob/master/doc/06-distributed-monitoring.md" the update for Universal C Runtime doesn't work for me. I need to install Visual C++ Redistributable 2013
https://www.microsoft.com/en-us/download/details.aspx?id=40784

## Your Environment

* Version used (`icinga2 --version`):
]# icinga2 --version
C:\Program Files\ICINGA2\sbin>icinga2.exe --version
icinga2.exe - The Icinga 2 network monitoring daemon (version: v2.8.0-5-gdf10d2a)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: C:\Program Files\ICINGA2\
  Sysconf directory: C:\ProgramData\icinga2\etc
  Run directory: C:\ProgramData\icinga2\var\run
  Local state directory: C:\ProgramData\icinga2\var
  Package data directory: C:\Program Files\ICINGA2\\share\icinga2
  State path: C:\ProgramData\icinga2\var/lib/icinga2/icinga2.state
  Modified attributes path: C:\ProgramData\icinga2\var/lib/icinga2/modified-attr
ibutes.conf
  Objects path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.debug
  Vars path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.vars
  PID path: C:\ProgramData\icinga2\var\run/icinga2/icinga2.pid

System information:
  Platform: Windows
  Platform version: 8.1 or greater (Server)
  Kernel: Windows
  Kernel version: 6.2
  Architecture: x86_64

Build information:
  Compiler: MSVC 19.0.24215.1
  Build host: ICINGA-BUILD-WI

* Operating System and version: Windows Server 2012 R2
* Enabled features (`icinga2 feature list`): NA
* Icinga Web 2 version and modules (System - About): NA
* Config validation (`icinga2 daemon -C`): NA
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes. NA

**Comment by dnsmichi** [comment] 2017-11-20 16:09
Interesting. Thanks for the heads up, should be documented.

**Comment by gunnarbeutner** [comment] 2017-11-24 06:35
The correct way to fix this would be to redistribute those DLLs. This should not just be a documentation change.

**Comment by gunnarbeutner** [comment] 2017-11-24 06:36
http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_vcredist.html

**Comment by lazyfrosch** [comment] 2017-11-24 11:54
Also see https://github.com/Icinga/icinga-packaging/issues/64

**Comment by dnsmichi** [comment] 2017-11-24 16:02
@gunnarbeutner right, we talked about offline, thanks.

**Comment by Crunsher** [comment] 2017-12-13 16:56
As it turns out the problem was actually openssl that required msvcr120.dll. We solved this by rebuilding openssl with with Visual Studio 2015 and it now requires msvcr140, which we ship with icinga.

The issue is now fixed and all we need to do is rebuild version 2.8.0

**Closed by Crunsher** 2017-12-13 16:56 UTC
Labels: bug, high, Packages, Windows

**Comment by Tontonitch** [comment] 2017-12-15 13:07
It seems that the x86 package has been rebuilt, but not the x86_64.

![image](https://user-images.githubusercontent.com/600025/34043231-6b8dd714-e1a0-11e7-9d5d-8c6bef7094e3.png)

Would it be possible to rebuild also the x86_64? That would make our deployment process easier on our infra (reduction of the number of dependencies).

**Comment by Crunsher** [comment] 2017-12-15 15:40
Sorry for the inconvenience, new packages are up now.

**Comment by Tontonitch** [comment] 2017-12-15 15:49
Great, thanks :+1:
