### ISSUE TITLE
In case of icinga2 reload businessprocesses end with critical

### ISSUE THREAD

**Issue by emanuel-b-q** [Icinga/icinga2#7068] opened 2018-11-22 11:51 UTC
Reload of icinga2 kills all child processes and the end with return value CRITICAL

## Expected Behavior
Icinga2 shouldn't  kill the processes, or in should delay them until the reload/restart is finish and then start the checks 

## Current Behavior
Whenever there is a reload/restart of icinga2, all business processes end with a cirtical error.
The businessprocesses are child processes of the icinga2 process, so in case there is - e.g. a deployment done by director, this results worst case in a broken SLA - which is wrong!

## Possible Solution
Not sure how to solve this .... 

## Your Environment
* Module version (System - About):  2.1.0
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Operating System and version: RHEL 7.5
* Webserver, PHP versions: Apache 2.4.6 , PHP 7.1.8

**Comment by dnsmichi** [comment] 2019-04-01 08:05
Please do the following

- Verify which checks are running for such a long time, being killed then
- Either test the snapshot packages or wait for 2.11 which provides improvements in this region

**Comment by dnsmichi** [comment] 2019-07-16 09:00
Somehow a duplicate of #6873.

**Closed by dnsmichi** 2019-07-16 09:00 UTC
Labels: area/checks, needs-feedback
