### ISSUE TITLE
pretty long stacktrace on unknown host for external command

### ISSUE THREAD

**Issue by cite** [Icinga/icinga2#5172] opened 2017-04-20 08:33 UTC
When Icinga 2 receives an external service check for a host or service that is not known, not only is a warning message logged but also a stacktrace. This stacktrace is pretty long and results in a significant amount of space used for logging messages:

`[2017-04-20 10:28:32 +0200] information/ExternalCommandListener: Executing external command: [1492676912] PROCESS_SERVICE_CHECK_RESULT;fra1pro-be-bstats-1;feedcache_chile;0;All is well.|
[2017-04-20 10:28:32 +0200] warning/ExternalCommandListener: External command failed: Error: Cannot process passive service check result for non-existent service 'feedcache_chile' on host 'fra1pro-be-bstats-1'

	(0) libicinga.so.2.6.3: <unknown function> (+0x126ab1) [0x2b7ae833bab1]
	(1) libicinga.so.2.6.3: icinga::ExternalCommandProcessor::ProcessServiceCheckResult(double, std::vector<icinga::String, std::allocator<icinga::String> > const&) (+0x5d1) [0x2b7ae83d4491]
	(2) libicinga.so.2.6.3: icinga::ExternalCommandProcessor::Execute(double, icinga::String const&, std::vector<icinga::String, std::allocator<icinga::String> > const&) (+0x61e) [0x2b7ae83d083e]
	(3) libicinga.so.2.6.3: icinga::ExternalCommandProcessor::Execute(icinga::String const&) (+0x1f3) [0x2b7ae83d2543]
	(4) libcompat.so.2.6.3: <unknown function> (+0x35a68) [0x2b7ae8d6ba68]
	(5) libboost_thread.so.1.63.0: <unknown function> (+0x12eda) [0x2b7ad16c2eda]
	(6) libpthread.so.0: <unknown function> (+0x7aa1) [0x2b7ad4aa6aa1]
	(7) libc.so.6: clone (+0x6d) [0x2b7ad4da5aad]
`

## Expected Behavior
I'd expect Icinga 2 to log a warning message but not a stacktrace.

## Current Behavior
Icinga 2 logs a warning message AND a stacktrace.

## Steps to Reproduce (for bugs)
1. Send passive service check result to command socket.

## Your Environment

* Version used (`icinga2 --version`): r2.6.3-1
* Operating System and version: CentOS release 6.8 (Final)

**Comment by dnsmichi** [comment] 2017-04-20 08:38
Duplicate of #3483.

**Closed by dnsmichi** 2017-04-20 08:38 UTC
