### ISSUE TITLE
check_ipmi_sensor exits with exit code 3 since update to 2.8.3

### ISSUE THREAD

**Issue by nazco** [Icinga/icinga2#6258] opened 2018-04-25 09:55 UTC
We've updated our Icinga installation this morning to 2.8.3. Since then the check_ipmi_sensor check fails with the exit code 3 if called directly by icinga.
If we run the check manually with the exact same parameters and the icinga user everything works well.

Debug log:

> [2018-04-25 11:45:32 +0200] notice/Process: Running command '/usr/lib/nagios/plugins/check_ipmi_sensor' '-D' 'LAN_2_0' '-H' '10.10.10.21' '-f' '/etc/ipmi/ipmi.cfg': PID 13000
> [2018-04-25 11:45:33 +0200] notice/Process: PID 13000 ('/usr/lib/nagios/plugins/check_ipmi_sensor' '-D' 'LAN_2_0' '-H' '10.10.10.21' '-f' '/etc/ipmi/ipmi.cfg') terminated with exit code 3

We run a distributed setup with one master and three satellites. The systems are debian stretch based and we use the official project repository. After updating all three satellites all of them are effected.

It seems there is a change how the check is called in the latest version breaking this check.

icinga2 --version: 
> [2018-04-25 11:58:08 +0200] warning/icinga-app: Sysconfig file '/etc/sysconfig/icinga2' cannot be read. Using default values.
> icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.3-1)
> 
> Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
> License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Application information:
>   Installation root: /usr
>   Sysconf directory: /etc
>   Run directory: /run
>   Local state directory: /var
>   Package data directory: /usr/share/icinga2
>   State path: /var/lib/icinga2/icinga2.state
>   Modified attributes path: /var/lib/icinga2/modified-attributes.conf
>   Objects path: /var/cache/icinga2/icinga2.debug
>   Vars path: /var/cache/icinga2/icinga2.vars
>   PID path: /run/icinga2/icinga2.pid
> 
> System information:
>   Platform: Debian GNU/Linux
>   Platform version: 9 (stretch)
>   Kernel: Linux
>   Kernel version: 4.9.0-6-amd64
>   Architecture: x86_64
> 
> Build information:
>   Compiler: GNU 6.3.0
>   Build host: 123014c49ce1
>

**Comment by Crunsher** [comment] 2018-04-25 10:52
Seems to be a duplicate of #6257 Strange issue...

**Closed by Crunsher** 2018-04-25 10:52 UTC
