### ISSUE TITLE
ITL - check_by_ssh - * in path does not work with icinga2 but on cli

### ISSUE THREAD

**Issue by schirrmie** [Icinga/icinga2#8296] opened 2020-09-29 11:22 UTC
## Describe the bug

We try to use a '*' in command path with check_by_ssh. We need this, because Debian and Redhat have different install dir for nagios plugins (/usr/lib & /usr/lib64).
With the following it doesn't matter if the check command is in /usr/lib or /usr/lib64

```
  vars.PluginDir = "/usr/lib*/nagios/plugins"
  vars.by_ssh_command = vars.PluginDir + "/check_users"
```

With icinga2 this does not work. We get unknown and the following return
`Remote command execution failed: bash: /usr/lib*/nagios/plugins/check_users: No such file or directory`

In the debug.log we have following lines:

```
[11:20:46][root@monitoring01:/]$ grep 21121 /var/log/icinga2/debug.log
[2020-09-29 11:13:37 +0200] notice/Process: Running command '/usr/lib/nagios/plugins/check_by_ssh' '-C' ''/usr/lib*/nagios/plugins/check_users' '-c' '15' '-w' '10'' '-H' 'hostname.local' '-i' '/etc/icinga2/conf.d/icinga_agent.key' '-l' 'icinga_agent' '-o' 'StrictHostKeyChecking=no' '-o' 'ControlMaster=auto' '-o' 'ControlPath=/var/run/icinga2/hostname.local' '-o' 'ControlPersist=20m' '-q' '-t' '300': PID 21121
[2020-09-29 11:13:37 +0200] notice/Process: PID 21121 ('/usr/lib/nagios/plugins/check_by_ssh' '-C' ''/usr/lib*/nagios/plugins/check_users' '-c' '15' '-w' '10'' '-H' 'hostname.local' '-i' '/etc/icinga2/conf.d/icinga_agent.key' '-l' 'icinga_agent' '-o' 'StrictHostKeyChecking=no' '-o' 'ControlMaster=auto' '-o' 'ControlPath=/var/run/icinga2/hostname.local' '-o' 'ControlPersist=20m' '-q' '-t' '300') terminated with exit code 3
```

If we run the exact same command on cli it does work:
```
[13:16:12][root@monitoring01:/]$ '/usr/lib/nagios/plugins/check_by_ssh' '-C' ''/usr/lib*/nagios/plugins/check_users' '-c' '15' '-w' '10'' '-H' 'hostname.local' '-i' '/etc/icinga2/conf.d/icinga_agent.key' '-l' 'icinga_agent' '-o' 'StrictHostKeyChecking=no' '-o' 'ControlMaster=auto' '-o' 'ControlPath=/var/run/icinga2/hostname.local' '-o' 'ControlPersist=20m' '-q' '-t' '300'
USERS OK - 1 users currently logged in |users=1;10;15;0
```

## To Reproduce
check_by_ssh service with a `/usr/lib*/nagios/plugins/check_users`

## Expected behavior

a working service

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.12.0-1
```
[13:16:14][root@monitoring01:/]$ icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.0-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 4.19.0-9-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

```
* Operating System and version: icinga2 server: Debian 10, monitored hosts: Debian 10 & CentOS 7
* Enabled features (`icinga2 feature list`):
```
[13:18:26][root@monitoring01:/]$ icinga2 feature list
Disabled features: command compatlog debuglog elasticsearch gelf graphite icingadb influxdb livestatus notification opentsdb perfdata statusdata
Enabled features: api checker mainlog syslog

```
* Icinga Web 2 version and modules (System - About): 2.8.2
* Config validation (`icinga2 daemon -C`): valid
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by Al2Klimov** [comment] 2020-10-28 14:50
Hello @schirrmie and thank you for reporting!

Have you tried to add a custom variable – say – _distro_ and make `vars.PluginDir` the following:

```
var that = this
vars.PluginDir = function() use (that) {
  if (that.vars.distro == "Debian") {
    return "/usr/lib/nagios/plugins"
  }
  return "/usr/lib64/nagios/plugins"
}
```

Best,
AK

**Comment by schirrmie** [comment] 2020-11-02 13:18
Hi,
thank you for your answer.
Your example is how we do it today. We have two templates for Debian based and RedHat Based systems. But I want only one template for all with "/usr/lib*" :)
And like I wrote, it is working on CLI but not with icinga2. For me this is a bug.

Regards

**Comment by julianbrost** [comment] 2020-11-02 13:46
There is really nothing that Icinga can do about this. Running the command in a shell worked because the host you ran `check_by_ssh` on and the one it connected to were running the same distribution, as the glob was expanded locally but has to work remotely. If you run it on Debian and the remote is RedHat (or the other way around), it would fail. If anything could do something about it, then it's `check_by_ssh` which would have to issue a command on the remote host that expands the glob.

**Comment by Al2Klimov** [comment] 2020-11-02 13:50
> There is really nothing that Icinga can do about this.

**Comment by schirrmie** [comment] 2020-11-02 13:51
But i call it with single quotes in bash. Single quotes in bash does not expand the '*'. For me your explanation is wrong.

**Comment by julianbrost** [comment] 2020-11-02 14:26
Ok, I misread your command, however your command does not reproduce what Icinga is executing, note the difference between the following:

```
$ echo '/b*/echo'
/b*/echo
$ echo ''/b*/echo''
/bin/echo
$ echo ''/b*/echo' 'foo''
/b*/echo foo
```

So what Icinga actually executed is `/usr/lib/nagios/plugins/check_by_ssh -C "'/usr/lib*/nagios/plugins/check_users' -c [...]" -H [...]` whereas in the shell, you effectively executed `/usr/lib/nagios/plugins/check_by_ssh -C '/usr/lib*/nagios/plugins/check_users -c [...]' -H [...]` (note that there are no single quotes around the inner check_users command) which makes the difference in the end. So check_by_ssh in the end just executes a single command using /bin/sh, thus expanding globs.

This extra quoting happens due to escaping done by the `by_ssh` definition:

https://github.com/Icinga/icinga2/blob/d059947107244670e31353edbacabf5c4cf04f55/itl/command-plugins.conf#L2167-L2180

But I'm pretty sure just removing this would break existing setups.

**Comment by Al2Klimov** [comment] 2020-11-02 14:28
I'd still opt for not fixing this as I consider the user's current workaround reasonable.

**Comment by julianbrost** [comment] 2020-11-02 14:43
Given the `by_ssh` definition, just setting a full command in `by_ssh_command` and not using `by_ssh_arguments` should also work:

```
vars.by_ssh_command = "/usr/lib*/nagios/plugins/check_users -c 15 -w 10"
```

**Comment by Al2Klimov** [comment] 2021-09-28 16:33
@schirrmie Is this a reasonable workaround for you?

**Comment by Al2Klimov** [comment] 2022-10-11 13:19
I opt for not fixing this as there are already multiple workarounds for this special case and closing this due to missing feedback, but you, Julian, have re-opened this... 🤷‍♂️

**Comment by julianbrost** [comment] 2022-10-11 14:02
I reopened it because it was closed based on a wrong assumption.

Now when thinking about this again, I'd say escaping the command (and all arguments) is the most sane thing to do in this situation. `*` is one thing, but the next question would be whether variables should be allowed/escaped, what about whitespace, what about command substitution? In the end it would be strange if we did some weird escaping that would only escape some of this.

If you want control over the exact command passed to `check_by_ssh`, you can set the full command to be interpreted by a shell in `by_ssh_command` as described in https://github.com/Icinga/icinga2/issues/8296#issuecomment-720514032 and not set `by_ssh_arguments`.

**Closed by julianbrost** 2022-10-11 14:02 UTC
Labels: needs feedback, area/checks, TBD
