### ISSUE TITLE
Icinga2 Agent communication on virtual resources

### ISSUE THREAD

**Issue by pdeneu** [Icinga/icinga2#5745] opened 2017-11-10 07:32 UTC
I have to monitor virtual instances / cluster resources on linux / windows and execute agent based checks against these resources.

## Current Behavior
In the old way, using something like check_by_ssh or nrpe, it was quite easy to execute checks on a host while connection it through different ip addresses or hostnames.
For example: theres a host cluster, existing of two physical machines and one cluster resource (ip address and process). For checking the the process i have to connect to the resource ip address (vip or whatever).
Doing it with icinga2 agent tells me using the wrong certificate: 
```
[2017-11-10 08:10:36 +0100] warning/ApiListener: Unexpected certificate common name while connecting to endpoint 'cluster-resources': got 'cluster-node-1'
Context:
        (0) Handling new API client connection
```
i tried to manualy add the certificates for all cluster resources to every cluster node and also added the resources as endpoints and zones to the zones.conf, but without effect.

Any idea or request for solving this? Is it me, whos doing something in the completley wrong way?

Thanks a lot.

## Your Environment

* Version used (`icinga2 --version`): r2.7.1-1
* Operating System and version: SUSE Linux Enterprise Server 11 SP4
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dgoetz** [comment] 2017-11-10 07:39
Duplicate of https://github.com/Icinga/icinga2/issues/5108 where I already tried to write down some ideas who it could look like.

**Comment by dnsmichi** [comment] 2017-11-13 09:56
Thanks @dgoetz

**Closed by dnsmichi** 2017-11-13 09:56 UTC
