### ISSUE TITLE
[dev.icinga.com #12955] Satellites servers in the same zone.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4744] opened 2016-10-21 13:56 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12955

**Created by maelig on 2016-10-21 13:56:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-21 13:56:01 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

Configuration : 2 masters and 3 satellites

Is it possible that a satellite server in the same zone is independent of the other two satellites servers ? I want this server checks only services configure with parameter command\_endpoint and so not load balancing.

Thank you for your help.

---

**Relations**:

* relates [#10977](https://dev.icinga.com/issues/10977)

**Comment by gunnarbeutner** [comment] 2017-02-07 10:13
If anything this is a duplicate of #10977.

**Closed by gunnarbeutner** 2017-02-07 10:13 UTC
Labels: Cluster, duplicate
