### ISSUE TITLE
unable to start icinga2 after reinstallation

### ISSUE THREAD

**Issue by manjitp46** [Icinga/icinga2#5380] opened 2017-06-28 06:16 UTC
icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/usr/lib/systemd/system/icinga2.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2017-06-28 11:35:20 IST; 9min ago
  Process: 10163 ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/sysconfig/icinga2 (code=exited, status=6)

Jun 28 11:35:20 centos7 systemd[1]: Starting Icinga host/service/network monitoring system...
Jun 28 11:35:20 centos7 prepare-dirs[10163]: execvp: Argument list too long
Jun 28 11:35:20 centos7 prepare-dirs[10163]: Could not fetch RunAsUser variable. Error ''. Exiting.
Jun 28 11:35:20 centos7 systemd[1]: icinga2.service: control process exited, code=exited status=6
Jun 28 11:35:20 centos7 systemd[1]: Failed to start Icinga host/service/network monitoring system.
Jun 28 11:35:20 centos7 systemd[1]: Unit icinga2.service entered failed state.
Jun 28 11:35:20 centos7 systemd[1]: icinga2.service failed.

errors with status code 6 is coming
contents of my sysconfig file:

[root@centos7 /]# cat /etc/sysconfig/icinga2
DAEMON=/usr/sbin/icinga2
ICINGA2_CONFIG_FILE=/etc/icinga2/icinga2.conf
ICINGA2_RUN_DIR=/run
ICINGA2_STATE_DIR=/var
ICINGA2_PID_FILE=$ICINGA2_RUN_DIR/icinga2/icinga2.pid
ICINGA2_ERROR_LOG=/var/log/icinga2/error.log
ICINGA2_STARTUP_LOG=/var/log/icinga2/startup.log
ICINGA2_LOG=/var/log/icinga2/icinga2.log
ICINGA2_USER=icinga
ICINGA2_GROUP=icinga
ICINGA2_COMMAND_GROUP=icingacmd

**Comment by gunnarbeutner** [comment] 2017-06-28 06:17
This is a duplicate of #5367. Please have a look at the other ticket for more information.

**Closed by gunnarbeutner** 2017-06-28 06:17 UTC
