### ISSUE TITLE
2.12 RC31...11 stuck on reload Ubuntu 18.04

### ISSUE THREAD

**Issue by powelleb** [Icinga/icinga2#8021] opened 2020-05-20 01:17 UTC
## Describe the bug
I know these are snapshots, but we have been testing due to zone bug reported in #7981 for 2.11.3 Satellites

2.12 RC7 fixed zone issue from #7981 

Semi-Live Landscape - 
3 Tier Landscape 
Level 1 (Master with 2 nodes)  2.11.3 / 2.12 RCx
Level 2 (Satellite with 2 nodes) 2.12 RCx / 2.12 RCx
Level 3 (Satellite with 1 node) 2.12 RCx

Tracking snapshots we noted this behavior with RC11, RC13, RC19:
1) Restart no problem and loads configs from Level 1 Master/Level 2 Satellite
2) Next (1st) Reload loads config from Level 1 Master/ Level 2 Satellite
3) Next (2nd) Reload process starts, but never completes on Satellite (Level 1 node 2, Level 2 Satellites)

Current time UTC 00:55
Note pid 5925 is new proc, and it has been in reload for 45 minutes.  
and though icinga2 says it killed it @ 00:35 still running (**30 minutes**).

Every 2.0s: ps -ef|grep sbin/icinga2|grep -v grep;echo "\n\n";service icinga2 status                                                                                                        level2sat01: Wed May 20 00:55:30 2020

**nagios    5925 15031  0 00:05 ?        00:00:06 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log**
nagios   15031     1  0 May19 ?        00:00:00 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
nagios   21482 15031  2 May19 ?        00:01:38 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
nagios   21684 21482  0 May19 ?        00:00:01 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log

● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/icinga2.service.d
           └─limits.conf
   Active: reloading (reload) since Tue 2020-05-19 23:22:43 UTC; 1h 31min ago
 Main PID: 15031 (icinga2)
    Tasks: 38
   CGroup: /system.slice/icinga2.service
           ├─ 5925 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
           ├─15031 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
           ├─21482 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
           └─21684 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log

May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 5 Endpoints.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 2 ApiUsers.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 361 Users.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 318 CheckCommands.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 108 Services.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/cli: Closing console log.
May 19 23:22:43 level2sat01 systemd[1]: Started Icinga host/service/network monitoring system.
**May 20 00:35:43 level2sat01 systemd[1]: icinga2.service: Reload operation timed out. Killing reload process.**

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): v2.12.0-rc1-19-gf71be9e80
* Operating System and version: aws #18~18.04.1Ubuntu
* Enabled features (`icinga2 feature list`):  api checker ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About):
company	1.0.0
cube	1.1.0
downtimecommander	0.0.1
enforceddashboard	0.0.0
ipl	v0.3.0
monitoring	2.8.0+rc1
pdfexport	0.9.1
pnp	1.1.0
reactbundle	0.7.0
reporting	0.10.0
setup	2.8.0+rc1

* Config validation (`icinga2 daemon -C`):
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 6 NotificationCommands.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 FileLogger.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 260 Notifications.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 7647 HostGroups.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 84 Hosts.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 5 Zones.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 5 Endpoints.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 2 ApiUsers.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 361 Users.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 318 CheckCommands.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 108 Services.
[2020-05-20 01:05:18 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-05-20 01:05:18 +0000] information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

Wed May 20 01:06:22$ icinga2 object list --type Endpoint
Object 'level1master02' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 10:1-10:40
  * __name = "level1master02"
  * host = "100.92.13.228"
    % = modified in '/etc/icinga2/zones.conf', lines 11:9-11:30
  * log_duration = 86400
  * name = "level1master02"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 12:9-12:21
  * source_location
    * first_column = 1
    * first_line = 10
    * last_column = 40
    * last_line = 10
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level1master02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 10:1-10:40
  * type = "Endpoint"
  * zone = ""

Object 'level3sat01' of type 'Endpoint':
  % declared in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 1:0-1:40
  * __name = "level3sat01"
  * host = "10.7.1.210"
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 2:5-2:23
  * log_duration = 86400
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 4:5-4:21
  * name = "level3sat01"
  * package = "_cluster"
  * port = "5665"
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 3:5-3:17
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 40
    * last_line = 1
    * path = "/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf"
  * templates = [ "level3sat01" ]
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 1:0-1:40
  * type = "Endpoint"
  * zone = "level2_zone"

Object 'level2sat01' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 19:1-19:40
  * __name = "level2sat01"
  * host = ""
  * log_duration = 86400
  * name = "level2sat01"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 19
    * last_column = 40
    * last_line = 19
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level2sat01" ]
    % = modified in '/etc/icinga2/zones.conf', lines 19:1-19:40
  * type = "Endpoint"
  * zone = ""

Object 'level1master01' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 6:1-6:40
  * __name = "level1master01"
  * host = "100.92.12.49"
    % = modified in '/etc/icinga2/zones.conf', lines 7:9-7:29
  * log_duration = 86400
  * name = "level1master01"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 8:9-8:21
  * source_location
    * first_column = 1
    * first_line = 6
    * last_column = 40
    * last_line = 6
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level1master01" ]
    % = modified in '/etc/icinga2/zones.conf', lines 6:1-6:40
  * type = "Endpoint"
  * zone = ""

Object 'level2sat02' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 22:1-22:40
  * __name = "level2sat02"
  * host = "100.92.13.111"
    % = modified in '/etc/icinga2/zones.conf', lines 23:9-23:30
  * log_duration = 86400
  * name = "level2sat02"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 24:9-24:21
  * source_location
    * first_column = 1
    * first_line = 22
    * last_column = 40
    * last_line = 22
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level2sat02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 22:1-22:40
  * type = "Endpoint"
  * zone = ""

root@level2sat01:/etc/icinga2
Wed May 20 01:06:34$ icinga2 object list --type Zone
Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 32:1-32:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 33:2-33:14
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 32
    * last_column = 30
    * last_line = 32
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 32:1-32:30
  * type = "Zone"
  * zone = ""

Object 'level2_zone' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 27:1-27:24
  * __name = "level2_zone"
  * endpoints = [ "level2sat01", "level2sat02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 28:2-28:67
  * global = false
  * name = "level2_zone"
  * package = "_etc"
  * parent = "global"
    % = modified in '/etc/icinga2/zones.conf', lines 29:2-29:18
  * source_location
    * first_column = 1
    * first_line = 27
    * last_column = 24
    * last_line = 27
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level2_zone" ]
    % = modified in '/etc/icinga2/zones.conf', lines 27:1-27:24
  * type = "Zone"
  * zone = ""

Object 'level3_zone' of type 'Zone':
  % declared in '/var/lib/icinga2/api/zones/level2_zone/director/zones.conf', lines 1:0-1:21
  * __name = "level3_zone"
  * endpoints = [ "level3sat01" ]
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/zones.conf', lines 3:5-3:45
  * global = false
  * name = "level3_zone"
  * package = "_cluster"
  * parent = "level2_zone"
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/zones.conf', lines 2:5-2:25
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 21
    * last_line = 1
    * path = "/var/lib/icinga2/api/zones/level2_zone/director/zones.conf"
  * templates = [ "level3_zone" ]
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/zones.conf', lines 1:0-1:21
  * type = "Zone"
  * zone = "level2_zone"

Object 'global' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 14:1-14:20
  * __name = "global"
  * endpoints = [ "level1master01", "level1master02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 15:9-15:74
  * global = false
  * name = "global"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 14
    * last_column = 20
    * last_line = 14
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global" ]
    % = modified in '/etc/icinga2/zones.conf', lines 14:1-14:20
  * type = "Zone"
  * zone = ""

Object 'director-global' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 36:1-36:29
  * __name = "director-global"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 37:2-37:14
  * name = "director-global"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 36
    * last_column = 29
    * last_line = 36
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "director-global" ]
    % = modified in '/etc/icinga2/zones.conf', lines 36:1-36:29
  * type = "Zone"
  * zone = ""

**Comment by Al2Klimov** [comment] 2020-05-20 12:43
Hello @powelleb and thank you for reporting!

1. The Icinga versions of your master nodes mismatch
2. Some satellites run a newer version that some masters

Please fix that.

Best,
AK

**Comment by powelleb** [comment] 2020-05-21 00:07
3 Tier Landscape
Level 1 (Master with 2 nodes) 2.12.RC23 / 2.12.RC23
Level 2 (Satellite with 2 nodes) 2.12.RC23 / 2.12.RC23
Level 3 (Satellite with 1 node) 2.12.RC23

Behavior:
**ROUND 1 -**
Upgrade all servers to current snapshot.   RC23

1st reload
ALL Level 1, Level 2, Level 3 OK
3 minutes

2nd reload
Level 1 Master Node 1 stuck on reload.
Waited 10 minutes, 
service icinga2 restart on Level 1 Master Node 1
after restart of Level 1 Master Node 1 -
Level 1 Master Node 2 stuck on reload
Level 2 Satellites stuck on reload

**ROUND 2**
Stopped all servers (level 1, level 2 , level 3)
(1) cleared all files/subs in /var/lib/icinga2/api/ -R
(2) cleared icinga2.state modified-attributes.conf /var/lib/icinga2/
(3) cleared all files /var/cache/icinga2

(4) started Level 1 Master Node 1, waited 3 minutes, 
(5) director deployment of config
(6) Level 1 Master Node 1 , reload OK
(7) another director deplpyment for new config
(8) Level 1 Master Node 1 , stuck on reload
* No other servers currently up.

Level 1 (Master with 2 nodes) 2.12.RC23 (ONLY)

icinga2 daemon -C
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 6 NotificationCommands.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 1 FileLogger.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 7579 Notifications.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 1 PerfdataWriter.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 7655 HostGroups.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 601 Hosts.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 66 Zones.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 10 Endpoints.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 2 ApiUsers.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 361 Users.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 319 CheckCommands.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 1 LivestatusListener.
[2020-05-21 00:06:02 +0000] information/ConfigItem: Instantiated 3810 Services.
[2020-05-21 00:06:02 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-05-21 00:06:02 +0000] information/cli: Finished validating the configuration file(s).



Tracking snapshots we noted this behavior with

**Comment by powelleb** [comment] 2020-06-09 02:39
Tested RC31 this evening.  same behavior.   
First start is fine.  
First reload is fine, then on second reload, 
after valiation, the a new process is created but never takes over from old processes,
and reload status remains stuck.

**Comment by Al2Klimov** [comment] 2020-06-10 09:56
Hello again @powelleb!

Please could you test [these packages](https://github.com/Icinga/icinga2/actions/runs/129637467)?

If they don't help, please provide us [backtraces](https://icinga.com/docs/icinga2/latest/doc/21-development/#gdb-backtrace-from-running-process) into [this folder](https://nextcloud.icinga.com/index.php/s/Cr3sNdrFnrYn3xf).

Best,
AK

**Comment by powelleb** [comment] 2020-06-11 00:54
@Al2Klimov
Testing **bionic-0_amd64**

So far no issues on Reloading.

We will be doing the next stress test on Friday 2020-06-12 with 15K hosts, and 245K services.
I will report back if we see any issues.   otherwise I  will close over the weekend.

Thanks for the packages.

br,
Eric

**Comment by powelleb** [comment] 2020-06-14 00:13
Stress tested the deployment with 22K hosts and 280K service checks on the master, and master + master/satellite.  So far no problems.  

The final deployment will have:
67 zones (3 Tier landscape)
 -   1 Zone Master
 -   7 Zones Satellites
 -   59 Zones Satellites

~22K Hosts
~400K Service checks

closing the issue.

**Comment by N-o-X** [comment] 2020-06-15 06:58
Hi @powelleb,

i'm glad this fixed your issue. I'll reopen this issue, because it will be closed when the fixes are merged.

Thanks for your help!

Greetings
Noah

**Comment by Al2Klimov** [comment] 2020-06-15 13:07
@powelleb Please could you reproduce the issue with https://github.com/Icinga/icinga2/actions/runs/135836663 and provide the Icinga logs during the bad reload?

**Comment by powelleb** [comment] 2020-06-16 02:01
@Al2Klimov
i pulled the bionic package and tested (rc46),
Two things.

(1)
the reload still does not fail on the master like with rc31.
the only diff is the amount of config right now.  
3k hosts, 33K services.

I will be able to do a full load test again 2020-06-16 1500 EST, 
with all hosts and service checks from the CMDB.  
22K hosts, 280K service checks.

(2)
launching gdb, i get  the following error

```
/build/gdb-kAlH5B/gdb-8.1/gdb/dictionary.c:690: internal-error: void insert_symbol_hashed(dictionary*, symbol*): Assertion `SYMBOL_LANGUAGE (sym) == DICT_LANGUAGE (dict)->la_language' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) n
```
symbols and icinga-dbg are installed.
lazyfrosch had same issue in #7532 ...but continued on so i did the same.
If i should do something different, please let me know.

I will report back tuesday nite after we do a full cmdb import again and test.
br,
Eric

**Comment by powelleb** [comment] 2020-06-17 02:50
After executing a new import from our CMDB to director, 
loaded 22K hosts and applied 282K service checks.
Over the last 5 hours, multiple reloads and no issues still 

Level 1 (Master with 2 nodes) 2.12.RC46 / 2.12.RC46

icinga2 - The Icinga 2 network monitoring daemon (version: v2.12.0-rc1-46-g1dd064419)

System information:
  Platform: Ubuntu
  Platform version: 18.04.4 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 5.3.0-1023-aws
  Architecture: x86_64

.....
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 6 NotificationCommands.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 1 FileLogger.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 312839 Notifications.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 1 PerfdataWriter.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 11586 HostGroups.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 22661 Hosts.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 3020 Downtimes.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 67 Zones.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 12 Endpoints.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 2 ApiUsers.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 442 Users.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 320 CheckCommands.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 2 ServiceGroups.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 1 TimePeriod.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 282884 Services.
[2020-06-17 02:43:14 +0000] information/ConfigItem: Instantiated 984 ScheduledDowntimes.
[2020-06-17 02:43:16 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-06-17 02:43:16 +0000] information/cli: Finished validating the configuration `file(s).

regards,
eric

**Comment by Al2Klimov** [comment] 2020-06-17 10:09
I.e. the packages I gave you also solved your issue? If yes, please also test the current snapshots.

**Comment by powelleb** [comment] 2020-06-17 10:31
I just pulled down latest snapshot.   RC48.
however, the master node 1 crashed @ 0240 EST after a reload.   
master node 2 was still running.   will upgrade both to RC48, and 
keep all of CMDB config for next 24 hours to do a burn in and look for
issues.

**Comment by powelleb** [comment] 2020-06-21 01:55
Repo snapshot RC48 has been running stable in our landscape for 4 days now.   No reload issues.

**Comment by Al2Klimov** [comment] 2020-06-22 08:05
@N-o-X Shall we close this one?

**Closed** 2020-07-21 12:41 UTC
Labels: needs-feedback
