### ISSUE TITLE
Need to restart Icinga2 service on all masters to re-evaluate existing apply rules if hosts attributes are modified through API

### ISSUE THREAD

**Issue by xiumei-77** [Icinga/icinga2#7774] opened 2020-01-23 01:46 UTC
## Describe the bug

We have two icinga2 instances operating as master with a mysql database on each host with master-master replication. Then we have four endpoints which use API to receive config automatically as monitor nodes.

We apply rules for hosts to generate service objects for monitoring. Meanwhile, host vars are required to be updated under certain scenarios. As said in Icinga2 api documentation that  “Modified attributes do not trigger a re-evaluation of existing static apply rules and group assignments. Delete and re-create the objects if you require such changes or consider funding this feature request.” , we delete and recreate the host when attributes need to be changed. While, existing static apply rules are not re-evaluated with new variables without restarting Icinga2 services on both masters.

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1. Create two icinga2 instances operating as master with a mysql database on each host with master-master replication.
2. Create four endpoints which use API to receive config automatically as monitor nodes.
3. Create a host as

    ```
    object Host "test-host" {
        import "generic-host"
        __name = "test-host"
        check_command = "dummy"
        display_name = "test-host"
        vars = {
            ports = {
                "port_1/1" = {
                    check = "true"
                }
                "port_1/2" = {
                    check = "true"
                }
            }
        }
        zone = "master"
    }
    ```

4. Create apply rules

    ```
    apply Service "check-port-" for (ifs => ifAttr in host.vars.ports) {
        import "generic-service"
        check_command = "dummy"
        ignore where ifAttr.check != "true"
    }
    ```

5. Delete the host with icinga api

6. Re-create the host with icinga api

    ```
    object Host "test-host" {
        import "generic-host"
        __name = "test-host"
        check_command = "dummy"
        display_name = "test-host"
        vars = {
            ports = {
                "port_2/1" = {
                    check = "true"
                }
                "port_2/2" = {
                    check = "true"
                }
            }
        }
        zone = "master"
    }
    ```

## Expected behavior

Apply rules to updated attributes with restarting Icinga2 service on the primary master only

or

Apply rules to updated attributes without restarting Icinga2 service

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): version: r2.11.0-1
* Operating System and version: Ubuntu 18.04.3 LTS \n \l
* Enabled features (`icinga2 feature list`): api checker ido-mysql mainlog
* Icinga Web 2 version and modules (System - About): 2.7.1
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

    master1
    ```
    object Endpoint "master1" {
    }
    object Endpoint "master2" {
            host = "10.10.10.12"
    }
    object Zone "master" {
            endpoints = [ "master1", "master2" ]
    }
    object Endpoint "satellite1a" {
            host = "10.10.10.13"
    }
    object Endpoint "satellite1a" {
            host = "10.10.10.14"
    }
    object Zone "region1" {
            endpoints = [ "satellite1a", "satellite1b" ]
            parent = "master"
    }
    object Endpoint "satellite2a" {
            host = "10.10.10.15"
    }
    object Endpoint "satellite2b" {
            host = "10.10.10.16"
    }
    object Zone "region2" {
            endpoints = [ "satellite2a", "satellite2b" ]
            parent = "master"
    }
    object Zone "global-templates" {
            global = true
    }
    object Zone "director-global" {
            global = true
    }
    ```

    master2
    ```
    object Endpoint "master1" {
    }
    object Endpoint "master2" {
    }
    object Zone "master" {
            endpoints = [ "master1", "master2" ]
    }
    object Endpoint "satellite1a" {
            host = "10.10.10.13"
    }
    object Endpoint "satellite1a" {
            host = "10.10.10.14"
    }
    object Zone "region1" {
            endpoints = [ "satellite1a", "satellite1b" ]
            parent = "master"
    }
    object Endpoint "satellite2a" {
            host = "10.10.10.15"
    }
    object Endpoint "satellite2b" {
            host = "10.10.10.16"
    }
    object Zone "region2" {
            endpoints = [ "satellite2a", "satellite2b" ]
            parent = "master"
    }
    object Zone "global-templates" {
            global = true
    }
    object Zone "director-global" {
            global = true
    }
    ```

    satellite1a
    ```
    object Endpoint "master1" {
    }
    object Endpoint "master2" {
    }
    object Zone "master" {
            endpoints = [ "master1", "master2" ]
    }
    object Endpoint "satellite1a" {
    }
    object Endpoint "satellite1b" {
    }
    object Zone "region1" {
            endpoints = [ "satellite1a", "satellite1b" ]
            parent = "master"
    }
    object Zone "global-templates" {
            global = true
    }
    object Zone "director-global" {
            global = true
    }
    ```

    satellite1b
    ```
    object Endpoint "master1" {
    }
    object Endpoint "master2" {
    }
    object Zone "master" {
            endpoints = [ "master1", "master2" ]
    }
    object Endpoint "satellite1a" {
    }
    object Endpoint "satellite1b" {
    }
    object Zone "region1" {
            endpoints = [ "satellite1a", "satellite1b" ]
            parent = "master"
    }
    object Zone "global-templates" {
            global = true
    }
    object Zone "director-global" {
            global = true
    }
    ```
    satellite2a
    ```
    object Endpoint "master1" {
    }
    object Endpoint "master2" {
    }
    object Zone "master" {
            endpoints = [ "master1", "master2" ]
    }
    object Endpoint "satellite2a" {
    }
    object Endpoint "satellite2b" {
    }
    object Zone "region2" {
            endpoints = [ "satellite2a", "satellite2b" ]
            parent = "master"
    }
    object Zone "global-templates" {
            global = true
    }
    object Zone "director-global" {
            global = true
    }
    ```

    satellite2b
    ```
    object Endpoint "master1" {
    }
    object Endpoint "master2" {
    }
    object Zone "master" {
            endpoints = [ "master1", "master2" ]
    }
    object Endpoint "satellite2a" {
    }
    object Endpoint "satellite2b" {
    }
    object Zone "region2" {
            endpoints = [ "satellite2a", "satellite2b" ]
            parent = "master"
    }
    object Zone "global-templates" {
            global = true
    }
    object Zone "director-global" {
            global = true
    }
    ```

## Additional context

ido-mysql.conf
object IdoMysqlConnection "ido-mysql" {
  user = "icinga2",
  password = "thepassword",
  host = "thehost",
  database = "thedatabase",
  instance_name = "default",
  enable_ha = true
}

**Comment by dgoetz** [comment] 2020-01-23 07:27
This is a duplicate of https://github.com/Icinga/icinga2/issues/4084

**Comment by htriem** [comment] 2020-01-23 11:01
Thanks, @dgoetz. Closing as a duplicate.

**Closed by htriem** 2020-01-23 11:01 UTC
