### ISSUE TITLE
Crash after upgrade to 2.10.1 from 2.9.2

### ISSUE THREAD

**Issue by smtalk** [Icinga/icinga2#6735] opened 2018-10-27 22:51 UTC
Crash report:
```
Caught unhandled exception.
Current time: 2018-10-28 01:31:44 +0300

  Application version: r2.10.1-1

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.17.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Error: Invalid NetString (missing :)

	(0) icinga2: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr<icinga::Stream> const&, icinga::String*, icinga::StreamReadContext&, bool, long) (+0xee) [0x7ade1e]
	(1) icinga2: icinga::ObjectListCommand::Run(boost::program_options::variables_map const&, std::vector<std::string, std::allocator<std::string> > const&) const (+0x435) [0x964115]
	(2) /usr/lib64/icinga2/sbin/icinga2() [0x973c63]
	(3) icinga2: main (+0x47) [0x5aed77]
	(4) libc.so.6: __libc_start_main (+0xf5) [0x7f1f498ce445]
	(5) /usr/lib64/icinga2/sbin/icinga2() [0x5bbf6e]


***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***
[New LWP 9290]
[New LWP 9289]
[New LWP 9288]
[New LWP 9287]
[New LWP 9286]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f1f49c88279 in waitpid () from /lib64/libpthread.so.0

Thread 6 (Thread 0x7f1f44b8c700 (LWP 9286)):
#0  0x00007f1f49c84995 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x000000000085650b in wait (m=..., this=0xec6e50 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+528>) at /usr/include/boost/thread/pthread/condition_variable.hpp:73
        guard = {m = 0x0}
        check_for_interruption = {thread_info = 0x15fbc00, m = 0xec6e50 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+528>, set = true}
        res = <optimized out>
#2  icinga::ThreadPool::WorkerThread::ThreadProc (this=0xec6f68 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+808>, queue=...) at ../base/threadpool.cpp:110
        lock = {m = 0xec6e28 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+488>, is_locked = false}
        wi = {Callback = {<std::_Maybe_unary_or_binary_function> = {<std::unary_function> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {_M_functor = {_M_unused = {_M_object = 0x0, _M_const_object = 0x0, _M_function_pointer = 0x0, _M_member_pointer = NULL}, _M_pod_data = '\000' <repeats 15 times>}, _M_manager = 0x0}, _M_invoker = 0x0}, Timestamp = 0}
        st = <optimized out>
        et = <optimized out>
        latency = <optimized out>
        idbuf = <incomplete type>
        lock = {m = 0xec6e28 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+488>, is_locked = false}
#3  0x00007f1f4bba527a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
No symbol table info available.
#4  0x00007f1f49c80e25 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f1f499aabad in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 5 (Thread 0x7f1f44bcd700 (LWP 9287)):
#0  0x00007f1f49c84995 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x000000000085650b in wait (m=..., this=0xec7190 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+1360>) at /usr/include/boost/thread/pthread/condition_variable.hpp:73
        guard = {m = 0x0}
        check_for_interruption = {thread_info = 0x15fbe30, m = 0xec7190 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+1360>, set = true}
        res = <optimized out>
#2  icinga::ThreadPool::WorkerThread::ThreadProc (this=0xec72a8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+1640>, queue=...) at ../base/threadpool.cpp:110
        lock = {m = 0xec7168 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+1320>, is_locked = false}
        wi = {Callback = {<std::_Maybe_unary_or_binary_function> = {<std::unary_function> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {_M_functor = {_M_unused = {_M_object = 0x7f1f44bcc8c0, _M_const_object = 0x7f1f44bcc8c0, _M_function_pointer = 0x7f1f44bcc8c0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x7f1f44bcc8c0, this adjustment 139772366470861}, _M_pod_data = "\300ȼD\037\177\000\000;@J\037\177\000"}, _M_manager = 0x0}, _M_invoker = 0xc}, Timestamp = 6.9056678793174053e-310}
        st = <optimized out>
        et = <optimized out>
        latency = <optimized out>
        idbuf = <incomplete type>
        lock = {m = 0xec7168 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+1320>, is_locked = false}
#3  0x00007f1f4bba527a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
No symbol table info available.
#4  0x00007f1f49c80e25 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f1f499aabad in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 4 (Thread 0x7f1f4c029700 (LWP 9288)):
#0  0x00007f1f49c84995 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x000000000085650b in wait (m=..., this=0xec74d0 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+2192>) at /usr/include/boost/thread/pthread/condition_variable.hpp:73
        guard = {m = 0x0}
        check_for_interruption = {thread_info = 0x15fc030, m = 0xec74d0 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+2192>, set = true}
        res = <optimized out>
#2  icinga::ThreadPool::WorkerThread::ThreadProc (this=0xec75e8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+2472>, queue=...) at ../base/threadpool.cpp:110
        lock = {m = 0xec74a8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+2152>, is_locked = false}
        wi = {Callback = {<std::_Maybe_unary_or_binary_function> = {<std::unary_function> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {_M_functor = {_M_unused = {_M_object = 0x7f1f4c0288c0, _M_const_object = 0x7f1f4c0288c0, _M_function_pointer = 0x7f1f4c0288c0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x7f1f4c0288c0, this adjustment 139772366470861}, _M_pod_data = "\300\210\002L\037\177\000\000;@J\037\177\000"}, _M_manager = 0x0}, _M_invoker = 0xc}, Timestamp = 6.9056739074937722e-310}
        st = <optimized out>
        et = <optimized out>
        latency = <optimized out>
        idbuf = <incomplete type>
        lock = {m = 0xec74a8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+2152>, is_locked = false}
#3  0x00007f1f4bba527a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
No symbol table info available.
#4  0x00007f1f49c80e25 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f1f499aabad in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7f1f4c06a700 (LWP 9289)):
#0  0x00007f1f49c84995 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x000000000085650b in wait (m=..., this=0xec7810 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+3024>) at /usr/include/boost/thread/pthread/condition_variable.hpp:73
        guard = {m = 0x0}
        check_for_interruption = {thread_info = 0x15fc2a0, m = 0xec7810 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+3024>, set = true}
        res = <optimized out>
#2  icinga::ThreadPool::WorkerThread::ThreadProc (this=0xec7928 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+3304>, queue=...) at ../base/threadpool.cpp:110
        lock = {m = 0xec77e8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+2984>, is_locked = false}
        wi = {Callback = {<std::_Maybe_unary_or_binary_function> = {<std::unary_function> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {_M_functor = {_M_unused = {_M_object = 0x7f1f4c0698c0, _M_const_object = 0x7f1f4c0698c0, _M_function_pointer = 0x7f1f4c0698c0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x7f1f4c0698c0, this adjustment 139772366470861}, _M_pod_data = "\300\230\006L\037\177\000\000;@J\037\177\000"}, _M_manager = 0x0}, _M_invoker = 0xc}, Timestamp = 6.905673920647776e-310}
        st = <optimized out>
        et = <optimized out>
        latency = <optimized out>
        idbuf = <incomplete type>
        lock = {m = 0xec77e8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+2984>, is_locked = false}
#3  0x00007f1f4bba527a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
No symbol table info available.
#4  0x00007f1f49c80e25 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f1f499aabad in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7f1f4c0ab700 (LWP 9290)):
#0  0x00007f1f49c84d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00000000007446c5 in do_wait_until (timeout=..., m=..., this=0xec6dc8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+392>) at /usr/include/boost/thread/pthread/condition_variable.hpp:108
        check_for_interruption = {thread_info = 0x7f1f20000cb0, m = 0xec6dc8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+392>, set = false}
        guard = {m = 0x7f1f4c0aa8e0}
        cond_res = <optimized out>
#2  timed_wait (a_wait_until=..., m=..., this=0xec6dc8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+392>) at /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:108
        timeout = {tv_sec = 1540679505, tv_nsec = 353450000}
#3  boost::condition_variable::timed_wait<boost::date_time::subsecond_duration<boost::posix_time::time_duration, 1000l> >(boost::unique_lock<boost::mutex>&, boost::date_time::subsecond_duration<boost::posix_time::time_duration, 1000l> const&) [clone .local.16071] (this=0xec6dc8 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+392>, m=..., wait_duration=...) at /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:123
No locals.
#4  0x0000000000a108e3 in icinga::ThreadPool::ManagerThreadProc() (this=0xec6c40 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497>) at ../base/threadpool.cpp:239
        lock = {m = 0xec6da0 <_ZZN6icinga11Application5GetTPEvE2tp.94860.68497+352>, is_locked = false}
        total_utilization = 0
        total_pending = 0
        total_alive = 0
        total_avg_latency = 0
        now = <optimized out>
        idbuf = <incomplete type>
        lastStats = 0
#5  0x00007f1f4a462070 in ?? () from /lib64/libstdc++.so.6
No symbol table info available.
#6  0x00007f1f49c80e25 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#7  0x00007f1f499aabad in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7f1f4c1b38c0 (LWP 9250)):
#0  0x00007f1f49c88279 in waitpid () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x000000000078a65e in icinga::Application::AttachDebugger (filename=..., interactive=interactive@entry=false) at ../base/application.cpp:680
        __PRETTY_FUNCTION__ = "static void icinga::Application::AttachDebugger(const icinga::String&, bool)"
#2  0x0000000000805a64 in icinga::Application::ExceptionHandler () at ../base/application.cpp:935
        sa = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        fname = {m_Data = <incomplete type>}
        dirName = {m_Data = <incomplete type>}
        interactive_debugger = false
#3  0x00007f1f4a40b746 in ?? () from /lib64/libstdc++.so.6
No symbol table info available.
#4  0x00007f1f4a40b773 in std::terminate() () from /lib64/libstdc++.so.6
No symbol table info available.
#5  0x00007f1f4a40b993 in __cxa_throw () from /lib64/libstdc++.so.6
No symbol table info available.
#6  0x0000000000a7c940 in __cxa_throw (obj=0x1611720, pvtinfo=0xba1d80 <typeinfo for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::invalid_argument> >>, dest=0x608d90 <boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::invalid_argument> >::~clone_impl()>) at ../base/exception.cpp:144
        real_cxa_throw = 0x7f1f4a40b920 <__cxa_throw>
        context = {m_Frames = {<> = {_M_impl = {<> = {<> = {<No data fields>}, <No data fields>}, _M_node = {_M_next = 0x7ffc1bf7efa0, _M_prev = 0x7ffc1bf7efa0}}}, <No data fields>}}
        tinfo = 0xba1d80 <typeinfo for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::invalid_argument> >>
        uex = <optimized out>
        ex = <optimized out>
        real_cxa_throw = 0x7f1f4a40b920 <__cxa_throw>
#7  0x0000000000753d85 in throw_exception (e=...) at /usr/include/boost/throw_exception.hpp:67
No locals.
#8  boost::exception_detail::throw_exception_<std::invalid_argument>(std::invalid_argument const&, char const*, char const*, int) [clone .local.18306] (x=..., current_function=<optimized out>, file=0xb31e5f "../base/netstring.cpp", line=62) at /usr/include/boost/throw_exception.hpp:84
No locals.
#9  0x00000000007ade1e in icinga::NetString::ReadStringFromStream (stream=..., str=0x7ffc1bf7f7e0, context=..., may_wait=<optimized out>, maxMessageLength=<optimized out>) at ../base/netstring.cpp:62
        __PRETTY_FUNCTION__ = "static icinga::StreamReadStatus icinga::NetString::ReadStringFromStream(const Ptr&, icinga::String*, icinga::StreamReadContext&, bool, ssize_t)"
#10 0x0000000000964115 in icinga::ObjectListCommand::Run (this=<optimized out>, vm=..., ap=...) at ../cli/objectlistcommand.cpp:98
        srs = <optimized out>
        type_count = {_M_t = {_M_impl = {<std::allocator> = {<__gnu_cxx::new_allocator> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7ffc1bf7f818, _M_right = 0x7ffc1bf7f818}, _M_node_count = 0}}}
        first = true
        message = {m_Data = <incomplete type>}
        fp = <incomplete type>
        objects_count = 0
        src = {Buffer = 0x1601650 "# Icinga objects cache file\n# This file is auto-generated. Do not modify this file.\n\ndefine host {\n\thost_name\tbackup.domain.info\n\tdisplay_name\tbackup.domain.info\n\talias\tbackup.domain.info\n\taddre"..., Size = 65536, MustRead = false, Eof = false}
        objectfile = {m_Data = <incomplete type>}
        sfp = {px = 0x15fee70}
        name_filter = {m_Data = <incomplete type>}
        type_filter = {m_Data = <incomplete type>}
#11 0x0000000000973c63 in Main () at icinga.cpp:681
        args = {<std::_Vector_base> = {_M_impl = {<std::allocator> = {<__gnu_cxx::new_allocator> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}
        autocomplete = false
        cmdname = {m_Data = <incomplete type>}
        command = {px = 0x15dd120}
        argc = 6
        autoindex = 0
        icingaGroup = {m_Data = <incomplete type>}
        visibleDesc = {m_caption = <incomplete type>, m_line_length = 80, m_min_description_length = 40, m_options = {<std::_Vector_base> = {_M_impl = {<std::allocator> = {<__gnu_cxx::new_allocator> = {<No data fields>}, <No data fields>}, _M_start = 0x15fe490, _M_finish = 0x15fe530, _M_end_of_storage = 0x15fe590}}, <No data fields>}, belong_to_group = {<> = {_M_impl = {<std::allocator> = {<__gnu_cxx::new_allocator> = {<No data fields>}, <No data fields>}, _M_start = {<> = {<std::iterator> = {<No data fields>}, _M_p = 0x15fd310, _M_offset = 0}, <No data fields>}, _M_finish = {<> = {<std::iterator> = {<No data fields>}, _M_p = 0x15fd310, _M_offset = 10}, <No data fields>}, _M_end_of_storage = 0x15fd318}}, <No data fields>}, groups = {<std::_Vector_base> = {_M_impl = {<std::allocator> = {<__gnu_cxx::new_allocator> = {<No data fields>}, <No data fields>}, _M_start = 0x15fe470, _M_finish = 0x15fe480, _M_end_of_storage = 0x15fe480}}, <No data fields>}}
        positionalDesc = {m_names = {<std::_Vector_base> = {_M_impl = {<std::allocator> = {<__gnu_cxx::new_allocator> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, m_trailing = <incomplete type>}
        vm = <incomplete type>
        argv = 0x7ffc1bf826f8
        icingaUser = {m_Data = <incomplete type>}
        hiddenDesc = {m_caption = <incomplete type>, m_line_length = 80, m_min_description_length = 40, m_options = {<std::_Vector_base> = {_M_impl = {<std::allocator> = {<__gnu_cxx::new_allocator> = {<No data fields>}, <No data fields>}, _M_start = 0x15fdd60, _M_finish = 0x15fdd80, _M_end_of_storage = 0x15fdd80}}, <No data fields>}, belong_to_group = {<> = {_M_impl = {<std::allocator> = {<__gnu_cxx::new_allocator> = {<No data fields>}, <No data fields>}, _M_start = {<> = {<std::iterator> = {<No data fields>}, _M_p = 0x15fdc50, _M_offset = 0}, <No data fields>}, _M_finish = {<> = {<std::iterator> = {<No data fields>}, _M_p = 0x15fdc50, _M_offset = 2}, <No data fields>}, _M_end_of_storage = 0x15fdc58}}, <No data fields>}, groups = {<std::_Vector_base> = {_M_impl = {<std::allocator> = {<__gnu_cxx::new_allocator> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}}
        rc = 1
#12 0x00000000005aed77 in main (argc=6, argv=0x7ffc1bf826f8) at icinga.cpp:975
        rc = <optimized out>
```

It happens on `/usr/sbin/icinga2 object list --type TimePeriod` time. The error is `critical/Application: Error: Invalid NetString (missing :)`.

The following fixes it:
`icinga2 daemon -C`

And the crash doesn't happen again, unless we restart the service. `/usr/sbin/icinga2 object list --type TimePeriod` works without problems until next restart.

**Comment by mcktr** [comment] 2018-10-28 18:55
Duplicate of #6705

**Closed** 2018-10-28 18:55 UTC
Labels: duplicate
