### ISSUE TITLE
[dev.icinga.com #12540] ScheduledDowntime always use next day

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4561] opened 2016-08-25 06:01 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12540

**Created by GreenRover on 2016-08-25 06:01:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-04 10:34:30 +00:00 (in Redmine)_

    Icinga Version: r2.4.10-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

NOW is: 25.08.2016 07:19:03

I add this Rule to config.

    apply ScheduledDowntime "4 - 11 - service" to Service {
        author = "icingaadmin"
        comment = "#4 HH wartung"
        ranges = {
            "2016-08-24" = "00:00-24:00"
            "2016-08-25" = "00:00-24:00"
            "2016-08-26" = "00:00-24:00"
            "2016-08-27" = "00:00-24:00"
            "2016-08-28" = "00:00-24:00"
            "2016-08-29" = "00:00-24:00"
            "2016-08-30" = "00:00-24:00"
            "2016-08-31" = "00:00-07:00"
        }
        fixed = true
        assign where service.host_name == "PC-HH"
    }

Bud the spool "/v1/objects/downtimes" shows:

    start_time: 1472162400,        // 26.08.2016 00:00:00
    end_time: 1472248800,          // 27.08.2016 00:00:00
    entry_time: 1472102343.063089, // 25.08.2016 07:19:03

The issue is based in the usage of wrong time range:

the system use:

"2016-08-26" = "00:00-24:00"

but should also add for today.

"2016-08-25" = "00:00-24:00"

Otherwise the critical services will only acknowledged at next day.

German description:
https://monitoring-portal.org/index.php?thread/37186-host-down-time-best%C3%A4tigt-services-nicht/&postID=235024#post235027

**Comment by Crunsher** [comment] 2018-09-04 11:58
Closing as duplicate of  #4790

**Closed by Crunsher** 2018-09-04 11:58 UTC
Labels: Configuration, bug, low-priority
