### ISSUE TITLE
Inconsistent response codes in schedule-downtime API

### ISSUE THREAD

**Issue by ricsil** [Icinga/icinga2#7131] opened 2019-04-19 11:14 UTC
## Describe the bug
If you call /v1/actions/schedule-downtime with appropriate type and filter but without any data, HTTP response code is 500 but response message will state that code is 400.

## To Reproduce

Provided code is python but the same should work with API query tool of your choice:

1. ```a = requests.post("https://HOSTNAME:5665/v1/actions/schedule-downtime?type=Host&filter=host.name==%22A%22", verify=False, headers={"Accept":"application/json"}, auth=("USERNAME", "PASSWORD"))```
2. ```a.status_code``` (returns ```500```)
3. ```a.text``` (returns ``` {"results":[{"code":400.0,"status":"Options \'start_time\', \'end_time\', \'author\' and \'comment\' are required"}]}```)

## Expected behavior
If I understand correctly, HTTP status code is the wrong one here. 

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.10.4
* Operating System and version: RHEL7

**Comment by ricsil** [comment] 2019-04-19 11:31
Curl example:

```
curl "https://HOSTNAME:5665/v1/actions/schedule-downtime?type=Host&filter=host.name==%22A%22" -k -u USERNAME:PASSWORD -X POST -H "Accept: application/json" -v
...
< HTTP/1.1 500 No action executed successfully
...
{"results":[{"code":400.0,"status":"Options 'start_time', 'end_time', 'author' and 'comment' are required"}]}
```

**Comment by ricsil** [comment] 2019-04-19 11:46
In general this API endpoint seems flaky:

```
curl "https://HOSTNAME:5665/v1/actions/schedule-downtime?type=Host&filter=host.name==%22A%22" -k -u USERNAME:PASSWORD -X POST -H "Accept: application/json" -d '{"fixed":false, "duration":120, "author":"me", "comment": "Test"}'
{"results":[{"code":400.0,"status":"Options 'start_time', 'end_time', 'author' and 'comment' are required"}]}
```

Even though with ```"fixed":false```, ```start_time``` and ```end_time``` should not matter?

Providing nonsensical values doesn't work either:

```
curl "https://HOSTNAME:5665/v1/actions/schedule-downtime?type=Host&filter=host.name==%22A%22" -k -u USERNAME:PASSWORD -X POST -H "Accept: application/json" -d '{"fixed":false, "duration":120, "author":"me", "comment": "Test", "start_time":0, "end_time":10}'
{"results":[{"code":500.0,"status":"Action execution failed: 'Error: Could not create downtime object.\n'."}]}
```

**Comment by dnsmichi** [comment] 2019-04-23 14:18
@htriem Please try to reproduce the issue and discuss a a possible fix.

**Comment by N-o-X** [comment] 2021-09-10 15:55
Tested all issues that got pointed out. Everything seems to be working fine now. 

> In general this API endpoint seems flaky:
> ```
> curl "https://HOSTNAME:5665/v1/actions/schedule-downtime?type=Host&filter=host.name==%22A%22" -k -u USERNAME:PASSWORD -X POST -H "Accept: application/json" -d '{"fixed":false, "duration":120, "author":"me", "comment": "Test"}'
> {"results":[{"code":400.0,"status":"Options 'start_time', 'end_time', 'author' and 'comment' are required"}]}
> ```

This is not a problem. `duration` isn't there to replace `start_time` and `end_time`, but to define the length of a flexible downtime.

I'll close this issue. If you still encounter problems with this API endpoint, please feel free to open a new issue.

**Closed by N-o-X** 2021-09-10 15:55 UTC
Labels: bug, area/api
